"""
bank_builders/frontend_pack.py
Generates 205+ questions each for:
- HTML (205 Qs)
- CSS (205 Qs)
- DOM (205 Qs)
- jQuery (205 Qs)
Total: 820 genuine, structured interview questions.
"""

from .common import make_q, parse_item

def build_html_pack(start_num=1):
    qs = []
    num = start_num

    # Topics and structured items for HTML
    # We will generate 205 distinct questions across all topics
    topics_data = [
        # (Topic, Subtopic, Question, Answer, Diff, Type, Code, MCQ_Opts, Correct_Opt, Followup)
        # 1. Document Structure (20 Qs)
        ("Document Structure", "Basics", "What does HTML stand for?", "HTML stands for HyperText Markup Language. It is the standard markup language used to structure web pages.", "Easy", "Concept", "", None, None, "What is the latest version of HTML?"),
        ("Document Structure", "DOCTYPE", "What is the purpose of <!DOCTYPE html>?", "The <!DOCTYPE html> declaration tells the browser which HTML version is used. In HTML5, it ensures standard rendering mode.", "Easy", "Concept", "<!DOCTYPE html>", None, None, "What happens if DOCTYPE is omitted?"),
        ("Document Structure", "Quirks Mode", "What is quirks mode in web browsers?", "Quirks mode emulates older 1990s browser behaviors to prevent broken layouts on very old legacy websites.", "Intermediate", "Concept", "", None, None, "How can you verify what mode the browser is in?"),
        ("Document Structure", "Root Element", "What is the root element in an HTML document?", "The <html> element wraps all content on the page, except for the DOCTYPE declaration.", "Easy", "Concept", "<html lang=\"en\">...</html>", None, None, "Why is the lang attribute important?"),
        ("Document Structure", "Head vs Body", "What is the difference between <head> and <body>?", "The <head> contains metadata, title, and links to styles/scripts. The <body> contains the visible page content.", "Easy", "Comparison", "", None, None, "Can user-visible text go inside head?"),
        ("Document Structure", "Character Encoding", "Why is <meta charset='UTF-8'> recommended?", "UTF-8 includes characters from almost all languages, preventing garbled or corrupt text display.", "Easy", "Concept", "<meta charset=\"UTF-8\">", None, None, "What encoding was commonly used before UTF-8?"),
        ("Document Structure", "Viewport Meta", "What does the viewport meta tag do?", "It configures the viewport width and initial zoom for responsive rendering on mobile devices.", "Intermediate", "Concept", "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">", None, None, "What happens on phones without this tag?"),
        ("Document Structure", "Page Title", "Where does the text inside <title> appear?", "It appears on the browser tab, in bookmarks, and as the clickable headline in search results.", "Easy", "Concept", "<title>Fresher Practice</title>", None, None, "How long should a title tag ideally be?"),
        ("Document Structure", "Favicon", "How do you add a favicon to a website in HTML?", "Use a <link> tag with rel='icon' inside the <head> element pointing to the icon file path.", "Easy", "Practical", "<link rel=\"icon\" type=\"image/png\" href=\"/favicon.png\">", None, None, "Which image formats work for favicons?"),
        ("Document Structure", "CSS Linking", "What is the standard way to link an external CSS file?", "Use a <link rel='stylesheet' href='style.css'> element inside the <head> tag.", "Easy", "Practical", "<link rel=\"stylesheet\" href=\"style.css\">", None, None, "Can you link multiple stylesheets?"),
        ("Document Structure", "Script Linking", "What is the difference between script defer and async?", "async runs scripts immediately when loaded. defer waits until HTML parsing finishes before running scripts in order.", "Intermediate", "Comparison", "<script src=\"app.js\" defer></script>", None, None, "Which one preserves script order?"),
        ("Document Structure", "Noscript", "What is the purpose of the <noscript> tag?", "It provides fallback content displayed only when JavaScript is disabled or unsupported by the browser.", "Intermediate", "Concept", "<noscript>Please enable JavaScript.</noscript>", None, None, "Is noscript used in React apps?"),
        ("Document Structure", "HTML Elements", "What is the difference between a tag and an element?", "A tag is the syntax like <p> or </p>. An element includes opening tag, content, and closing tag.", "Easy", "Concept", "<p>Hello world</p>", None, None, "Name two self-closing elements."),
        ("Document Structure", "Void Elements", "What are void elements in HTML?", "Void elements cannot contain child content and have no closing tags, such as <img>, <br>, <hr>, and <input>.", "Easy", "Concept", "<img src=\"logo.png\" alt=\"Logo\">", None, None, "Is <br/> required in HTML5?"),
        ("Document Structure", "Data Attributes", "What are data-* attributes used for?", "They store private custom data on HTML elements that JavaScript can easily read via dataset.", "Intermediate", "Concept", "<div data-user-id=\"42\" data-role=\"admin\"></div>", None, None, "How do you access this in JavaScript?"),
        ("Document Structure", "Comments", "How do you write comments in HTML?", "Use <!-- comment here -->. Comments are ignored by browsers during rendering.", "Easy", "Practical", "<!-- Navigation section starts -->", None, None, "Can comments be viewed in View Source?"),
        ("Document Structure", "Base Tag", "What does the <base> tag do in HTML?", "It specifies the base URL for all relative URLs in a document (links, images, scripts).", "Advanced", "Concept", "<base href=\"https://example.com/blog/\">", None, None, "Can you have more than one base tag?"),
        ("Document Structure", "DOCTYPE MCQ", "Which DOCTYPE declaration is correct for modern HTML5?", "Option B is correct. HTML5 uses a simple case-insensitive DOCTYPE declaration.", "Easy", "MCQ", "", {"A": "<!DOCTYPE html5>", "B": "<!DOCTYPE html>", "C": "<!DOCTYPE HTML PUBLIC>", "D": "<DOCTYPE html>"}, "B", "Why was the DOCTYPE simplified in HTML5?"),
        ("Document Structure", "Script Tag MCQ", "Where should scripts without defer be placed to avoid blocking rendering?", "Option C is correct. Placing scripts at the bottom of the body ensures HTML elements are parsed first.", "Easy", "MCQ", "", {"A": "Before <html>", "B": "Inside <head>", "C": "At the very bottom of <body>", "D": "Inside <title>"}, "C", "Why does defer remove the need for this?"),
        ("Document Structure", "Meta Description", "What is the purpose of the meta description tag?", "It provides a short summary of the page displayed in search engine snippets under the title.", "Intermediate", "Concept", "<meta name=\"description\" content=\"Free fresher interview drill tool.\">", None, None, "Does meta description directly affect Google rankings?"),
    ]

    for item in topics_data:
        top, subtop, q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = item
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # Now add complete subtopic batteries for HTML to reach 205 questions:
    # 2. Semantic Elements (25 Qs)
    semantics = [
        ("What is semantic HTML?", "Semantic HTML uses tags that explain their meaning to the browser and developer, like <header>, <article>, and <footer>.", "Easy", "Concept", "<header><h1>Site Title</h1></header>", "Why does semantic HTML help accessibility?"),
        ("What is the difference between <header> and <h1>?", "<header> is a container for introductory content or nav. <h1> is the main top-level heading text.", "Easy", "Comparison", "<header><h1>Title</h1><p>Subtitle</p></header>", "Can a page have multiple header tags?"),
        ("When should you use <nav>?", "Use <nav> only for major navigation blocks like site menus or breadcrumb trails, not for every group of links.", "Easy", "Concept", "<nav><a href=\"/\">Home</a><a href=\"/about\">About</a></nav>", "Should pagination links be inside a nav?"),
        ("What is the purpose of the <main> tag?", "The <main> tag represents the central content unique to the document, excluding headers, sidebars, and footers.", "Easy", "Concept", "<main><article>...</article></main>", "Can you have multiple main tags visible at once?"),
        ("What is the difference between <section> and <article>?", "<article> is self-contained and could be syndicated independently (like a blog post). <section> is a thematic grouping.", "Intermediate", "Comparison", "<article><h2>Post</h2><section>Comments</section></article>", "Can an article contain sections?"),
        ("When should you use <aside>?", "Use <aside> for content tangentially related to the main content, such as sidebars, callout boxes, or related links.", "Intermediate", "Concept", "<aside><h3>Related Articles</h3></aside>", "Is aside only placed on the right side?"),
        ("What does the <footer> tag represent?", "The <footer> represents a footer for its nearest section or page, typically containing copyright, author, or contact info.", "Easy", "Concept", "<footer><p>&copy; 2026 Developer Portal</p></footer>", "Can an article have its own footer?"),
        ("What is the difference between <div> and <section>?", "<div> has no semantic meaning and is used purely for styling. <section> represents a thematic content group with a heading.", "Easy", "Comparison", "", "When should you prefer div over section?"),
        ("What does the <figure> and <figcaption> pair do?", "<figure> wraps self-contained media (image, chart, code), and <figcaption> provides its caption or title.", "Intermediate", "Concept", "<figure><img src=\"graph.png\" alt=\"Chart\"><figcaption>Q3 Sales</figcaption></figure>", "Can figcaption be placed before the image?"),
        ("What is the <time> tag used for?", "The <time> tag represents dates, times, or durations in human-readable and machine-readable formats.", "Intermediate", "Concept", "<time datetime=\"2026-10-03\">October 3, 2026</time>", "Why is the datetime attribute useful?"),
        ("What does the <mark> tag do?", "The <mark> tag highlights text of current relevance, such as search term results in a document.", "Easy", "Concept", "<p>Search result: <mark>closure</mark> in JS.</p>", "How does mark differ from strong or em?"),
        ("What is the difference between <strong> and <b>?", "<strong> conveys strong importance or urgency semantically. <b> formats text bold visually without extra importance.", "Easy", "Comparison", "<strong>Warning:</strong> Action required.", "Do screen readers treat strong differently?"),
        ("What is the difference between <em> and <i>?", "<em> indicates verbal stress or semantic emphasis. <i> renders italic text for terms, foreign words, or thoughts without emphasis.", "Easy", "Comparison", "<p>I <em>love</em> clean code.</p>", "Does em change voice pitch in screen readers?"),
        ("What does the <address> tag represent?", "The <address> tag provides contact information for the author or owner of the document or article.", "Intermediate", "Concept", "<address>Email: contact@example.com</address>", "Should physical addresses of products use address?"),
        ("What does the <details> and <summary> pair do?", "It creates a native disclosure widget where clicking the <summary> toggles the visibility of the inner details without JS.", "Intermediate", "Practical", "<details><summary>FAQ 1</summary><p>Answer text</p></details>", "How do you make details open by default?"),
        ("What does the open attribute do on <details>?", "The open boolean attribute makes the <details> element expand and show its content by default when loaded.", "Easy", "Practical", "<details open><summary>Rules</summary><p>Content</p></details>", "Can you listen for toggle events on details?"),
        ("What is the purpose of <dialog> in HTML5?", "The <dialog> element represents a native modal dialog box or popup window with showModal() and close() methods.", "Advanced", "Concept", "<dialog id=\"modal\"><p>Alert</p></dialog>", "How does showModal() handle the backdrop?"),
        ("What does the <progress> element do?", "The <progress> element displays a progress bar representing task completion (e.g., upload or download progress).", "Intermediate", "Concept", "<progress value=\"70\" max=\"100\">70%</progress>", "How does progress differ from meter?"),
        ("What does the <meter> element do?", "The <meter> element represents a scalar value within a known range, such as disk usage or battery percentage.", "Intermediate", "Comparison", "<meter value=\"0.6\" min=\"0\" max=\"1\">60%</meter>", "Can meter show low, high, and optimum thresholds?"),
        ("Which semantic tag should wrap an independent blog post on a portal?", "Option A is correct. <article> represents independent, distributable content.", "Easy", "MCQ", "", {"A": "<article>", "B": "<section>", "C": "<aside>", "D": "<div>"}, "A", "Can an article have its own header and footer?"),
        ("What tag should be used for a site-wide navigation menu?", "Option B is correct. <nav> indicates primary navigation links.", "Easy", "MCQ", "", {"A": "<menu>", "B": "<nav>", "C": "<dir>", "D": "<links>"}, "B", "Is nav used for utility links in footers?"),
        ("Why should you avoid using <div> for everything (div soup)?", "Div soup harms accessibility for screen reader users, hurts search engine indexing, and makes HTML hard to read.", "Intermediate", "Scenario", "", "What tool checks page semantic outline?"),
        ("Can you nest an <article> inside another <article>?", "Yes. A blog post <article> can contain nested <article> elements for user comments.", "Advanced", "Concept", "<article><h1>Post</h1><article><h3>Comment</h3></article></article>", "Is this standard W3C practice?"),
        ("What semantic tag is best for quote attribution?", "The <cite> tag is used to reference the title of a creative work or quote source.", "Intermediate", "Concept", "<p><cite>Clean Code</cite> by Robert Martin.</p>", "Can cite enclose the author's name in HTML5?"),
        ("What is the difference between <blockquote> and <q>?", "<blockquote> is a block-level container for long quotations. <q> is an inline quote that browsers surround with quotation marks.", "Easy", "Comparison", "<blockquote><p>Quote text</p></blockquote>", "What attribute references the URL source in blockquote?")
    ]
    for item in semantics:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Semantic HTML", "Elements",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 3. Text Formatting & Structure (25 Qs)
    text_formatting = [
        ("What is the difference between block-level and inline elements?", "Block elements start on a new line and take full container width (like <div>, <p>). Inline elements take only content width (like <span>, <a>).", "Easy", "Comparison", "<div>Block</div><span>Inline</span>", "Can an inline element contain a block element in HTML5?"),
        ("What does the <span> tag do?", "The <span> tag is an inline container with no semantic meaning, used to group text for styling or scripting.", "Easy", "Concept", "<p>Hello <span class=\"highlight\">world</span></p>", "How does span differ from div?"),
        ("What is the heading hierarchy in HTML (h1 to h6)?", "<h1> is the highest rank heading and <h6> is the lowest. A page should have one main <h1> followed by nested subheadings.", "Easy", "Concept", "<h1>Main Title</h1><h2>Subheading</h2>", "Can you skip heading levels (like h1 to h3)?"),
        ("What is the purpose of the <p> tag?", "The <p> element defines a paragraph of text. Browsers automatically add vertical margin before and after it.", "Easy", "Concept", "<p>This is a paragraph.</p>", "Can a paragraph contain a div?"),
        ("What does the <br> tag do and when should you avoid it?", "<br> inserts a line break. You should avoid using multiple <br> tags for spacing; use CSS margins instead.", "Easy", "Practical", "<p>Line 1<br>Line 2</p>", "Is br an inline or block element?"),
        ("What does the <hr> tag represent in HTML5?", "<hr> represents a thematic break or transition between topics within a section, displayed as a horizontal divider.", "Easy", "Concept", "<p>Section A</p><hr><p>Section B</p>", "How do you style the color of an hr in CSS?"),
        ("What does the <pre> tag do?", "The <pre> tag preserves preformatted text, retaining all spaces, tabs, and line breaks exactly as written in the HTML.", "Easy", "Concept", "<pre>Line 1\n  Line 2 (indented)</pre>", "Which default font family is used for pre?"),
        ("What is the difference between <code> and <pre>?", "<code> is an inline tag used for computer code snippets. <pre> is a block tag that preserves formatting. They are often nested together.", "Easy", "Comparison", "<pre><code>const x = 10;</code></pre>", "Why nest code inside pre?"),
        ("What does the <kbd> element represent?", "The <kbd> tag represents user keyboard input, voice input, or key combinations like <kbd>Ctrl</kbd> + <kbd>C</kbd>.", "Intermediate", "Concept", "<p>Press <kbd>Ctrl</kbd> + <kbd>S</kbd> to save.</p>", "How is kbd typically styled in CSS?"),
        ("What does the <samp> element represent?", "The <samp> tag represents sample output from a computer program or system.", "Intermediate", "Concept", "<samp>Error 404: Not Found</samp>", "Is samp inline or block?"),
        ("What does the <var> element represent?", "The <var> tag represents a variable in a mathematical expression or programming context, usually displayed in italics.", "Intermediate", "Concept", "<p>Let <var>x</var> = 5.</p>", "Can var be used in math formulas?"),
        ("What does the <sub> and <sup> tags do?", "<sub> creates subscript text (lower than baseline, e.g. H<sub>2</sub>O). <sup> creates superscript text (higher, e.g. x<sup>2</sup>).", "Easy", "Practical", "<p>H<sub>2</sub>O and 10<sup>3</sup></p>", "Are sub and sup inline elements?"),
        ("What does the <small> tag represent in HTML5?", "The <small> tag represents side comments and small print, like copyright text or legal disclaimers.", "Easy", "Concept", "<small>&copy; 2026 All rights reserved.</small>", "Does small only change font size?"),
        ("What does the <del> and <ins> tags represent?", "<del> represents deleted text (rendered with strikethrough), and <ins> represents inserted text (rendered underlined).", "Intermediate", "Practical", "<p>Price: <del>$50</del> <ins>$35</ins></p>", "Can del and ins accept a datetime attribute?"),
        ("What does the <s> tag represent?", "The <s> tag represents text that is no longer accurate or relevant, rendered with a strike-through.", "Easy", "Concept", "<p><s>Old price $100</s></p>", "How does s differ from del?"),
        ("What does the <abbr> tag do and what is the 'title' attribute for?", "<abbr> marks an abbreviation or acronym. The title attribute provides its full expansion on hover.", "Intermediate", "Concept", "<abbr title=\"HyperText Markup Language\">HTML</abbr>", "Does screen reader read title attribute?"),
        ("What does the <bdo> tag do in HTML?", "<bdo> (Bi-Directional Override) overrides current text direction (e.g. dir='rtl' for right-to-left).", "Advanced", "Concept", "<bdo dir=\"rtl\">This text displays backwards.</bdo>", "When is bdo useful?"),
        ("What does the <wbr> tag do?", "The <wbr> (Word Break Opportunity) tag specifies where the browser may optionally break a very long word or URL if needed.", "Advanced", "Practical", "very<wbr>long<wbr>identifier", "Does wbr show any visual mark when not broken?"),
        ("Which element is best for representing inline program code?", "Option B is correct. <code> formats inline code snippets semantically.", "Easy", "MCQ", "", {"A": "<samp>", "B": "<code>", "C": "<pre>", "D": "<var>"}, "B", "What font family does code use by default?"),
        ("Which tag preserves spaces and line breaks exactly as typed?", "Option C is correct. <pre> preserves raw whitespace and line feeds.", "Easy", "MCQ", "", {"A": "<p>", "B": "<span>", "C": "<pre>", "D": "<code>"}, "C", "Can you use CSS white-space on normal paragraphs?"),
        ("What is the HTML entity for a non-breaking space?", "&nbsp; is the HTML entity for a space that prevents an automatic line break at its position.", "Easy", "Concept", "100&nbsp;km/h", "What is the entity for the copyright symbol?"),
        ("What are the HTML entities for '<' and '>'?", "&lt; represents less-than (<) and &gt; represents greater-than (>), used to display literal angle brackets without breaking HTML.", "Easy", "Practical", "&lt;div&gt; displays as <div>", "What is the entity for ampersand (&)?"),
        ("What happens if you type a raw '&' inside HTML text?", "Browsers may treat it as the start of an entity. You should encode it as &amp; to avoid HTML parsing bugs.", "Intermediate", "Scenario", "<p>Fish &amp; Chips</p>", "Can raw & cause validation errors?"),
        ("What is the purpose of the <ruby> tag in HTML?", "<ruby> is used for presenting pronunciation annotations (ruby text via <rt>) above East Asian characters.", "Advanced", "Concept", "<ruby>漢 <rt>kan</rt></ruby>", "What does the rp tag do inside ruby?"),
        ("What is the maximum number of h1 tags recommended per web page?", "One main <h1> per page is the accessibility and SEO best practice, representing the document's primary subject.", "Easy", "Concept", "<h1>Main Product Name</h1>", "Can sections technically have their own h1 in HTML5?")
    ]
    for item in text_formatting:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Text Formatting", "Typography",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 4. Links & Navigation (20 Qs)
    links_data = [
        ("What tag creates hyperlinks in HTML?", "The <a> (anchor) tag creates hyperlinks using the 'href' attribute to define destination URL.", "Easy", "Concept", "<a href=\"https://example.com\">Visit Site</a>", "What happens if an anchor has no href attribute?"),
        ("What does target='_blank' do and what security attribute must accompany it?", "target='_blank' opens the link in a new browser tab. Always add rel='noopener noreferrer' to prevent tab-nabbing vulnerabilities.", "Intermediate", "Practical", "<a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">Link</a>", "What does window.opener allow if not blocked?"),
        ("How do you create an internal anchor link that scrolls to a section on the same page?", "Set href='#section-id' pointing to the id attribute of the destination element on the page.", "Easy", "Practical", "<a href=\"#pricing\">Go to Pricing</a>\n...\n<section id=\"pricing\">Pricing</section>", "Can you link to an ID on another webpage?"),
        ("How do you create a clickable email link in HTML?", "Use href='mailto:email@example.com'. Clicking it opens the user's default email client.", "Easy", "Practical", "<a href=\"mailto:support@example.com\">Email Us</a>", "Can you prefill subject and body in mailto?"),
        ("How do you create a clickable telephone link in HTML?", "Use href='tel:+1234567890'. On mobile devices, clicking it directly initiates a phone call.", "Easy", "Practical", "<a href=\"tel:+15551234567\">Call Us</a>", "Does tel work on desktop browsers?"),
        ("What does the 'download' attribute do on an anchor tag?", "The 'download' attribute instructs the browser to download the linked resource instead of navigating to it.", "Intermediate", "Practical", "<a href=\"/docs/resume.pdf\" download=\"Candidate_Resume.pdf\">Download Resume</a>", "Can download rename the file?"),
        ("What does rel='nofollow' mean in HTML?", "rel='nofollow' tells search engine crawlers not to follow the link or transfer ranking credit (PageRank) to the target page.", "Intermediate", "Concept", "<a href=\"https://ads.com\" rel=\"nofollow\">Sponsored</a>", "When is nofollow required by Google?"),
        ("What is the difference between relative and absolute URLs in href?", "Absolute URLs include the full protocol and domain (https://example.com/page). Relative URLs are relative to the current page path (/page).", "Easy", "Comparison", "<a href=\"/about\">About</a> vs <a href=\"https://site.com/about\">About</a>", "When should you use relative URLs?"),
        ("What happens if you click <a href='#'>?", "It navigates to the top of the current page and adds '#' to the URL unless preventDefault() is called in JavaScript.", "Easy", "Scenario", "<a href=\"#\">Top of Page</a>", "What should you use instead for JS buttons?"),
        ("Why should you use <button> instead of <a href='javascript:void(0)'> for actions?", "Buttons are semantically designed for triggering actions, support keyboard Enter/Space by default, and are accessible to screen readers.", "Intermediate", "Scenario", "<button type=\"button\" onclick=\"doAction()\">Action</button>", "Does an anchor trigger with spacebar?"),
        ("What does target='_self' do?", "target='_self' is the default behavior; it opens the linked document in the same frame/tab where it was clicked.", "Easy", "Concept", "<a href=\"/dashboard\" target=\"_self\">Dashboard</a>", "What are the other target options?"),
        ("What does target='_parent' and target='_top' do?", "_parent opens link in parent frame. _top opens link in full window, breaking out of all nested iframes.", "Advanced", "Concept", "<a href=\"/home\" target=\"_top\">Exit iframe</a>", "When is target='_top' critical?"),
        ("How do you link to an SMS message in HTML?", "Use href='sms:+1234567890?body=Hello'. On mobile phones, this opens the SMS text message app.", "Intermediate", "Practical", "<a href=\"sms:+1234567890\">Send SMS</a>", "Is body parameter supported on all OS?"),
        ("Which attribute must be added with target='_blank' for security?", "Option B is correct. rel='noopener' prevents the opened page from accessing window.opener.", "Intermediate", "MCQ", "", {"A": "rel='canonical'", "B": "rel='noopener noreferrer'", "C": "rel='author'", "D": "rel='dns-prefetch'"}, "B", "What security attack does this prevent?"),
        ("What does rel='author' indicate?", "It indicates that the linked document provides information about the author of the current page.", "Intermediate", "Concept", "<a href=\"/author/john\" rel=\"author\">John Doe</a>", "Can search engines use rel='author'?"),
        ("What does rel='prev' and rel='next' do?", "They specify relationships between pages in a paginated sequence (e.g. Page 1, Page 2).", "Intermediate", "Concept", "<link rel=\"next\" href=\"/page/2\">", "Are they placed in head or body?"),
        ("Can an anchor tag wrap an entire card container in HTML5?", "Yes. HTML5 permits <a> tags to wrap block-level elements like <div>, <img>, and <h2> to make an entire card clickable.", "Intermediate", "Practical", "<a href=\"/product/1\" class=\"card\"><img src=\"p.jpg\"><h3>Title</h3></a>", "Can you nest another <a> inside that card?"),
        ("What happens if you nest an <a> tag inside another <a> tag?", "Invalid HTML. Browsers will break the DOM tree and auto-close the first link, causing severe layout and click bugs.", "Advanced", "Debugging", "<!-- INVALID -->\n<a href=\"#1\"><a href=\"#2\">nested</a></a>", "How do you achieve clickable nested tags?"),
        ("What does href='javascript:void(0)' mean?", "It runs a JavaScript expression that evaluates to undefined, preventing page reload or scrolling when clicked.", "Intermediate", "Concept", "<a href=\"javascript:void(0)\">Click</a>", "Why is a button element better?"),
        ("What is the role attribute when using an anchor as a button?", "If an anchor must act as a button, add role='button' and handle Space/Enter keyboard events for accessibility.", "Advanced", "Practical", "<a href=\"#\" role=\"button\" tabindex=\"0\">Submit</a>", "Why is standard button preferred?")
    ]
    for item in links_data:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Links & Navigation", "Hyperlinks",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 5. Lists & Tables (25 Qs)
    lists_tables = [
        ("What is the difference between <ul> and <ol> in HTML?", "<ul> creates an unordered bulleted list. <ol> creates an ordered numbered list.", "Easy", "Comparison", "<ul><li>A</li></ul>\n<ol><li>1</li></ol>", "What element must direct children of ul/ol be?"),
        ("Can elements other than <li> be direct children of <ul> or <ol>?", "No. The only valid direct child elements of <ul> and <ol> are <li> elements (and <script>/<template>).", "Easy", "Concept", "<!-- Valid -->\n<ul><li>Item</li></ul>", "Can li contain other lists?"),
        ("How do you create a nested list in HTML?", "Place the inner <ul> or <ol> inside an <li> element of the parent list.", "Easy", "Practical", "<ul>\n  <li>Frontend\n    <ul><li>HTML</li><li>CSS</li></ul>\n  </li>\n</ul>", "Can you put the inner ul directly under outer ul?"),
        ("What is a Description List (<dl>) in HTML?", "A description list (<dl>) encloses terms (<dt>) and their descriptions (<dd>), useful for glossaries, metadata, or key-value pairs.", "Intermediate", "Concept", "<dl>\n  <dt>CSS</dt>\n  <dd>Cascading Style Sheets</dd>\n</dl>", "Can a dt have multiple dd elements?"),
        ("What is the difference between <dt> and <dd>?", "<dt> defines the description term. <dd> defines the description definition or details for that term.", "Easy", "Comparison", "<dt>HTTP</dt><dd>Hypertext Transfer Protocol</dd>", "Can you group dt/dd inside div inside dl?"),
        ("What does the 'start' attribute do on an <ol> tag?", "The start attribute specifies the starting number of the ordered list (e.g. start='5' starts counting from 5).", "Easy", "Practical", "<ol start=\"5\">\n  <li>Fifth</li>\n  <li>Sixth</li>\n</ol>", "Can start be a negative number?"),
        ("What does the 'reversed' attribute do on an <ol> tag?", "The 'reversed' boolean attribute numbers list items in descending reverse order (e.g. 3, 2, 1).", "Intermediate", "Practical", "<ol reversed>\n  <li>Third</li>\n  <li>Second</li>\n  <li>First</li>\n</ol>", "Does it reverse DOM order or only numbering?"),
        ("What does the 'type' attribute on <ol> do?", "The type attribute changes numbering style: '1' (numbers), 'a' (lowercase letters), 'A' (uppercase), 'i' (lowercase roman), 'I' (uppercase roman).", "Easy", "Practical", "<ol type=\"A\"><li>Item A</li></ol>", "Can CSS list-style-type do the same?"),
        ("What are the basic elements needed to create an HTML table?", "<table> creates the table, <tr> creates a table row, <th> creates a header cell, and <td> creates a data cell.", "Easy", "Concept", "<table>\n  <tr><th>Name</th></tr>\n  <tr><td>John</td></tr>\n</table>", "How does th differ visually from td?"),
        ("What is the difference between <th> and <td>?", "<th> represents a header cell (bold and centered by default, semantic header). <td> represents regular table data.", "Easy", "Comparison", "<tr><th>Score</th><td>95</td></tr>", "What attribute connects th to td?"),
        ("What is the purpose of <thead>, <tbody>, and <tfoot> in HTML tables?", "They semantically divide table rows into header, body data, and summary/footer sections, allowing independent styling and scrolling.", "Intermediate", "Concept", "<table>\n  <thead><tr><th>Item</th></tr></thead>\n  <tbody><tr><td>Apple</td></tr></tbody>\n</table>", "Does tfoot have to appear after tbody?"),
        ("What does the 'colspan' attribute do in an HTML table?", "colspan makes a table cell span horizontally across multiple columns.", "Easy", "Practical", "<td colspan=\"3\">Spans 3 columns</td>", "What happens if colspan exceeds table width?"),
        ("What does the 'rowspan' attribute do in an HTML table?", "rowspan makes a table cell span vertically across multiple rows.", "Easy", "Practical", "<td rowspan=\"2\">Spans 2 rows</td>", "How does rowspan affect subsequent tr tags?"),
        ("What is the purpose of the <caption> element in an HTML table?", "The <caption> element provides an accessible title or description for the table, placed immediately after opening <table>.", "Intermediate", "Concept", "<table>\n  <caption>Monthly Developer Expenses</caption>\n  <tr>...</tr>\n</table>", "Can caption be positioned below the table in CSS?"),
        ("What is the purpose of <colgroup> and <col> in tables?", "<colgroup> groups one or more columns together to apply styles (like background-color or width) to entire columns at once.", "Advanced", "Practical", "<colgroup>\n  <col style=\"background-color:#f0f0f0\">\n  <col style=\"width:200px\">\n</colgroup>", "Which CSS properties work on col elements?"),
        ("What does the 'scope' attribute do on a <th> element?", "The scope attribute specifies whether the header applies to a column (scope='col'), row (scope='row'), or groups for screen readers.", "Intermediate", "Accessibility", "<th scope=\"col\">Username</th>\n<th scope=\"row\">User 1</th>", "Why is scope essential for accessibility?"),
        ("Why should tables NOT be used for overall page layout?", "Tables for layout harm responsiveness, destroy accessibility for screen reader navigation, and bloat HTML code. Use CSS Flexbox/Grid instead.", "Intermediate", "Scenario", "", "When is a table appropriate to use?"),
        ("Which attribute merges two table cells horizontally?", "Option A is correct. colspan merges cells across columns.", "Easy", "MCQ", "", {"A": "colspan", "B": "rowspan", "C": "span", "D": "colmerge"}, "A", "What attribute merges vertically?"),
        ("Where must <caption> be placed in a <table>?", "Option B is correct. <caption> must be the first child tag immediately following <table>.", "Intermediate", "MCQ", "", {"A": "Inside <thead>", "B": "Immediately after <table>", "C": "Inside the first <tr>", "D": "At the end before </table>"}, "B", "Can a table have multiple captions?"),
        ("What does the 'headers' attribute do on a <td> element?", "It links a complex data cell to the id values of one or more header <th> cells for multi-level accessibility.", "Advanced", "Accessibility", "<td headers=\"q1 sales\">$500</td>", "When is headers required instead of scope?"),
        ("What happens if a table has empty cells?", "Empty cells (<td class='empty'></td>) can break layout or screen reading. Best practice is to provide '-' or meaningful text or CSS empty-cells: show.", "Intermediate", "Practical", "<td>N/A</td>", "What does CSS empty-cells property do?"),
        ("How do you make a table responsive on mobile devices?", "Wrap the table in a container with overflow-x: auto, or use CSS media queries to convert table rows into block cards.", "Intermediate", "Practical", "<div style=\"overflow-x:auto;\">\n  <table>...</table>\n</div>", "What is the card table pattern?"),
        ("What is the border-collapse CSS property on tables?", "border-collapse: collapse merges adjacent cell borders into a single border instead of separated double borders.", "Easy", "Practical", "table { border-collapse: collapse; }", "What is the default value of border-collapse?"),
        ("Can a <tfoot> tag contain multiple rows?", "Yes. <tfoot> can contain multiple <tr> elements for total, average, and summary calculations.", "Intermediate", "Concept", "<tfoot>\n  <tr><td>Subtotal</td><td>$100</td></tr>\n  <tr><td>Tax</td><td>$10</td></tr>\n</tfoot>", "Does tfoot print at bottom of every page?"),
        ("What is the difference between a numbered list and an unordered list?", "Ordered list (<ol>) implies sequence and progression (steps, rankings). Unordered list (<ul>) implies order does not matter.", "Easy", "Comparison", "", "Should recipe steps use ol or ul?")
    ]
    for item in lists_tables:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Lists & Tables", "Structure",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 6. Forms & User Input (30 Qs)
    forms_data = [
        ("What is the purpose of the <form> element in HTML?", "The <form> element collects user input and defines how and where to submit that data to a server.", "Easy", "Concept", "<form action=\"/api/login\" method=\"POST\"><input type=\"text\"><button>Submit</button></form>", "What happens if a form has no action attribute?"),
        ("What is the difference between GET and POST form methods?", "GET appends form data to the URL as query parameters (visible, cached, bookmarkable). POST sends data inside HTTP request body (private, no length limits).", "Easy", "Comparison", "<form method=\"GET\"> vs <form method=\"POST\">", "When should you NEVER use GET?"),
        ("Why should password or sensitive data never be submitted with GET?", "GET parameters are stored in browser history, server access logs, and shown in the URL bar, exposing credentials to attackers.", "Intermediate", "Scenario", "", "Can GET requests be cached by proxies?"),
        ("What does the 'action' attribute specify on a <form>?", "The action attribute specifies the destination URL endpoint where the form data will be sent upon submission.", "Easy", "Concept", "<form action=\"/submit-form\">", "What is the default action if omitted?"),
        ("What does the 'name' attribute do on an <input> element?", "The name attribute defines the key name for the input field. Only inputs with a name attribute are submitted with the form.", "Easy", "Concept", "<input type=\"text\" name=\"username\">", "What happens if name attribute is missing?"),
        ("What is the purpose of the <label> element and the 'for' attribute?", "The <label> provides accessible text for an input. Its 'for' attribute matches the input's 'id', focusing the input when the label is clicked.", "Easy", "Accessibility", "<label for=\"email-in\">Email:</label>\n<input id=\"email-in\" type=\"email\" name=\"email\">", "Can a label wrap an input directly?"),
        ("What is the difference between input type='text' and type='email'?", "type='email' triggers mobile email keyboards (with @) and performs native browser email format validation before submit.", "Easy", "Comparison", "<input type=\"email\" name=\"user_email\">", "Can email input accept multiple emails?"),
        ("What does input type='password' do?", "It masks entered characters with dots or asterisks so bystanders cannot read sensitive passwords on screen.", "Easy", "Concept", "<input type=\"password\" name=\"pwd\">", "Is the password encrypted in memory?"),
        ("What is the difference between radio buttons and checkboxes?", "Radio buttons (type='radio') allow selecting only one option from a named group. Checkboxes (type='checkbox') allow multiple independent selections.", "Easy", "Comparison", "<input type=\"radio\" name=\"gender\" value=\"m\">\n<input type=\"checkbox\" name=\"subscribe\">", "How do you group radio buttons together?"),
        ("How do you group radio buttons so only one can be selected?", "Give all radio buttons in the group the exact same 'name' attribute value.", "Easy", "Practical", "<input type=\"radio\" name=\"size\" value=\"s\">\n<input type=\"radio\" name=\"size\" value=\"m\">", "What happens if names are different?"),
        ("What does the 'required' attribute do on an input?", "The 'required' boolean attribute prevents form submission if the field is empty, displaying a native browser error tooltip.", "Easy", "Practical", "<input type=\"text\" name=\"uname\" required>", "Can CSS style required fields?"),
        ("What does the 'placeholder' attribute do on an input?", "The placeholder attribute displays temporary hint text inside the field when empty. It disappears when the user types.", "Easy", "Concept", "<input type=\"text\" placeholder=\"e.g. John Doe\">", "Should placeholder replace a label?"),
        ("Why should placeholder NOT be used as a replacement for <label>?", "Placeholders disappear on typing, have low contrast, and are not reliably announced by all screen readers, hurting usability.", "Intermediate", "Accessibility", "", "What is the floating label pattern?"),
        ("What is the difference between 'disabled' and 'readonly' attributes?", "disabled inputs are grayed out, unclickable, and NOT submitted with form data. readonly inputs cannot be edited but CAN be focused, copied, and ARE submitted.", "Intermediate", "Comparison", "<input readonly value=\"123\">\n<input disabled value=\"123\">", "Does JavaScript change readonly values?"),
        ("What does the 'pattern' attribute do on an input?", "The pattern attribute defines a regular expression that the input's value must match before the form can submit.", "Intermediate", "Practical", "<input type=\"text\" pattern=\"[0-9]{5}\" title=\"5-digit ZIP\">", "What does title attribute do with pattern?"),
        ("What does the 'maxlength' and 'minlength' attributes do?", "maxlength restricts the maximum number of characters typed. minlength enforces a minimum character count on submit.", "Easy", "Practical", "<input type=\"text\" minlength=\"3\" maxlength=\"20\">", "Does maxlength prevent paste?"),
        ("What does the 'min', 'max', and 'step' attributes do on number inputs?", "min and max define numeric limits. step defines the valid step increments (e.g. step='0.01' for currency).", "Easy", "Practical", "<input type=\"number\" min=\"1\" max=\"100\" step=\"1\">", "What is the default step value?"),
        ("What are the three button types in HTML (<button type='...')?", "type='submit' (submits the form; default), type='reset' (resets fields to defaults), and type='button' (does nothing automatically, used for JS).", "Intermediate", "Concept", "<button type=\"button\" onclick=\"save()\">Save</button>", "Why is type='button' critical inside forms?"),
        ("What does the <textarea> element do and how does it differ from <input>?", "<textarea> supports multi-line text input with line breaks. Unlike <input>, its default value goes between tags (<textarea>default</textarea>).", "Easy", "Comparison", "<textarea rows=\"4\" cols=\"50\" name=\"bio\"></textarea>", "What CSS property prevents user resizing?"),
        ("What is the <select> and <option> element used for?", "<select> creates a dropdown selection menu, and <option> defines each choice inside the dropdown.", "Easy", "Concept", "<select name=\"country\">\n  <option value=\"in\">India</option>\n  <option value=\"us\">USA</option>\n</select>", "How do you select an option by default?"),
        ("What does the 'selected' attribute do on an <option> tag?", "The 'selected' boolean attribute preselects that option when the dropdown renders.", "Easy", "Practical", "<option value=\"ny\" selected>New York</option>", "How do you allow multiple selections?"),
        ("What does the <optgroup> element do inside a <select>?", "The <optgroup> element groups related options under a non-selectable bold label header.", "Intermediate", "Practical", "<select>\n  <optgroup label=\"Fruits\"><option>Apple</option></optgroup>\n</select>", "Can optgroup be nested?"),
        ("What does the <datalist> tag do in HTML5?", "<datalist> provides an auto-complete dropdown list of suggested options for an <input> while still allowing custom user input.", "Intermediate", "Practical", "<input list=\"browsers\" name=\"browser\">\n<datalist id=\"browsers\">\n  <option value=\"Chrome\">\n  <option value=\"Firefox\">\n</datalist>", "How is datalist connected to the input?"),
        ("What is the purpose of <fieldset> and <legend> in forms?", "<fieldset> visually and semantically groups related form controls together. <legend> provides a caption title for the group.", "Intermediate", "Accessibility", "<fieldset>\n  <legend>Personal Information</legend>\n  <input type=\"text\" name=\"fname\">\n</fieldset>", "How do screen readers announce fieldset?"),
        ("What does input type='hidden' do?", "It stores form data that is not visible to the user but is submitted with the form (e.g. CSRF tokens or user IDs).", "Intermediate", "Concept", "<input type=\"hidden\" name=\"csrf_token\" value=\"xyz123\">", "Can users inspect hidden input values?"),
        ("What does the 'autofocus' attribute do?", "The autofocus boolean attribute automatically focuses that form field when the page finishes loading.", "Easy", "Practical", "<input type=\"text\" name=\"search\" autofocus>", "Should multiple inputs have autofocus?"),
        ("What does the 'autocomplete' attribute do on forms and inputs?", "It controls whether the browser can suggest saved user values (e.g. autocomplete='on', 'off', 'email', 'current-password').", "Intermediate", "Practical", "<input type=\"password\" autocomplete=\"new-password\">", "Why is autocomplete='new-password' useful?"),
        ("What does enctype='multipart/form-data' do on a <form>?", "It is required when the form includes file uploads (<input type='file'>) to transmit binary file data to the server.", "Intermediate", "Practical", "<form action=\"/upload\" method=\"POST\" enctype=\"multipart/form-data\">", "What is the default enctype if omitted?"),
        ("What does the 'novalidate' attribute do on a <form>?", "The novalidate boolean attribute turns off native browser HTML5 validation, allowing custom JavaScript validation to handle errors.", "Intermediate", "Practical", "<form novalidate action=\"/submit\">", "Why do libraries like Formik use novalidate?"),
        ("Which input type is best for entering telephone numbers?", "Option B is correct. type='tel' brings up phone keypads on mobile devices.", "Easy", "MCQ", "", {"A": "<input type='phone'>", "B": "<input type='tel'>", "C": "<input type='number'>", "D": "<input type='call'>"}, "B", "Does type='tel' validate numbers by default?")
    ]
    for item in forms_data:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Forms & Input", "User Input",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 7. Media, Graphics & HTML5 APIs (35 Qs)
    media_data = [
        ("What does the <img> tag do and why is the 'alt' attribute mandatory?", "The <img> tag embeds an image. 'alt' provides alternative text for screen readers and displays when the image fails to load.", "Easy", "Accessibility", "<img src=\"profile.jpg\" alt=\"Headshot of John Doe\">", "What should alt be for purely decorative images?"),
        ("What is an empty alt attribute (alt='') used for?", "alt='' tells screen readers to ignore purely decorative images (like icons or borders) without announcing broken image names.", "Intermediate", "Accessibility", "<img src=\"divider.png\" alt=\"\">", "Should decorative images be in CSS instead?"),
        ("What does loading='lazy' do on <img> tags?", "loading='lazy' instructs the browser to defer loading images until they are near the user's viewport, saving bandwidth.", "Intermediate", "Practical", "<img src=\"hero.jpg\" alt=\"Hero\" loading=\"lazy\">", "Should above-the-fold hero images use loading='lazy'?"),
        ("What is the purpose of the <picture> element in HTML5?", "<picture> enables art direction and responsive images by serving different image files based on media queries or format support.", "Intermediate", "Practical", "<picture>\n  <source srcset=\"img.webp\" type=\"image/webp\">\n  <img src=\"img.jpg\" alt=\"Fallback\">\n</picture>", "What is art direction in responsive images?"),
        ("What do 'srcset' and 'sizes' attributes do on an <img> tag?", "srcset provides multiple image resolutions for different screen pixel densities. sizes specifies display width at different media queries.", "Advanced", "Practical", "<img srcset=\"small.jpg 400w, large.jpg 800w\" sizes=\"(max-width: 600px) 400px, 800px\" src=\"large.jpg\" alt=\"Responsive\">", "How does the browser pick the image?"),
        ("How do you embed an audio file in HTML5?", "Use the <audio> tag with the 'controls' attribute and nested <source> tags for different format support (MP3, OGG).", "Easy", "Practical", "<audio controls>\n  <source src=\"audio.mp3\" type=\"audio/mpeg\">\n  Your browser does not support audio.\n</audio>", "What happens if controls attribute is omitted?"),
        ("How do you embed a video file in HTML5?", "Use the <video> tag with 'controls' and nested <source> elements (MP4, WebM).", "Easy", "Practical", "<video width=\"640\" height=\"360\" controls>\n  <source src=\"movie.mp4\" type=\"video/mp4\">\n</video>", "Why should you always specify width and height?"),
        ("What does the 'poster' attribute do on a <video> element?", "The poster attribute specifies an image URL displayed as a preview thumbnail before the video starts playing.", "Easy", "Practical", "<video poster=\"thumb.jpg\" controls></video>", "What displays if no poster is set?"),
        ("What does the 'autoplay' attribute do on video and why does it need 'muted'?", "autoplay plays video automatically on load. Modern browsers block unmuted autoplay to prevent annoying audio popups; 'muted' is required.", "Intermediate", "Scenario", "<video autoplay muted loop playsinline></video>", "What does playsinline do on iOS?"),
        ("What does the <track> element do inside audio and video tags?", "The <track> tag specifies timed text tracks like subtitles, captions, or descriptions using WebVTT (.vtt) files.", "Intermediate", "Accessibility", "<video controls>\n  <track src=\"subs_en.vtt\" kind=\"subtitles\" srclang=\"en\" label=\"English\">\n</video>", "What does kind='captions' mean?"),
        ("What is an <iframe> and what is its primary use?", "An <iframe> (inline frame) embeds another separate HTML document inside the current webpage (e.g. YouTube video or map).", "Easy", "Concept", "<iframe src=\"https://example.com\" width=\"500\" height=\"300\"></iframe>", "What security risks do iframes carry?"),
        ("What does the 'sandbox' attribute do on an <iframe>?", "The sandbox attribute restricts iframe capabilities (blocks scripts, popups, and form submissions) unless explicitly allowed.", "Advanced", "Security", "<iframe src=\"widget.html\" sandbox=\"allow-scripts allow-same-origin\"></iframe>", "What does sandbox='' with no values do?"),
        ("What does the 'srcdoc' attribute do on an <iframe>?", "srcdoc specifies raw HTML content to display directly inside the iframe instead of fetching from an external URL.", "Advanced", "Practical", "<iframe srcdoc=\"<p>Inline iframe content</p>\"></iframe>", "Which takes priority: src or srcdoc?"),
        ("What is the difference between <canvas> and <svg>?", "<canvas> is raster-based and drawn pixel-by-pixel with JavaScript. <svg> is vector-based XML, scalable without quality loss, and part of the DOM.", "Intermediate", "Comparison", "<canvas id=\"myCanvas\"></canvas>\n<svg width=\"100\" height=\"100\"><circle r=\"50\"/></svg>", "Which is better for high-speed game rendering?"),
        ("Can you style SVG elements with CSS?", "Yes. SVG elements like <circle>, <path>, and <rect> are part of the DOM and can be styled with fill, stroke, and transitions in CSS.", "Easy", "Concept", "svg path { fill: #38bdf8; }", "Can canvas elements be styled with CSS?"),
        ("What is the difference between client-side LocalStorage and SessionStorage?", "LocalStorage persists data indefinitely until explicitly cleared. SessionStorage is cleared when the browser tab or session is closed.", "Intermediate", "Comparison", "localStorage.setItem('k', 'v');\nsessionStorage.setItem('k', 'v');", "What is the storage capacity limit?"),
        ("What is the Geolocation API in HTML5?", "It allows users to share their geographic coordinates (latitude and longitude) with the web application via navigator.geolocation.", "Intermediate", "Concept", "navigator.geolocation.getCurrentPosition(success, error);", "Does it require user permission?"),
        ("What is the HTML5 Drag and Drop API?", "It enables dragging elements by adding the draggable='true' attribute and listening for dragstart, dragover, and drop events.", "Advanced", "Concept", "<div draggable=\"true\" ondragstart=\"drag(event)\">Drag me</div>", "Why is preventDefault needed in dragover?"),
        ("What are Web Workers in HTML5?", "Web Workers allow background JavaScript execution on a separate thread without blocking the main browser UI thread.", "Advanced", "Concept", "const worker = new Worker('worker.js');", "Can web workers access the DOM directly?"),
        ("What does the <template> element do in HTML?", "The <template> tag holds client-side content that is not rendered on page load but can be cloned and inserted into the DOM by JavaScript.", "Intermediate", "Practical", "<template id=\"card-tpl\"><div class=\"card\"><h3></h3></div></template>", "Does template execute scripts on page load?"),
        ("What does the <slot> element do in Web Components?", "A <slot> is a placeholder inside a Web Component Shadow DOM where users can inject their own custom HTML content.", "Advanced", "Concept", "<my-element><span slot=\"header\">Custom Title</span></my-element>", "What is default slot content?"),
        ("What is the Shadow DOM in HTML5?", "Shadow DOM provides encapsulated scoping for DOM subtrees and CSS styles inside custom Web Components, preventing style leakage.", "Advanced", "Concept", "element.attachShadow({ mode: 'open' });", "What is the difference between open and closed mode?"),
        ("Which attribute defers offscreen image loading?", "Option C is correct. loading='lazy' delays image downloads until scrolled into view.", "Easy", "MCQ", "", {"A": "defer='true'", "B": "async='image'", "C": "loading='lazy'", "D": "prefetch='off'"}, "C", "Is loading='lazy' supported in all modern browsers?"),
        ("Which element is vector-based and scalable without pixelation?", "Option B is correct. <svg> uses mathematical vectors rather than fixed pixels.", "Easy", "MCQ", "", {"A": "<canvas>", "B": "<svg>", "C": "<img>", "D": "<picture>"}, "B", "Can SVG animate with CSS?"),
        ("What is the purpose of the <audio> controls attribute?", "It instructs the browser to render standard playback UI buttons (play, pause, volume, scrub bar).", "Easy", "Concept", "<audio controls src=\"track.mp3\"></audio>", "What happens if you omit controls?"),
        ("What format is required for WebVTT subtitle files?", "WebVTT files must use UTF-8 text encoding and start with 'WEBVTT' on the first line.", "Advanced", "Concept", "WEBVTT\n\n1\n00:00:01.000 --> 00:00:04.000\nHello world", "Which tag links the vtt file in HTML?"),
        ("What does the allowfullscreen attribute do on an iframe?", "allowfullscreen permits the embedded iframe content (like a video player) to toggle into full-screen mode.", "Easy", "Practical", "<iframe allowfullscreen src=\"video.html\"></iframe>", "Can parent pages block full screen?"),
        ("What does the referrerpolicy attribute do on links and iframes?", "referrerpolicy controls how much referrer information (like source URL) is sent in the HTTP Referer header when navigating.", "Advanced", "Security", "<iframe referrerpolicy=\"no-referrer\" src=\"...\"></iframe>", "Why is strict-origin-when-cross-origin default?"),
        ("How do you embed YouTube videos responsively in HTML?", "Wrap the iframe in a container with aspect-ratio: 16 / 9 or percentage padding in CSS, with width: 100% and height: 100%.", "Intermediate", "Practical", "<div style=\"aspect-ratio:16/9;\"><iframe style=\"width:100%;height:100%;\" ...></iframe></div>", "What does aspect-ratio replace?"),
        ("Can an <img> tag have both width and height attributes in HTML5?", "Yes. Setting width and height attributes reserves space during page layout, preventing Cumulative Layout Shift (CLS).", "Intermediate", "Performance", "<img src=\"pic.jpg\" width=\"800\" height=\"600\" alt=\"Pic\">", "Does CSS override HTML width/height?"),
        ("What is Cumulative Layout Shift (CLS) and how does HTML affect it?", "CLS is a Core Web Vital measuring unexpected layout jumps. Providing width/height on images and media prevents CLS.", "Advanced", "Performance", "<img src=\"ad.jpg\" width=\"300\" height=\"250\" alt=\"Ad\">", "What is an acceptable CLS score?"),
        ("What is the purpose of <meta http-equiv='refresh'>?", "It redirects the browser to another URL or refreshes the page after a specified number of seconds.", "Intermediate", "Practical", "<meta http-equiv=\"refresh\" content=\"5;url=https://example.com\">", "Why is meta refresh discouraged for accessibility?"),
        ("What does <link rel='canonical'> do?", "It indicates the master/original URL for duplicate or syndicated content, preventing duplicate content SEO penalties.", "Intermediate", "SEO", "<link rel=\"canonical\" href=\"https://example.com/original-article\">", "Where should canonical tags be placed?"),
        ("What are Open Graph (og:*) meta tags?", "Open Graph meta tags define titles, descriptions, and preview images displayed when a link is shared on social media (LinkedIn, Twitter).", "Intermediate", "SEO", "<meta property=\"og:title\" content=\"Fresher Practice\">\n<meta property=\"og:image\" content=\"preview.png\">", "Who developed the Open Graph protocol?"),
        ("What does <link rel='preload'> do?", "preload requests critical resources (fonts, hero images) immediately early in the page lifecycle before normal discovery.", "Advanced", "Performance", "<link rel=\"preload\" href=\"font.woff2\" as=\"font\" type=\"font/woff2\" crossorigin>", "What happens if a preloaded resource is not used?")
    ]
    for item in media_data:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Media & APIs", "Graphics & Audio",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 8. Accessibility & ARIA (30 Qs)
    a11y_data = [
        ("What is web accessibility (a11y)?", "Accessibility means designing websites so people with disabilities (visual, auditory, motor, cognitive) can understand and navigate them.", "Easy", "Concept", "", "What does the abbreviation a11y mean?"),
        ("What are the four principles of WCAG (POUR)?", "POUR stands for Perceivable, Operable, Understandable, and Robust.", "Intermediate", "Concept", "", "What is WCAG 2.1 AA level?"),
        ("What is the first rule of ARIA use?", "First rule: Do not use ARIA if you can use a native HTML element with the built-in semantics and behavior already.", "Intermediate", "Concept", "<button>Click</button> <!-- PREFERRED over <div role=\"button\"> -->", "Why are native elements better than ARIA?"),
        ("What does aria-label do?", "aria-label provides an invisible text label read by screen readers when no visible text label exists (e.g. icon buttons).", "Easy", "Accessibility", "<button aria-label=\"Close modal\">&times;</button>", "How does aria-label differ from title?"),
        ("What does aria-labelledby do?", "aria-labelledby references the ID of another visible element on the page to serve as the accessible name for this element.", "Intermediate", "Accessibility", "<div role=\"dialog\" aria-labelledby=\"dlg-title\">\n  <h2 id=\"dlg-title\">Confirm Delete</h2>\n</div>", "Can aria-labelledby reference multiple IDs?"),
        ("What does aria-describedby do?", "aria-describedby references the ID of descriptive or help text that gives additional context after the element's label.", "Intermediate", "Accessibility", "<input aria-describedby=\"pwd-hint\">\n<p id=\"pwd-hint\">Must be 8+ characters.</p>", "How does it differ from aria-labelledby?"),
        ("What does aria-hidden='true' do?", "aria-hidden='true' hides an element and its children from screen readers, useful for purely decorative icons.", "Easy", "Accessibility", "<span class=\"icon\" aria-hidden=\"true\">🔍</span>", "Does aria-hidden hide the element visually?"),
        ("What does role='alert' do in ARIA?", "role='alert' informs screen readers to announce dynamic error messages immediately without waiting for user navigation.", "Intermediate", "Accessibility", "<div role=\"alert\">Payment failed. Please retry.</div>", "What is an aria-live region?"),
        ("What is the difference between aria-live='polite' and aria-live='assertive'?", "'polite' announces dynamic updates when the user is idle. 'assertive' interrupts current screen reader speech to announce immediately.", "Advanced", "Accessibility", "<div aria-live=\"polite\" id=\"status-msg\"></div>", "When should you use assertive?"),
        ("What does tabindex='0' do?", "tabindex='0' includes an element in the natural keyboard tab order in the order it appears in the DOM.", "Easy", "Accessibility", "<div tabindex=\"0\" role=\"button\">Accessible Div</div>", "Can users tab to a normal div without tabindex?"),
        ("What does tabindex='-1' do?", "tabindex='-1' removes an element from the keyboard tab sequence, but allows it to be focused programmatically with element.focus().", "Intermediate", "Accessibility", "<div id=\"error-box\" tabindex=\"-1\">Error</div>", "When would you use element.focus() on tabindex='-1'?"),
        ("Why is a positive tabindex (e.g. tabindex='1') considered bad practice?", "Positive tabindex overrides natural DOM tab flow, creating confusing, unpredictable keyboard navigation for keyboard users.", "Intermediate", "Accessibility", "", "What should you use instead of positive tabindex?"),
        ("What is skip link in web accessibility?", "A skip link is an anchor at the top of a page allowing keyboard users to bypass header navigation and jump straight to main content.", "Intermediate", "Accessibility", "<a href=\"#main\" class=\"skip-link\">Skip to main content</a>", "How is skip link hidden until focused?"),
        ("Why should color alone not be used to convey information?", "Color-blind users may not distinguish states (e.g. red for error). Always pair colors with icons or descriptive text.", "Easy", "Accessibility", "<span class=\"error\">⚠ Field required</span>", "What is the minimum contrast ratio for text in WCAG AA?"),
        ("What is the minimum color contrast ratio for normal text under WCAG AA?", "WCAG AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text (18pt or 14pt bold).", "Intermediate", "Accessibility", "", "Which tool checks contrast ratios?"),
        ("What does role='button' require to be fully accessible?", "It requires tabindex='0', keydown listeners for Enter and Space keys, and appropriate ARIA pressed states if togglable.", "Advanced", "Accessibility", "<div role=\"button\" tabindex=\"0\" onkeydown=\"handleKey(event)\">Button</div>", "Why is <button> preferred?"),
        ("What does aria-expanded do?", "aria-expanded ('true' or 'false') indicates whether an expandable component (like an accordion or dropdown menu) is currently open.", "Intermediate", "Accessibility", "<button aria-expanded=\"false\" aria-controls=\"menu\">Menu</button>", "What does aria-controls do?"),
        ("What does aria-checked do?", "aria-checked indicates the state of a custom checkbox or radio button ('true', 'false', or 'mixed').", "Intermediate", "Accessibility", "<div role=\"checkbox\" aria-checked=\"true\"></div>", "What does 'mixed' mean in tri-state checkboxes?"),
        ("What does aria-disabled do and how does it differ from disabled attribute?", "aria-disabled='true' tells screen readers the element is disabled, but unlike the native disabled attribute, it remains focusable.", "Advanced", "Accessibility", "<button aria-disabled=\"true\">Disabled</button>", "Why is focusable disabled sometimes better?"),
        ("Which attribute hides an element from screen readers while keeping it visible on screen?", "Option B is correct. aria-hidden='true' hides from assistive tech without affecting visual display.", "Easy", "MCQ", "", {"A": "hidden", "B": "aria-hidden='true'", "C": "display:none", "D": "visibility:hidden"}, "B", "What does the hidden attribute do?"),
        ("Which tabindex value makes an element focusable via JavaScript without adding it to tab order?", "Option A is correct. tabindex='-1' allows programmatic focus only.", "Easy", "MCQ", "", {"A": "tabindex='-1'", "B": "tabindex='0'", "C": "tabindex='1'", "D": "tabindex='none'"}, "A", "How do you focus it in JavaScript?"),
        ("What is the purpose of the 'hidden' boolean attribute in HTML5?", "The 'hidden' attribute hides an element both visually and from screen readers (equivalent to display: none).", "Easy", "Practical", "<div hidden>This is completely hidden</div>", "Can CSS display override the hidden attribute?"),
        ("What does role='status' do in ARIA?", "role='status' defines an advisory container for updates that should be announced politely to users (e.g. 'Search complete: 10 results').", "Intermediate", "Accessibility", "<div role=\"status\">3 items found.</div>", "How does role='status' differ from role='alert'?"),
        ("What does aria-required='true' do?", "It indicates to assistive technologies that user input is required on this field before form submission.", "Easy", "Accessibility", "<input aria-required=\"true\">", "Does native required attribute do this automatically?"),
        ("What does aria-invalid='true' do?", "It indicates that the entered value fails validation rules, prompting screen readers to announce an error state.", "Intermediate", "Accessibility", "<input aria-invalid=\"true\" aria-describedby=\"err-msg\">", "When should you set aria-invalid?"),
        ("What is a screen reader and name two common ones?", "A screen reader is assistive software that converts text and structure into synthesized speech. Examples: NVDA, JAWS, VoiceOver.", "Easy", "Concept", "", "Which screen reader is built into macOS and iOS?"),
        ("What does the 'lang' attribute do for screen reader users?", "It tells the screen reader which pronunciation rules, accents, and dictionary to use when voicing the content.", "Easy", "Accessibility", "<p lang=\"fr\">Bonjour le monde</p>", "What happens if a French paragraph has lang='en'?"),
        ("What does role='presentation' or role='none' do?", "It removes semantic meaning from an element (e.g., table used for legacy layout), exposing only its raw text content to screen readers.", "Advanced", "Accessibility", "<table role=\"presentation\">...</table>", "Does it hide text from the screen reader?"),
        ("Why should link text like 'Click Here' or 'Read More' be avoided?", "Screen reader users often browse by link lists out of context; 'Click Here' gives zero information on where the link leads.", "Intermediate", "Accessibility", "<a href=\"/pricing\">View Developer Pricing</a> <!-- PREFERRED -->", "How can you provide screen-reader-only context?"),
        ("What is the sr-only (screen reader only) CSS class pattern?", "A utility class that visually clips and hides text while keeping it readable by screen readers for context.", "Intermediate", "Practical", ".sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); }", "Can display:none be used for sr-only?")
    ]
    for item in a11y_data:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Accessibility & ARIA", "WCAG",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 9. HTML Debugging, Best Practices & Security (30 Qs)
    best_practices = [
        ("What is the difference between HTML and XHTML?", "XHTML is HTML reformulated as strict XML, requiring closing all tags, lowercase tags, quoted attributes, and strict document parsing.", "Intermediate", "Comparison", "", "Why did the web move to HTML5 instead of XHTML 2.0?"),
        ("What happens if you have duplicate ID attributes on the same page?", "Invalid HTML. document.getElementById() will only return the first element, breaking scripts, styles, and label associations.", "Intermediate", "Debugging", "<div id=\"box\"></div>\n<div id=\"box\"></div> <!-- BUG: Duplicate ID -->", "What should you use instead of duplicate IDs?"),
        ("Why should inline styles (<div style='...'>) be avoided in production HTML?", "Inline styles mix presentation with structure, defeat CSS caching, increase HTML file size, and violate strict Content Security Policy (CSP).", "Intermediate", "Scenario", "", "When are inline styles acceptable?"),
        ("What is Content Security Policy (CSP) in HTML?", "CSP is a security standard configured via HTTP headers or <meta> tags that prevents Cross-Site Scripting (XSS) by restricting allowed script sources.", "Advanced", "Security", "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'\">", "Can CSP disallow inline scripts?"),
        ("How does Cross-Site Scripting (XSS) exploit unescaped HTML?", "If user input is injected directly into innerHTML without escaping, an attacker can execute malicious JavaScript (<script> or <img onerror>).", "Advanced", "Security", "<script>fetch('/steal-cookies?c=' + document.cookie)</script>", "How do you protect against XSS in HTML?"),
        ("What is the difference between innerHTML and textContent for preventing XSS?", "textContent treats input strictly as plain text (safe). innerHTML parses HTML tags and executes dangerous script injections.", "Intermediate", "Comparison", "div.textContent = userInput; // Safe\ndiv.innerHTML = userInput; // Vulnerable to XSS", "Can textContent display literal HTML tags?"),
        ("What is HTML sanitization?", "Sanitization cleans user-provided HTML by stripping dangerous tags (<script>, <iframe>) and attributes (onerror, onload) before rendering.", "Advanced", "Security", "DOMPurify.sanitize(dirtyHtml);", "Name a popular JS sanitization library."),
        ("What is clickjacking and how does the X-Frame-Options header prevent it?", "Clickjacking tricks users into clicking invisible iframes. X-Frame-Options: DENY or SAMEORIGIN prevents other sites from embedding your page in iframes.", "Advanced", "Security", "X-Frame-Options: SAMEORIGIN", "What CSP directive replaces X-Frame-Options?"),
        ("What does the 'crossorigin' attribute do on <link> and <script>?", "It controls whether Cross-Origin Resource Sharing (CORS) headers are sent when requesting external assets like fonts or CDN scripts.", "Advanced", "Practical", "<link rel=\"preload\" href=\"font.woff2\" as=\"font\" crossorigin>", "What happens if crossorigin is missing on preloaded fonts?"),
        ("What does Subresource Integrity (SRI) do on <script> tags?", "The 'integrity' attribute contains a cryptographic hash of the script. The browser refuses to execute the script if a CDN was tampered with.", "Advanced", "Security", "<script src=\"https://cdn.example.com/lib.js\" integrity=\"sha384-...\" crossorigin=\"anonymous\"></script>", "What happens if the hash doesn't match?"),
        ("Why should you avoid using obsolete tags like <center>, <font>, and <marquee>?", "They were deprecated in HTML5 because presentation belongs in CSS. They lack semantic meaning and harm modern maintainability.", "Easy", "Concept", "<!-- AVOID --> <font color=\"red\">Text</font>\n<!-- USE --> <span class=\"text-error\">Text</span>", "How do you achieve marquee effect in modern CSS?"),
        ("What does the 'contenteditable' attribute do in HTML?", "The contenteditable boolean attribute makes any HTML element directly editable by the user in the browser window.", "Intermediate", "Practical", "<div contenteditable=\"true\">Click here to edit text</div>", "What does document.execCommand do with contenteditable?"),
        ("What does the 'spellcheck' attribute do?", "The spellcheck attribute specifies whether the browser should check spelling and grammar in text fields and editable elements.", "Easy", "Practical", "<textarea spellcheck=\"true\"></textarea>", "Can you turn spellcheck off on code inputs?"),
        ("What is the purpose of the <dialog> method showModal() vs show()?", "showModal() opens the dialog as a top-layer modal that blocks background interaction and adds a dark ::backdrop. show() opens a non-modal dialog.", "Advanced", "Comparison", "dialogEl.showModal(); // Modal\ndialogEl.show(); // Non-modal", "How do you close a dialog in HTML?"),
        ("How do you close an HTML5 <dialog> with a form?", "Use <form method='dialog'><button>Close</button></form>. Submitting closes the dialog automatically without JavaScript.", "Advanced", "Practical", "<dialog>\n  <form method=\"dialog\"><button>Close</button></form>\n</dialog>", "What is dialog.returnValue?"),
        ("What causes the 'Flash of Unstyled Content' (FOUC)?", "FOUC occurs when HTML renders before external CSS finishes downloading and parsing, momentarily showing raw unstyled content.", "Intermediate", "Scenario", "", "How does placing CSS in the head prevent FOUC?"),
        ("What is a web component Custom Element in HTML?", "A custom element allows developers to define new HTML tags (like <user-card>) with custom behaviors extending HTMLElement.", "Advanced", "Concept", "customElements.define('user-card', UserCard);", "Why must custom element tag names have a hyphen?"),
        ("Why must custom element tag names contain a hyphen (e.g. <my-card>)?", "The hyphen differentiates custom elements from standard HTML tags and guarantees forward compatibility with future HTML specifications.", "Advanced", "Concept", "<my-card></my-card> <!-- Valid -->\n<mycard></mycard> <!-- Invalid -->", "Can you override existing standard HTML tags?"),
        ("What is the difference between client-side rendering (CSR) and server-side rendering (SSR) for HTML?", "In CSR, the server sends a minimal empty HTML shell and JS renders content. In SSR, the server generates full HTML before sending, improving SEO.", "Intermediate", "Comparison", "<div id=\"root\"></div> <!-- CSR shell -->", "Why is SSR better for initial First Contentful Paint?"),
        ("Which attribute prevents an attacker from reading document.cookie via JavaScript?", "The HttpOnly flag set in HTTP Set-Cookie header prevents client-side JavaScript access, mitigating cookie-theft XSS attacks.", "Advanced", "Security", "Set-Cookie: token=xyz; HttpOnly; Secure; SameSite=Strict", "Can JavaScript write to an HttpOnly cookie?"),
        ("What is the purpose of the SameSite cookie attribute?", "SameSite prevents cookies from being sent on cross-site requests, protecting users against Cross-Site Request Forgery (CSRF).", "Advanced", "Security", "Set-Cookie: session=abc; SameSite=Lax", "What are the three values of SameSite?"),
        ("What is the purpose of the HTML5 History API?", "The History API (pushState, replaceState, popstate) enables Single Page Applications to change the URL without full browser page reloads.", "Intermediate", "Concept", "history.pushState({ page: 2 }, '', '/page-2');", "What event fires when the back button is clicked?"),
        ("What is the difference between pushState and replaceState?", "pushState creates a new history entry (can go back). replaceState overwrites the current history entry without adding to history.", "Intermediate", "Comparison", "history.replaceState(null, '', '/updated-filter');", "When is replaceState ideal for filter query params?"),
        ("What does the 'draggable' attribute do in HTML5?", "draggable='true' specifies that an element can be dragged using mouse or touch gestures.", "Intermediate", "Practical", "<div draggable=\"true\">Drag me</div>", "What dataTransfer method stores dragged data?"),
        ("What is the difference between HTML encoding and URL encoding?", "HTML encoding converts special characters (<, >, &) to HTML entities (&lt;, &gt;). URL encoding converts characters to percent-encoded format (%20 for space).", "Intermediate", "Comparison", "&amp; vs %26", "When do you use each?"),
        ("What does the 'translate' attribute do in HTML5?", "The translate boolean attribute specifies whether an element's text should be translated by automatic browser translation tools (e.g. translate='no').", "Intermediate", "Practical", "<span translate=\"no\">BrandName</span>", "Why is translate='no' useful for trademarks?"),
        ("What does the <meter> tag represent?", "The <meter> tag represents a scalar measurement within a known range, such as disk space or temperature.", "Intermediate", "Concept", "<meter min=\"0\" max=\"100\" value=\"75\"></meter>", "How does meter differ from progress?"),
        ("What is the difference between the 'id' and 'class' attributes?", "'id' must be unique per document and identifies a single element. 'class' is non-unique and groups multiple elements for shared styling.", "Easy", "Comparison", "<div id=\"header\" class=\"container dark\"></div>", "Which has higher CSS specificity: id or class?"),
        ("What is an HTML linter and why should developers use one?", "An HTML linter (like HTMLHint) checks markup for syntax errors, unclosed tags, duplicate IDs, and accessibility violations automatically.", "Easy", "Practical", "", "Can linters be integrated into code editors?"),
        ("What is the final status of HTML: is it case-sensitive?", "HTML tags and attribute names are case-insensitive, but lowercase is the universal W3C standard and best practice for readability.", "Easy", "Concept", "<p> vs <P>", "Are attribute values case-sensitive?")
    ]
    for item in best_practices:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-html-{num}", num, "HTML", "Best Practices", "Quality & Security",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    print(f"Built HTML pack: {len(qs)} questions (Target: >=200)")
    return qs
