"""
bank_builders/pack_css.py
Generates 210+ genuine, interview-focused CSS questions for freshers.
Covers: Selectors, specificity, box model, display, positioning, flexbox,
grid, responsive design, media queries, units, typography, transitions,
transforms, animations, CSS variables, centering, debugging.
"""

from .common import make_q, parse_item

def build_css_pack(start_num=1):
    qs = []
    num = start_num

    items = [
        # 1. Selectors & Specificity (30 Qs)
        ("Selectors", "Element Selector", "What is an element selector in CSS?", "An element selector targets HTML elements by their tag name, such as p, h1, or div, applying styles to all matching tags.", "Easy", "Concept", "p { color: #333; }", "What is the specificity of an element selector?"),
        ("Selectors", "Class Selector", "What is a class selector in CSS and how is it written?", "A class selector targets elements with a specific class attribute using a dot prefix (.btn), and can be applied to multiple elements.", "Easy", "Concept", ".btn { padding: 8px 16px; }", "Can an element have multiple classes?"),
        ("Selectors", "ID Selector", "What is an ID selector and why should it be used sparingly in CSS?", "An ID selector uses a hash prefix (#header) to target a unique element. It has very high specificity, making style overrides difficult.", "Easy", "Concept", "#main-nav { background: #111; }", "What is the specificity value of an ID?"),
        ("Selectors", "Universal Selector", "What does the universal selector (*) do in CSS?", "The universal selector (*) matches every single element in the DOM. It is often used for resetting margins and box-sizing.", "Easy", "Concept", "* { box-sizing: border-box; }", "Does the universal selector impact page rendering performance?"),
        ("Selectors", "Grouping Selectors", "How do you apply the same styles to multiple selectors?", "Separate the selectors with a comma: h1, h2, h3 { font-family: sans-serif; }.", "Easy", "Practical", "h1, h2, h3 { color: #1e293b; }", "What happens if one selector in a comma list is invalid?"),
        ("Selectors", "Descendant Combinator", "What is the descendant combinator (space) in CSS?", "The descendant combinator (e.g. div p) targets all <p> elements that are nested inside a <div>, regardless of depth.", "Easy", "Concept", "article p { line-height: 1.6; }", "How does descendant differ from child combinator?"),
        ("Selectors", "Child Combinator", "What is the child combinator (>) in CSS?", "The child combinator (div > p) targets only direct child <p> elements immediately inside a <div>, ignoring deeper nested descendants.", "Easy", "Comparison", "ul > li { list-style: none; }", "When would you prefer child over descendant?"),
        ("Selectors", "Adjacent Sibling", "What does the adjacent sibling combinator (+) do?", "The adjacent sibling combinator (h1 + p) matches the second element only if it immediately follows the first element at the same hierarchy level.", "Intermediate", "Concept", "h2 + p { margin-top: 0; }", "Does adjacent sibling match if another tag is between them?"),
        ("Selectors", "General Sibling", "What does the general sibling combinator (~) do?", "The general sibling combinator (h1 ~ p) matches all <p> elements that follow an <h1> as siblings, even if not immediately adjacent.", "Intermediate", "Concept", "h2 ~ p { color: #555; }", "Must they share the same parent?"),
        ("Selectors", "Attribute Selector", "How do you select input elements of type text using CSS?", "Use an attribute selector: input[type='text'] { border: 1px solid #ccc; }.", "Easy", "Practical", "input[type=\"text\"] { border: 1px solid #ccc; }", "Can attribute selectors match partial strings?"),
        ("Selectors", "Attribute Matchers", "What is the difference between [attr^='val'], [attr$='val'], and [attr*='val']?", "^= matches values starting with 'val', $= matches values ending with 'val', and *= matches values containing 'val' anywhere.", "Intermediate", "Practical", "a[href^=\"https:\"] { font-weight: bold; }\na[href$=\".pdf\"] { color: red; }", "How do you target external links?"),
        ("Selectors", "Specificity Hierarchy", "What is CSS specificity and how is it calculated?", "Specificity determines which CSS rule applies when multiple rules match. Calculated as: Inline styles (1000) > IDs (100) > Classes/attributes/pseudo-classes (10) > Elements/pseudo-elements (1).", "Intermediate", "Concept", "", "What happens if two rules have equal specificity?"),
        ("Selectors", "Specificity Calculation", "Between '#nav .link' and 'nav .item a.active', which rule wins?", "Option A wins. #nav .link has specificity 110 (1 ID, 1 class). nav .item a.active has specificity 22 (2 classes, 2 elements). The ID wins.", "Intermediate", "Practical", "#nav .link { color: red; } /* 110 */\nnav .item a.active { color: blue; } /* 022 */", "Does a class selector ever beat an ID selector?"),
        ("Selectors", "The !important Flag", "What does !important do in CSS and why is it discouraged?", "!important overrides all normal specificity rules. Overusing it creates brittle stylesheets where rules cannot be naturally overridden.", "Intermediate", "Scenario", "p { color: red !important; }", "Can anything override an !important rule?"),
        ("Selectors", "Cascade Principle", "What is the Cascade in CSS?", "The Cascade is the algorithm browsers use to resolve conflicting rules based on Origin (user/browser/author), Specificity, and Source Order.", "Intermediate", "Concept", "", "If specificity is equal, which rule applies?"),
        ("Selectors", "Inheritance", "Which CSS properties are inherited by default?", "Text properties (color, font-family, font-size, line-height, text-align) are inherited from parent to children. Box-model properties (margin, padding, border) are NOT.", "Easy", "Concept", "body { color: #333; } /* Inherited by p, span */", "How do you force a child to inherit margin?"),
        ("Selectors", "Inherit vs Initial", "What is the difference between inherit, initial, and unset in CSS?", "inherit takes the parent's computed value. initial resets to the CSS spec default. unset acts like inherit if inheritable, otherwise initial.", "Intermediate", "Comparison", "div { border: inherit; }", "What does 'revert' do?"),
        ("Selectors", "Pseudo-Classes", "What is a CSS pseudo-class?", "A pseudo-class targets an element's state or document tree position, written with a single colon (e.g. :hover, :focus, :first-child).", "Easy", "Concept", "button:hover { background: #0284c7; }", "How does a pseudo-class differ from a pseudo-element?"),
        ("Selectors", "Pseudo-Elements", "What is a CSS pseudo-element?", "A pseudo-element targets a virtual sub-part of an element, written with double colons (e.g. ::before, ::after, ::placeholder, ::first-line).", "Easy", "Concept", "p::first-letter { font-size: 2em; }", "Why are double colons standard in CSS3?"),
        ("Selectors", "::before and ::after", "What is required for ::before and ::after to render?", "The 'content' property is mandatory (even if empty string content: ''). Without 'content', the pseudo-element will not generate in the DOM.", "Intermediate", "Practical", ".badge::before { content: '★ '; color: gold; }", "Can pseudo-elements be selected in JavaScript?"),
        ("Selectors", ":nth-child()", "How do you select every alternate (even) table row in CSS?", "Use tr:nth-child(even) or tr:nth-child(2n).", "Easy", "Practical", "tr:nth-child(even) { background: #f8fafc; }", "How do you select odd rows?"),
        ("Selectors", ":nth-child vs :nth-of-type", "What is the difference between :nth-child(2) and :nth-of-type(2)?", ":nth-child(2) selects the 2nd child overall if it matches. :nth-of-type(2) filters only elements of that specific tag type first, then picks the 2nd.", "Intermediate", "Comparison", "<p>1</p><div>2</div><p>3</p>\np:nth-of-type(2) matches paragraph '3'.", "Which is safer when multiple tag types are siblings?"),
        ("Selectors", ":not() Pseudo-Class", "What does the :not() pseudo-class do?", "The :not() negation pseudo-class matches elements that do not match the selector list inside its parentheses.", "Intermediate", "Practical", "button:not(.btn-primary) { opacity: 0.8; }", "Does :not() add specificity?"),
        ("Selectors", ":is() and :where()", "What is the difference between :is() and :where()?", "Both match any selector in their list. :is() takes the specificity of its most specific argument. :where() always has 0 specificity.", "Advanced", "Comparison", ":where(h1, h2, h3) { margin: 0; } /* Specificity: 0 */", "Why is :where() great for CSS reset stylesheets?"),
        ("Selectors", ":has() Parent Selector", "What does the CSS :has() relational selector do?", "The :has() pseudo-class selects a parent element based on whether it contains matching children (a native parent selector in CSS).", "Advanced", "Concept", "article:has(img) { grid-column: span 2; }", "Can :has() check for siblings?"),
        ("Selectors", ":focus vs :focus-visible", "What is the difference between :focus and :focus-visible?", ":focus applies whenever an element is focused. :focus-visible applies only when keyboard navigation is used (not on mouse clicks).", "Intermediate", "Accessibility", "button:focus-visible { outline: 2px solid blue; }", "Why does :focus-visible improve UX?"),
        ("Selectors", ":root Selector", "What is the :root pseudo-class in CSS?", ":root targets the highest-level element in the document tree (<html> in HTML). It is the standard place to declare global CSS custom properties.", "Easy", "Concept", ":root { --brand-color: #38bdf8; }", "Does :root have higher specificity than html?"),
        ("Selectors", "Selector Specificity MCQ", "Which selector has the highest specificity?", "Option C is correct. ID selector has specificity (0,1,0,0) which beats any number of classes.", "Easy", "MCQ", "", {"A": ".nav .list .item a", "B": "header ul li a.active", "C": "#header .nav a", "D": "div.container div.row div.col"}, "C", "What is the numerical specificity of #header .nav a?"),
        ("Selectors", "Pseudo Element MCQ", "Which property is required to make ::before or ::after appear?", "Option B is correct. Without content, pseudo-elements are not generated.", "Easy", "MCQ", "", {"A": "display: block", "B": "content", "C": "visibility: visible", "D": "position: absolute"}, "B", "Can content be set to an image URL?"),
        ("Selectors", ":empty Selector", "What does the :empty pseudo-class match?", ":empty matches elements that have no children at all, including no text nodes and no whitespace.", "Intermediate", "Concept", "p:empty { display: none; }", "Does a space count as content for :empty?"),

        # 2. Box Model & Layout Fundamentals (35 Qs)
        ("Box Model", "Components", "What are the four components of the CSS Box Model?", "From inside out: Content (text/media), Padding (inner space), Border (boundary line), and Margin (outer clearance).", "Easy", "Concept", "", "Which component is affected by background-color?"),
        ("Box Model", "box-sizing", "What is the difference between content-box and border-box?", "content-box adds padding and border onto specified width (total = width + padding + border). border-box includes padding and border within the specified width.", "Easy", "Comparison", "* { box-sizing: border-box; }", "What is the default box-sizing in browsers?"),
        ("Box Model", "Total Width Calculation", "With width: 200px, padding: 20px, border: 5px, what is the total rendered width in content-box?", "250px (200px width + 20px left pad + 20px right pad + 5px left border + 5px right border).", "Easy", "Practical", ".box { width: 200px; padding: 20px; border: 5px solid; }", "What would it be with box-sizing: border-box?"),
        ("Box Model", "Universal Box-Sizing", "Why do developers set * { box-sizing: border-box; } at the top of CSS files?", "It makes layout sizing predictable: an element set to width: 100% or 300px will never break outside its container due to padding or borders.", "Easy", "Practical", "*, *::before, *::after { box-sizing: border-box; }", "Does border-box include margins?"),
        ("Box Model", "Margin Collapsing", "What is margin collapsing in CSS?", "When top and bottom vertical margins of adjacent block elements touch, they combine into a single margin equal to the largest of the two.", "Intermediate", "Concept", "h1 { margin-bottom: 30px; }\np { margin-top: 20px; }\n/* Resulting gap is 30px, not 50px */", "Do horizontal margins collapse?"),
        ("Box Model", "Prevent Margin Collapse", "How can you prevent margin collapsing between a parent and child?", "Add a border, padding, overflow: hidden, or display: flow-root to the parent element.", "Intermediate", "Practical", ".parent { display: flow-root; }", "What is BFC?"),
        ("Box Model", "Negative Margins", "What happens when you apply a negative margin in CSS?", "A negative margin pulls the element in that direction or pulls subsequent sibling elements closer over it.", "Intermediate", "Practical", ".card { margin-top: -20px; }", "Can negative margins cause content overlap?"),
        ("Box Model", "Margin Auto Centering", "How does margin: 0 auto center a block element horizontally?", "When a block element has a fixed width, margin: auto divides the remaining available container space equally between left and right margins.", "Easy", "Practical", ".container { width: 900px; margin: 0 auto; }", "Does margin: auto center vertically in normal block flow?"),
        ("Box Model", "Padding Shorthand", "In padding: 10px 20px 30px 40px, which value represents which side?", "Clockwise order: Top (10px), Right (20px), Bottom (30px), Left (40px).", "Easy", "Concept", "padding: 10px 20px 30px 40px;", "What if only two values are provided?"),
        ("Box Model", "Two-Value Padding", "In padding: 10px 20px, what do the two values represent?", "First value (10px) applies to Top and Bottom. Second value (20px) applies to Left and Right.", "Easy", "Concept", "padding: 10px 20px;", "What if three values are provided?"),
        ("Box Model", "display: block", "What are the characteristics of display: block?", "Block elements start on a new line, take up the full available container width, and respect width, height, padding, and margin properties.", "Easy", "Concept", "div { display: block; }", "Name three default block elements."),
        ("Box Model", "display: inline", "What are the characteristics of display: inline?", "Inline elements flow within text without starting a new line. They ignore width, height, and vertical margins/padding.", "Easy", "Concept", "span { display: inline; }", "Can an inline element have horizontal padding?"),
        ("Box Model", "display: inline-block", "What is display: inline-block and when is it useful?", "inline-block flows horizontally like inline text, but respects width, height, vertical margins, and padding like a block element.", "Easy", "Comparison", ".btn { display: inline-block; width: 120px; }", "What causes the white-space gap between inline-block elements?"),
        ("Box Model", "display: none vs visibility: hidden", "What is the difference between display: none and visibility: hidden?", "display: none removes the element from document layout entirely (takes 0 space). visibility: hidden hides the element visually but preserves its layout space.", "Easy", "Comparison", ".hidden { display: none; } /* 0 space */\n.invisible { visibility: hidden; } /* takes space */", "Does display: none trigger screen readers?"),
        ("Box Model", "opacity: 0 vs visibility: hidden", "How does opacity: 0 differ from visibility: hidden?", "opacity: 0 is completely transparent, takes up layout space, and STILL receives click and focus events unless pointer-events: none is added.", "Intermediate", "Comparison", ".ghost { opacity: 0; pointer-events: none; }", "Can opacity: 0 be transitioned smoothly?"),
        ("Box Model", "outline vs border", "What is the difference between outline and border in CSS?", "Borders add to element dimensions and trigger layout recalculations. Outlines are drawn outside the border without taking layout space or affecting size.", "Intermediate", "Comparison", ":focus-visible { outline: 2px solid #38bdf8; }", "Can outline have rounded corners in modern CSS?"),
        ("Box Model", "border-radius", "How do you create a perfect circle from a square element in CSS?", "Set width and height to equal values and border-radius: 50%.", "Easy", "Practical", ".avatar { width: 64px; height: 64px; border-radius: 50%; }", "Can border-radius have different horizontal and vertical radii?"),
        ("Box Model", "box-shadow Syntax", "What are the values in box-shadow: 2px 4px 6px 1px rgba(0,0,0,0.2)?", "In order: Horizontal offset (2px), Vertical offset (4px), Blur radius (6px), Spread radius (1px), and Shadow color.", "Intermediate", "Practical", "box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);", "How do you make an inset (inner) shadow?"),
        ("Box Model", "overflow Values", "What are the four common values of the overflow property?", "visible (content spills out; default), hidden (clips excess content), scroll (always shows scrollbars), and auto (shows scrollbars only if needed).", "Easy", "Concept", ".box { overflow: auto; }", "Can you configure overflow-x and overflow-y separately?"),
        ("Box Model", "overflow: hidden for BFC", "Why does overflow: hidden clear floats and prevent margin collapsing?", "overflow: hidden establishes a new Block Formatting Context (BFC), which contains floated descendants and prevents external margin collapse.", "Intermediate", "Concept", ".container { overflow: hidden; }", "What modern property replaces overflow: hidden for BFC?"),
        ("Box Model", "display: flow-root", "What is display: flow-root in modern CSS?", "display: flow-root creates a new Block Formatting Context without unintended side effects like clipping tooltips or dropdowns.", "Intermediate", "Concept", ".clearfix { display: flow-root; }", "Is flow-root supported in all modern browsers?"),
        ("Box Model", "min-width vs max-width", "What is the difference between min-width and max-width?", "min-width guarantees an element never shrinks below that width. max-width prevents an element from expanding beyond that width.", "Easy", "Comparison", ".card { width: 100%; max-width: 400px; }", "How does max-width: 100% make images responsive?"),
        ("Box Model", "Responsive Images Rule", "What is the standard CSS rule to make images responsive?", "img { max-width: 100%; height: auto; display: block; } prevents images from overflowing their parent while preserving aspect ratio.", "Easy", "Practical", "img { max-width: 100%; height: auto; }", "Why add height: auto?"),
        ("Box Model", "aspect-ratio Property", "What does the CSS aspect-ratio property do?", "aspect-ratio maintains a fixed ratio between width and height (e.g. aspect-ratio: 16 / 9) without requiring vertical padding hacks.", "Intermediate", "Practical", ".video-box { aspect-ratio: 16 / 9; width: 100%; }", "Does aspect-ratio prevent Cumulative Layout Shift?"),
        ("Box Model", "object-fit Property", "What are the common values of object-fit on images and videos?", "fill (stretches), contain (scales to fit without cropping), cover (fills box while preserving ratio, cropping edges), and none.", "Intermediate", "Practical", "img.cover { width: 100%; height: 200px; object-fit: cover; }", "How does object-fit differ from background-size?"),
        ("Box Model", "object-position", "What does the object-position property do?", "object-position aligns the content of a replaced element (image/video) inside its box, similar to background-position (e.g. object-position: top center).", "Intermediate", "Practical", "img { object-fit: cover; object-position: center top; }", "What is the default value of object-position?"),
        ("Box Model", "clip-path Property", "What does the clip-path property do in CSS?", "clip-path defines a specific clipping region (polygon, circle, ellipse); only the area inside the region remains visible.", "Advanced", "Practical", ".arrow { clip-path: polygon(0 0, 100% 50%, 0 100%); }", "Can clip-path be animated with transitions?"),
        ("Box Model", "calc() Function", "How do you mix different units in CSS using calc()?", "calc() performs mathematical calculations across units: width: calc(100% - 40px); (always ensure spaces around + and - operators).", "Easy", "Practical", "width: calc(100% - 32px);", "Why are spaces required around plus and minus in calc?"),
        ("Box Model", "clamp() Function", "What does clamp(min, preferred, max) do in CSS?", "clamp() clamps a value between a lower minimum and upper maximum limit, ideal for fluid responsive typography (font-size: clamp(1rem, 2.5vw, 2rem)).", "Intermediate", "Practical", "font-size: clamp(14px, 2vw, 18px);", "What functions does clamp combine?"),
        ("Box Model", "min() and max() Functions", "What is the difference between min() and max() in CSS?", "min(a, b) selects the smallest value (acts like a ceiling / max-width). max(a, b) selects the largest value (acts like a floor / min-width).", "Intermediate", "Comparison", "width: min(100%, 600px);", "How does min(100%, 600px) replace max-width?"),
        ("Box Model", "Box Model MCQ", "Under box-sizing: border-box, what is the total width of an element with width: 300px, padding: 20px, and border: 2px?", "Option B is correct. In border-box, padding and border are included inside the specified 300px width.", "Easy", "MCQ", "", {"A": "344px", "B": "300px", "C": "322px", "D": "256px"}, "B", "What would it be under content-box?"),
        ("Box Model", "Display MCQ", "Which display value takes up the full width of its parent and starts on a new line?", "Option A is correct. block elements occupy full width by default.", "Easy", "MCQ", "", {"A": "block", "B": "inline", "C": "inline-block", "D": "flex-inline"}, "A", "Name two default inline elements."),
        ("Box Model", "Visibility MCQ", "Which CSS property hides an element while still keeping its space in the layout?", "Option C is correct. visibility: hidden retains layout space.", "Easy", "MCQ", "", {"A": "display: none", "B": "opacity: 0", "C": "visibility: hidden", "D": "overflow: hidden"}, "C", "How does display: none differ?"),
        ("Box Model", "pointer-events: none", "What does pointer-events: none do in CSS?", "It makes the element transparent to mouse and touch events, allowing clicks to pass through to elements underneath.", "Intermediate", "Practical", ".overlay { pointer-events: none; }", "Can pointer-events be turned back on for children?"),
        ("Box Model", "user-select Property", "How do you prevent users from selecting text in CSS?", "Use user-select: none; on the element or button.", "Easy", "Practical", "button { user-select: none; }", "Can users still copy text via Inspect Element?")
    ]
    for item in items:
        top, subtop, q_text, ans, diff, qtype, code, *rest = item
        mcq_opts, correct_opt, fup = None, None, ""
        if len(rest) == 1:
            fup = rest[0]
        elif len(rest) == 3:
            mcq_opts, correct_opt, fup = rest

        qs.append(make_q(
            f"q-css-{num}", num, "CSS", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 3. Positioning & Layout (35 Qs)
    positioning = [
        ("Positioning", "position: static", "What is position: static in CSS?", "position: static is the default positioning. The element flows naturally in the document and ignores top, right, bottom, left, and z-index.", "Easy", "Concept", "div { position: static; }", "Do top/left work on static elements?"),
        ("Positioning", "position: relative", "What does position: relative do?", "The element is offset relative to its original normal position using top/right/bottom/left without affecting surrounding elements. It also acts as an anchor for absolute children.", "Easy", "Concept", ".box { position: relative; top: 10px; }", "Does relative positioning leave a gap where it was?"),
        ("Positioning", "position: absolute", "What is position: absolute in CSS?", "The element is removed from normal document flow and positioned relative to its nearest positioned ancestor (ancestor with relative, absolute, or fixed).", "Easy", "Concept", ".badge { position: absolute; top: 0; right: 0; }", "What ancestor does it use if none are positioned?"),
        ("Positioning", "Relative Parent + Absolute Child", "Why is a parent given position: relative when a child has position: absolute?", "position: relative establishes a containing positioning context for the child without altering the parent's normal document flow.", "Easy", "Practical", ".card { position: relative; }\n.card-badge { position: absolute; top: 8px; right: 8px; }", "What happens if the parent is static?"),
        ("Positioning", "position: fixed", "What is position: fixed in CSS?", "The element is removed from document flow and positioned relative to the browser viewport. It stays pinned in the same spot even during scrolling.", "Easy", "Concept", ".navbar { position: fixed; top: 0; left: 0; width: 100%; }", "Can an ancestor transform break fixed positioning?"),
        ("Positioning", "position: sticky", "What is position: sticky and how does it work?", "sticky acts like position: relative until the page scrolls past a defined threshold (e.g. top: 0), at which point it sticks like position: fixed within its parent container.", "Intermediate", "Concept", ".sidebar { position: sticky; top: 20px; }", "What CSS property on a parent breaks position: sticky?"),
        ("Positioning", "Why Sticky Fails", "Why does position: sticky stop working if an ancestor has overflow: hidden?", "sticky requires a scrolling ancestor. overflow: hidden, auto, or scroll on any ancestor traps the scroll boundary and disables sticking.", "Intermediate", "Debugging", "/* BUG: sticky header fails if body/parent has overflow:hidden */", "How do you debug broken sticky elements?"),
        ("Positioning", "z-index Property", "What does z-index control and what positioning is required for it to work?", "z-index controls 3D stacking order along the z-axis (higher values stack on top). It only works on positioned elements (relative, absolute, fixed, sticky) or flex/grid items.", "Easy", "Concept", ".modal { position: fixed; z-index: 1000; }", "Does z-index work on position: static?"),
        ("Positioning", "Stacking Context", "What is a Stacking Context in CSS and what creates one?", "A stacking context is an isolated 3D layer where child z-indexes are resolved locally. Created by opacity < 1, transform != none, filter, will-change, or z-index on positioned elements.", "Advanced", "Concept", ".parent { opacity: 0.99; /* creates stacking context */ }", "Can a child escape its parent's stacking context?"),
        ("Positioning", "z-index 99999 Bug", "Why does setting z-index: 99999 sometimes fail to bring a modal above other elements?", "If the modal is inside a parent with a lower stacking context than a sibling container, no child z-index can ever break above the sibling context.", "Advanced", "Debugging", "/* Parent A has z-index:1, Parent B has z-index:2.\nChild in A with z-index:99999 is STILL under Parent B. */", "How do you fix this stacking context bug?"),
        ("Positioning", "inset Property", "What is the inset shorthand property in modern CSS?", "inset is a shorthand for top, right, bottom, and left simultaneously (e.g. inset: 0 is equivalent to top: 0; right: 0; bottom: 0; left: 0;).", "Intermediate", "Practical", ".overlay { position: absolute; inset: 0; }", "Can inset accept 1 to 4 values like padding?"),
        ("Positioning", "Centering with Absolute + Transform", "How do you center an element of unknown size using absolute positioning?", "Set top: 50%; left: 50%; and transform: translate(-50%, -50%);.", "Easy", "Practical", ".modal { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }", "Why is translate(-50%, -50%) needed?"),
        ("Positioning", "Positioning MCQ", "Which positioning keeps an element in place relative to the viewport while scrolling?", "Option B is correct. position: fixed remains anchored to the viewport.", "Easy", "MCQ", "", {"A": "position: absolute", "B": "position: fixed", "C": "position: relative", "D": "position: static"}, "B", "How does sticky positioning differ?"),
        ("Positioning", "Sticky Constraint", "Can position: sticky scroll past the bottom of its parent container?", "No. A sticky element will never extend beyond the boundaries of its immediate parent container.", "Intermediate", "Concept", "", "What happens when you scroll past the parent container?"),
        ("Positioning", "Float Property", "What was the float property originally designed for?", "float was designed to wrap text around images (like magazine columns) before modern Flexbox and Grid were introduced.", "Easy", "Concept", "img { float: left; margin-right: 15px; }", "Why should floats not be used for main page layouts?"),
        ("Positioning", "Clearfix Pattern", "What was the clearfix hack and why was it necessary?", "Floated children cause parents to collapse to 0 height. Clearfix forced the parent to contain floated children using a ::after pseudo-element clearing floats.", "Intermediate", "Concept", ".clearfix::after { content: ''; display: table; clear: both; }", "What modern property replaces clearfix?"),
        ("Positioning", "clear Property", "What does clear: both do in CSS?", "clear: both prevents an element from sitting adjacent to earlier floated elements, moving it down below any left or right floats.", "Easy", "Concept", ".footer { clear: both; }", "What are the other values for clear?"),
        ("Positioning", "Fixed Navbar Spacer", "When using a fixed navbar (position: fixed; height: 60px), why does the top page content get hidden?", "Fixed elements are removed from document flow. Add padding-top: 60px to <body> or <main> to offset the fixed navbar height.", "Easy", "Scenario", "body { padding-top: 60px; }", "What is scroll-padding-top used for?"),
        ("Positioning", "scroll-padding-top", "What does scroll-padding-top do when linking to anchor IDs with a fixed header?", "It offsets the scroll destination position so anchor headings do not get hidden behind a fixed sticky navbar when clicked.", "Intermediate", "Practical", "html { scroll-padding-top: 70px; }", "Does scroll-padding work with smooth scrolling?"),
        ("Positioning", "scroll-behavior: smooth", "How do you enable smooth page scrolling for anchor navigation in pure CSS?", "Add scroll-behavior: smooth; to the <html> root element.", "Easy", "Practical", "html { scroll-behavior: smooth; }", "Can this be disabled for users preferring reduced motion?"),
        ("Positioning", "prefers-reduced-motion", "How do you respect accessibility preferences for users who suffer from motion sickness?", "Use the @media (prefers-reduced-motion: reduce) media query to disable or simplify animations and transitions.", "Intermediate", "Accessibility", "@media (prefers-reduced-motion: reduce) {\n  * { animation: none !important; transition: none !important; }\n}", "How does an OS set this preference?"),
        ("Positioning", "will-change Property", "What does will-change do in CSS and why should it be used cautiously?", "will-change hints to the browser ahead of time which properties will animate, promoting the element to its own GPU compositor layer. Overuse wastes GPU memory.", "Advanced", "Performance", ".animated-box { will-change: transform, opacity; }", "When should will-change be applied and removed?"),
        ("Positioning", "contain Property", "What does the CSS contain property do?", "contain isolates a DOM subtree from the rest of the page so browser recalculations of layout, style, or paint do not affect outside elements.", "Advanced", "Performance", ".widget { contain: layout paint; }", "How does contain improve large list scrolling?"),
        ("Positioning", "content-visibility Property", "What does content-visibility: auto do in modern CSS?", "content-visibility: auto skips rendering and painting offscreen elements until they are near the viewport, drastically speeding up initial page load.", "Advanced", "Performance", ".long-article-section { content-visibility: auto; contain-intrinsic-size: 500px; }", "Why is contain-intrinsic-size needed?"),
        ("Positioning", "contain-intrinsic-size", "Why must contain-intrinsic-size accompany content-visibility: auto?", "It provides estimated placeholder height for offscreen elements before they render, preventing severe scrollbar jumping.", "Advanced", "Performance", ".section { content-visibility: auto; contain-intrinsic-size: 1px 400px; }", "What happens to the scrollbar without it?"),
        ("Positioning", "Subpixel Rendering", "What causes 1px blurry lines or borders during CSS transitions and transforms?", "Subpixel positioning when an element's coordinates or dimensions compute to non-integer floating-point pixel values.", "Advanced", "Debugging", "", "How does backface-visibility: hidden help?"),
        ("Positioning", "backface-visibility", "What does backface-visibility: hidden do in 3D transforms?", "It hides the reverse side of an element when rotated in 3D space, essential for card flip effects.", "Intermediate", "Practical", ".card-front { backface-visibility: hidden; }", "What is the default value of backface-visibility?"),
        ("Positioning", "perspective Property", "What does the perspective property do in 3D transforms?", "perspective defines the distance between the viewer and the z=0 plane, giving 3D transformed child elements visual depth.", "Intermediate", "Concept", ".scene { perspective: 800px; }", "Where is perspective placed: parent or child?"),
        ("Positioning", "transform-style: preserve-3d", "Why is transform-style: preserve-3d needed for nested 3D elements?", "By default, children are flattened into the 2D plane of their parent. preserve-3d keeps children in shared 3D space.", "Advanced", "Practical", ".cube { transform-style: preserve-3d; }", "What is the default transform-style?"),
        ("Positioning", "z-index Stacking MCQ", "Which of the following creates a new stacking context?", "Option C is correct. opacity less than 1 creates a new stacking context on the element.", "Intermediate", "MCQ", "", {"A": "margin: 0 auto", "B": "padding: 20px", "C": "opacity: 0.95", "D": "color: red"}, "C", "Does transform: translate(0) create a stacking context?"),
        ("Positioning", "Top vs Translate Performance", "Why is animating transform: translateY() preferred over top/bottom for performance?", "transform runs on the GPU compositor thread without triggering layout or repaint cycles. Changing top triggers expensive layout recalculations.", "Intermediate", "Performance", "/* FAST (Composited) */\ntransform: translateY(10px);\n/* SLOW (Triggers Layout) */\ntop: 10px;", "What two properties are cheapest to animate in CSS?"),
        ("Positioning", "Composite-Only Properties", "What are the only two CSS properties that animate purely on the GPU compositor thread?", "transform and opacity. They do not trigger layout (reflow) or paint cycles.", "Intermediate", "Performance", "", "Does background-color trigger repaint?"),
        ("Positioning", "Reflow vs Repaint", "What is the difference between Reflow (Layout) and Repaint in browser rendering?", "Reflow recalculates the geometric positions and dimensions of elements. Repaint redraws visual pixels (colors, shadows) without changing geometry.", "Intermediate", "Performance", "", "Does reflow always cause repaint?"),
        ("Positioning", "Sticky Header MCQ", "Which parent property prevents position: sticky from functioning?", "Option B is correct. overflow: hidden traps the scroll context.", "Intermediate", "MCQ", "", {"A": "display: flex", "B": "overflow: hidden", "C": "background: #fff", "D": "width: 100%"}, "B", "How can you detect this in DevTools?"),
        ("Positioning", "clip vs clip-path", "Why is the CSS clip property deprecated?", "clip only worked on position: absolute elements and only supported rectangular clipping. clip-path supports all elements and any shape.", "Easy", "Concept", "", "What shapes does clip-path support?")
    ]
    for item in positioning:
        top, subtop, q_text, ans, diff, qtype, code, *rest = item
        mcq_opts, correct_opt, fup = None, None, ""
        if len(rest) == 1:
            fup = rest[0]
        elif len(rest) == 3:
            mcq_opts, correct_opt, fup = rest

        qs.append(make_q(
            f"q-css-{num}", num, "CSS", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 4. Flexbox Layout (35 Qs)
    flexbox = [
        ("Flexbox", "display: flex", "What happens when you apply display: flex to a container?", "The container becomes a flex container, and all its direct children immediately become flex items flowing along a main axis (row by default).", "Easy", "Concept", ".container { display: flex; }", "Do grandchildren become flex items?"),
        ("Flexbox", "Main vs Cross Axis", "What is the difference between the main axis and cross axis in Flexbox?", "The main axis is the primary direction items flow (defined by flex-direction). The cross axis runs perpendicular (at 90 degrees) to the main axis.", "Easy", "Concept", "/* row: main = horizontal, cross = vertical */\n/* column: main = vertical, cross = horizontal */", "How does changing flex-direction change the axes?"),
        ("Flexbox", "flex-direction", "What are the four values of flex-direction?", "row (horizontal left-to-right; default), row-reverse (right-to-left), column (vertical top-to-bottom), and column-reverse (bottom-to-top).", "Easy", "Concept", ".nav { flex-direction: column; }", "How does column affect justify-content?"),
        ("Flexbox", "justify-content", "What does justify-content do in Flexbox?", "justify-content aligns flex items along the main axis. Common values: flex-start, flex-end, center, space-between, space-around, space-evenly.", "Easy", "Concept", ".row { display: flex; justify-content: space-between; }", "Which axis does justify-content control?"),
        ("Flexbox", "align-items", "What does align-items do in Flexbox?", "align-items aligns flex items along the cross axis across the single current line. Common values: stretch (default), flex-start, flex-end, center, baseline.", "Easy", "Concept", ".row { display: flex; align-items: center; }", "What is the default value of align-items?"),
        ("Flexbox", "align-items: stretch", "Why do flex items automatically stretch to equal heights by default?", "Because the default value of align-items is 'stretch', forcing all items to match the height of the tallest item in the row.", "Easy", "Concept", ".container { display: flex; /* items stretch */ }", "How do you stop items from stretching?"),
        ("Flexbox", "Centering with Flexbox", "How do you center an element both horizontally and vertically using Flexbox?", "Set display: flex; justify-content: center; align-items: center; on the parent container.", "Easy", "Practical", ".parent {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n}", "Can margin: auto on a flex child do the same?"),
        ("Flexbox", "margin: auto in Flexbox", "How does margin: auto work inside a flex container?", "In a flex container, margin: auto consumes all available empty space in that direction (e.g. margin-left: auto pushes a flex item all the way to the right).", "Intermediate", "Practical", ".nav-login { margin-left: auto; } /* Pushes to right */", "Can margin: auto center both axes on a flex child?"),
        ("Flexbox", "space-between vs space-around vs space-evenly", "What is the difference between space-between, space-around, and space-evenly?", "space-between puts no space at edges. space-around puts half-size space at edges. space-evenly creates equal gaps everywhere including edges.", "Intermediate", "Comparison", ".row { justify-content: space-evenly; }", "Which is newest in CSS specification?"),
        ("Flexbox", "flex-wrap", "What does flex-wrap do in Flexbox?", "By default (nowrap), items stay on a single line and shrink. flex-wrap: wrap allows items to wrap onto multiple lines when space runs out.", "Easy", "Concept", ".grid { display: flex; flex-wrap: wrap; }", "What is flex-wrap: wrap-reverse?"),
        ("Flexbox", "align-content", "What does align-content do and when does it take effect?", "align-content aligns multiple lines of flex items along the cross axis. It only has an effect when flex-wrap: wrap is enabled and multiple lines exist.", "Intermediate", "Concept", ".container { display: flex; flex-wrap: wrap; align-content: space-between; }", "Does align-content work on a single line?"),
        ("Flexbox", "flex-grow", "What does flex-grow do on a flex item?", "flex-grow determines how much of the remaining positive free space in the container an item should absorb (default is 0: do not grow).", "Easy", "Concept", ".main-col { flex-grow: 1; }", "If one item has flex-grow: 2 and another 1, how is space split?"),
        ("Flexbox", "flex-shrink", "What does flex-shrink do on a flex item?", "flex-shrink determines how an item shrinks when there is negative overflow space (default is 1). Setting flex-shrink: 0 prevents an item from shrinking.", "Easy", "Concept", ".sidebar { flex-shrink: 0; width: 250px; }", "Why is flex-shrink: 0 crucial for fixed sidebars?"),
        ("Flexbox", "flex-basis", "What is flex-basis in Flexbox?", "flex-basis defines the default initial size of a flex item before remaining space is distributed according to flex-grow and flex-shrink.", "Easy", "Concept", ".item { flex-basis: 200px; }", "How does flex-basis differ from width?"),
        ("Flexbox", "flex Shorthand", "What does the shorthand flex: 1 1 auto mean?", "In order: flex-grow (1), flex-shrink (1), and flex-basis (auto).", "Easy", "Concept", ".item { flex: 1 1 auto; }", "What does flex: 1 expand to?"),
        ("Flexbox", "flex: 1 vs flex: auto", "What is the difference between flex: 1 and flex: auto?", "flex: 1 sets flex: 1 1 0% (ignores content size, splits space equally). flex: auto sets flex: 1 1 auto (sizes based on content first).", "Intermediate", "Comparison", ".equal-col { flex: 1; }", "Why use flex: 1 for equal-width columns?"),
        ("Flexbox", "order Property", "What does the order property do on a flex item?", "The order property reorders flex items visually without altering their DOM order (default is 0; negative values move earlier).", "Easy", "Practical", ".promoted { order: -1; } /* Moves first */", "Does order affect screen reader navigation?"),
        ("Flexbox", "Accessibility Risk of order", "Why should order not be used carelessly for layout?", "order alters visual display without changing DOM order, creating a disconnect between visual layout and keyboard focus / screen reader order.", "Intermediate", "Accessibility", "", "What WCAG criterion does this relate to?"),
        ("Flexbox", "align-self Property", "What does align-self do on a flex item?", "align-self overrides the parent container's align-items property for that individual flex child.", "Easy", "Practical", ".item { align-self: flex-end; }", "Can align-self accept auto?"),
        ("Flexbox", "gap Property in Flexbox", "How does the gap property work in Flexbox?", "gap defines the empty spacing between flex items without needing margin hacks on child elements (e.g. gap: 16px or row-gap / column-gap).", "Easy", "Practical", ".nav { display: flex; gap: 1rem; }", "Is gap supported in Flexbox across modern browsers?"),
        ("Flexbox", "Flexbox Holy Grail Layout", "How do you build a sticky footer using Flexbox?", "Set body to display: flex; flex-direction: column; min-height: 100vh;, and set the main content area to flex: 1;.", "Easy", "Practical", "body {\n  display: flex;\n  flex-direction: column;\n  min-height: 100vh;\n}\nmain { flex: 1; }", "What happens to footer on short pages?"),
        ("Flexbox", "Flexbox Overflow Bug", "Why do text elements inside flex items sometimes refuse to shrink and break container width?", "Flex items have a default min-width: auto. Add min-width: 0; to the flex item to allow text truncation with text-overflow: ellipsis.", "Intermediate", "Debugging", ".flex-item { min-width: 0; }", "What is the default min-width on flex items?"),
        ("Flexbox", "Text Ellipsis in Flex Item", "How do you truncate overflowing text with an ellipsis inside a flex item?", "Add min-width: 0 on the flex child, and white-space: nowrap; overflow: hidden; text-overflow: ellipsis; on the text element.", "Intermediate", "Practical", ".title {\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n}", "Why does min-width: 0 fix this?"),
        ("Flexbox", "Flexbox MCQ", "Which property aligns flex items along the cross axis?", "Option C is correct. align-items aligns items along the cross axis.", "Easy", "MCQ", "", {"A": "justify-content", "B": "flex-direction", "C": "align-items", "D": "align-content"}, "C", "Which property aligns along the main axis?"),
        ("Flexbox", "Flex Shrink MCQ", "What is the default value of flex-shrink on a flex item?", "Option B is correct. flex-shrink defaults to 1, meaning items will shrink if space is tight.", "Easy", "MCQ", "", {"A": "0", "B": "1", "C": "auto", "D": "none"}, "B", "How do you prevent an item from shrinking?"),
        ("Flexbox", "Flex Direction MCQ", "If flex-direction: column is set, which axis does justify-content control?", "Option A is correct. In column direction, the main axis is vertical.", "Easy", "MCQ", "", {"A": "Vertical (top to bottom)", "B": "Horizontal (left to right)", "C": "Cross axis", "D": "Both axes"}, "A", "What does align-items control in column direction?"),
        ("Flexbox", "baseline Alignment", "What does align-items: baseline do?", "It aligns flex items such that the baselines of their first lines of text align along a shared horizontal line, even if font sizes differ.", "Intermediate", "Concept", ".row { display: flex; align-items: baseline; }", "When is baseline alignment useful?"),
        ("Flexbox", "flex-flow Shorthand", "What does the flex-flow property combine?", "flex-flow combines flex-direction and flex-wrap into a single shorthand declaration (e.g. flex-flow: row wrap;).", "Easy", "Concept", ".grid { display: flex; flex-flow: row wrap; }", "What is the default flex-flow value?"),
        ("Flexbox", "Auto Margins vs Justify Content", "If a flex item has margin-left: auto, does justify-content: center still affect it?", "No. Auto margins consume all available free space first before justify-content alignment is calculated.", "Intermediate", "Concept", "", "Can auto margins be used to push items to opposite sides?"),
        ("Flexbox", "Inline Flexbox", "What is the difference between display: flex and display: inline-flex?", "display: flex creates a block-level flex container. display: inline-flex creates an inline-level flex container that flows inside text.", "Intermediate", "Comparison", ".pill-group { display: inline-flex; }", "Do items inside inline-flex behave the same?"),
        ("Flexbox", "Flex Item Sizing Calculation", "Given 600px container, three items of width 100px with flex-grow: 1, 2, 0. How much space does each get?", "Total width = 300px. Remaining space = 300px. Item 1 gets 100 + 100 = 200px. Item 2 gets 100 + 200 = 300px. Item 3 gets 100px.", "Advanced", "Practical", "", "Why does item 3 get zero extra space?"),
        ("Flexbox", "Nested Flex Containers", "Can a flex item also be a flex container?", "Yes. Setting display: flex on a flex item turns it into a flex container for its own direct children, enabling complex nested layouts.", "Easy", "Practical", ".card { display: flex; }\n.card-body { display: flex; flex-direction: column; }", "Is there any limit to nesting depth?"),
        ("Flexbox", "Responsive Navbar Pattern", "How do you convert a horizontal desktop flex navbar into a stacked mobile menu?", "In a media query, change flex-direction from row to column on the nav container.", "Easy", "Practical", "@media (max-width: 768px) {\n  .nav { flex-direction: column; }\n}", "How do you hide the menu until toggled?"),
        ("Flexbox", "Flexbox vs Floats", "Why did Flexbox completely replace floats for modern component layouts?", "Flexbox handles dynamic vertical alignment, equal-height columns, automatic space distribution, reordering, and wrapping without clearing hacks.", "Easy", "Comparison", "", "Is float still useful for anything?"),
        ("Flexbox", "Flexbox vs Grid Rule of Thumb", "What is the general rule of thumb for choosing between Flexbox and CSS Grid?", "Flexbox is designed for 1-dimensional layouts (a single row OR a single column). CSS Grid is designed for 2-dimensional layouts (rows AND columns simultaneously).", "Easy", "Comparison", "", "Can you use Flexbox inside a Grid item?")
    ]
    for item in flexbox:
        top, subtop, q_text, ans, diff, qtype, code, *rest = item
        mcq_opts, correct_opt, fup = None, None, ""
        if len(rest) == 1:
            fup = rest[0]
        elif len(rest) == 3:
            mcq_opts, correct_opt, fup = rest

        qs.append(make_q(
            f"q-css-{num}", num, "CSS", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 5. CSS Grid Layout (30 Qs)
    grid_items = [
        ("CSS Grid", "display: grid", "What is CSS Grid Layout?", "CSS Grid is a two-dimensional layout system that allows dividing a page into rows and columns simultaneously with precise placement.", "Easy", "Concept", ".grid { display: grid; }", "How does it differ from Flexbox?"),
        ("CSS Grid", "grid-template-columns", "How do you define a 3-column layout in CSS Grid?", "Use grid-template-columns: 1fr 1fr 1fr; or grid-template-columns: repeat(3, 1fr);.", "Easy", "Practical", ".container { display: grid; grid-template-columns: repeat(3, 1fr); }", "What does fr stand for?"),
        ("CSS Grid", "The fr Unit", "What is the 'fr' (fractional) unit in CSS Grid?", "The fr unit represents a fraction of the available free space in the grid container after fixed dimensions are subtracted.", "Easy", "Concept", "grid-template-columns: 200px 1fr 2fr;", "How is space split between 1fr and 2fr?"),
        ("CSS Grid", "repeat() Function", "What does repeat(4, 1fr) do in CSS Grid?", "It repeats the column definition 4 times, equivalent to writing 1fr 1fr 1fr 1fr.", "Easy", "Practical", "grid-template-columns: repeat(4, 1fr);", "Can repeat() take multiple column patterns?"),
        ("CSS Grid", "gap Property in Grid", "How do you specify row and column spacing in CSS Grid?", "Use the gap property (e.g. gap: 20px; or row-gap: 10px; column-gap: 20px;).", "Easy", "Practical", ".grid { display: grid; gap: 16px; }", "Does gap add space to the outer edges of the grid?"),
        ("CSS Grid", "auto-fit vs auto-fill", "What is the difference between auto-fit and auto-fill in CSS Grid?", "auto-fill creates empty ghost column tracks to fill the row. auto-fit collapses empty tracks to 0, stretching filled items to take the full width.", "Intermediate", "Comparison", "grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));", "Which is preferred for responsive card grids?"),
        ("CSS Grid", "Responsive Grid without Media Queries", "How do you create an auto-wrapping responsive grid without media queries?", "Use grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); with gap.", "Intermediate", "Practical", ".cards {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 1.5rem;\n}", "How does minmax work here?"),
        ("CSS Grid", "minmax() Function", "What does minmax(min, max) do in CSS Grid?", "minmax() sets a size range for a grid track that cannot be smaller than min and cannot be larger than max.", "Easy", "Practical", "grid-template-columns: minmax(150px, 1fr) 2fr;", "Can max be set to max-content?"),
        ("CSS Grid", "grid-column / grid-row", "How do you make a grid item span 2 columns?", "Use grid-column: span 2; or grid-column: 1 / 3;.", "Easy", "Practical", ".featured { grid-column: span 2; }", "What is the starting line index in CSS Grid?"),
        ("CSS Grid", "Grid Lines Numbering", "How are grid lines numbered in CSS Grid?", "Grid lines start at 1 on the outer edge (1, 2, 3...). Negative line numbers count backwards from the end (-1 is the last edge line).", "Intermediate", "Concept", "grid-column: 1 / -1; /* Spans full width */", "What does grid-column: 1 / -1 do?"),
        ("CSS Grid", "grid-template-areas", "What is grid-template-areas in CSS Grid?", "A visual syntax defining named grid regions using strings (e.g. 'header header' 'sidebar main' 'footer footer'). Items assign themselves via grid-area.", "Intermediate", "Practical", ".layout {\n  display: grid;\n  grid-template-areas:\n    \"header header\"\n    \"sidebar main\"\n    \"footer footer\";\n}\nheader { grid-area: header; }", "How do you leave an empty cell in grid-template-areas?"),
        ("CSS Grid", "Empty Cell in grid-template-areas", "How do you represent an empty cell in grid-template-areas?", "Use a period (.) to represent an unnamed empty cell: 'header .' 'main main'.", "Intermediate", "Practical", "grid-template-areas: \"header .\" \"main aside\";", "Can you use multiple periods?"),
        ("CSS Grid", "Implicit vs Explicit Grid", "What is the difference between explicit and implicit grid tracks?", "Explicit tracks are defined by grid-template-columns/rows. Implicit tracks are created automatically by the browser when items overflow the defined grid.", "Advanced", "Concept", "", "What property styles implicit grid rows?"),
        ("CSS Grid", "grid-auto-rows and grid-auto-columns", "What do grid-auto-rows and grid-auto-columns do?", "They define the size of automatically created implicit grid tracks when more items exist than defined in the template.", "Intermediate", "Practical", ".grid { grid-auto-rows: 200px; }", "What is the default size of implicit rows?"),
        ("CSS Grid", "grid-auto-flow", "What does grid-auto-flow do?", "It controls how auto-placed items are inserted into the grid: row (fills rows first; default), column (fills columns), or dense (packs empty holes).", "Intermediate", "Concept", ".grid { grid-auto-flow: dense; }", "When is grid-auto-flow: dense useful?"),
        ("CSS Grid", "justify-items vs align-items in Grid", "What do justify-items and align-items do in CSS Grid?", "justify-items aligns grid items horizontally within their grid cell. align-items aligns grid items vertically within their cell.", "Easy", "Concept", ".grid { justify-items: center; align-items: center; }", "What is the default value of both?"),
        ("CSS Grid", "justify-content vs align-content in Grid", "What do justify-content and align-content do in CSS Grid?", "They align the entire grid structure itself inside the grid container when total track sizes are smaller than the container.", "Intermediate", "Concept", ".grid { justify-content: center; }", "When is total grid smaller than container?"),
        ("CSS Grid", "justify-self and align-self in Grid", "What do justify-self and align-self do on a grid item?", "They override the container's justify-items and align-items for that individual specific grid item.", "Easy", "Practical", ".item { justify-self: end; }", "Can flex items use justify-self?"),
        ("CSS Grid", "Centering in CSS Grid", "What is the shortest one-liner to center an element in CSS Grid?", "display: grid; place-items: center;.", "Easy", "Practical", ".parent { display: grid; place-items: center; min-height: 100vh; }", "What shorthand is place-items?"),
        ("CSS Grid", "subgrid Property", "What is CSS Subgrid and why is it useful?", "subgrid allows a nested child grid to adopt and align directly to the row and column tracks of its parent grid.", "Advanced", "Concept", ".child-grid { display: grid; grid-template-columns: subgrid; }", "What problem does subgrid solve in card layouts?"),
        ("CSS Grid", "Grid MCQ", "Which unit represents a fraction of the available free space in CSS Grid?", "Option B is correct. fr stands for fractional unit.", "Easy", "MCQ", "", {"A": "%", "B": "fr", "C": "vh", "D": "em"}, "B", "Can fr be mixed with px?"),
        ("CSS Grid", "Line Index MCQ", "What line number represents the very last right-hand grid line in CSS Grid?", "Option D is correct. -1 represents the trailing edge line.", "Intermediate", "MCQ", "", {"A": "0", "B": "100%", "C": "last", "D": "-1"}, "D", "What does grid-column: 1 / -1 accomplish?"),
        ("CSS Grid", "Dense Packing", "What does grid-auto-flow: row dense do in an image gallery?", "It attempts to back-fill earlier empty layout holes if smaller items appear later in the DOM, creating a gap-free visual mosaic.", "Intermediate", "Practical", ".gallery { display: grid; grid-auto-flow: dense; }", "Does this change DOM order?"),
        ("CSS Grid", "min-content vs max-content", "What is the difference between min-content and max-content keywords?", "min-content is the smallest intrinsic size without overflowing (wrapping at every word). max-content is the intrinsic size with no wrapping at all.", "Intermediate", "Comparison", "grid-template-columns: min-content 1fr;", "When is min-content useful?"),
        ("CSS Grid", "fit-content() Function", "What does fit-content(maxSize) do?", "It clamps track size to max-content while ensuring it does not exceed the provided maxSize argument.", "Intermediate", "Practical", "grid-template-columns: fit-content(300px) 1fr;", "How does fit-content differ from minmax?"),
        ("CSS Grid", "Overlaying Elements in Grid", "How do you stack two elements on top of each other using CSS Grid without absolute positioning?", "Assign both elements to the exact same grid-column and grid-row coordinates.", "Intermediate", "Practical", ".bg, .hero-content {\n  grid-column: 1;\n  grid-row: 1;\n}", "How do you control which one sits on top?"),
        ("CSS Grid", "Named Grid Lines", "How do you define named grid lines in grid-template-columns?", "Enclose line names in square brackets: grid-template-columns: [main-start] 1fr [main-end] 300px [sidebar-end];.", "Advanced", "Practical", "grid-template-columns: [col-start] 1fr [col-end];", "How do you reference named lines?"),
        ("CSS Grid", "Full Bleed Layout with Grid", "What is the full bleed pattern in CSS Grid?", "A 3-column layout where standard content sits in the center track, but breakout images/headers span 1 / -1 across full screen edges.", "Advanced", "Practical", ".content-grid {\n  display: grid;\n  grid-template-columns: 1fr min(65ch, 100%) 1fr;\n}", "What does 65ch represent?"),
        ("CSS Grid", "Grid Performance", "Does CSS Grid cause performance issues for thousands of items?", "Yes. Calculating two-dimensional track constraints for very large numbers of DOM nodes is computationally heavier than Flexbox.", "Advanced", "Performance", "", "What technique handles thousands of list items?"),
        ("CSS Grid", "Grid vs Flexbox Summary", "When should you prefer CSS Grid over Flexbox?", "Use Grid when you need control over rows AND columns together (galleries, dashboards, page layouts). Use Flexbox for linear alignment in 1 direction.", "Easy", "Comparison", "", "Can both be used on the same page?")
    ]
    for item in grid_items:
        top, subtop, q_text, ans, diff, qtype, code, *rest = item
        mcq_opts, correct_opt, fup = None, None, ""
        if len(rest) == 1:
            fup = rest[0]
        elif len(rest) == 3:
            mcq_opts, correct_opt, fup = rest

        qs.append(make_q(
            f"q-css-{num}", num, "CSS", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 6. Responsive Design, Units, Typography & Animations (50 Qs)
    responsive_anim = [
        ("Responsive Design", "Mobile-First Design", "What is mobile-first responsive web design?", "Designing styles for the smallest mobile screen first, then using min-width media queries to progressively enhance layouts for larger screens.", "Easy", "Concept", "/* Mobile styles first */\n@media (min-width: 768px) { /* Tablet/Desktop */ }", "Why is mobile-first preferred over desktop-first?"),
        ("Responsive Design", "Media Query Syntax", "What is the standard syntax for a media query targeting screens wider than 768px?", "@media (min-width: 768px) { ... }.", "Easy", "Practical", "@media (min-width: 768px) {\n  .sidebar { display: block; }\n}", "What is the difference between min-width and max-width?"),
        ("Responsive Design", "Common Breakpoints", "What are common industry device breakpoints?", "Mobile: < 640px. Tablet: 641px - 1024px. Desktop: 1025px - 1280px. Large screens: > 1280px.", "Easy", "Concept", "", "Should breakpoints be based on specific devices or content?"),
        ("Responsive Design", "Modern Range Syntax", "What is the modern CSS range media query syntax?", "Modern CSS allows comparison operators: @media (width >= 768px) and @media (600px <= width <= 900px).", "Intermediate", "Practical", "@media (width >= 768px) { ... }", "Is range syntax supported in modern browsers?"),
        ("Responsive Design", "Orientation Media Feature", "How do you detect landscape orientation in a media query?", "Use @media (orientation: landscape) or @media (orientation: portrait).", "Easy", "Practical", "@media (orientation: landscape) { .header { height: 40px; } }", "How does orientation relate to aspect-ratio?"),
        ("Responsive Design", "prefers-color-scheme", "How do you support system dark mode in pure CSS?", "Use the @media (prefers-color-scheme: dark) media query to adjust background and text colors.", "Easy", "Practical", "@media (prefers-color-scheme: dark) {\n  body { background: #090d13; color: #f0f6fc; }\n}", "How does this interact with manual theme toggles?"),
        ("Units", "px vs rem vs em", "What is the difference between px, rem, and em units?", "px is an absolute fixed pixel value. rem is relative to the root <html> font-size. em is relative to its immediate parent font-size.", "Easy", "Comparison", "html { font-size: 16px; }\n.box { font-size: 1.5rem; /* 24px */ }", "Why is rem preferred for accessible typography?"),
        ("Units", "Why rem for Accessibility", "Why is using rem for font-size better for accessibility than px?", "If a visually impaired user increases their browser default font size (e.g. from 16px to 24px), rem scales up proportionally. px remains locked and small.", "Intermediate", "Accessibility", "", "What is 1rem if browser default is 16px?"),
        ("Units", "vh and vw Units", "What do 100vw and 100vh represent?", "100vw equals 100% of the viewport width. 100vh equals 100% of the viewport height.", "Easy", "Concept", ".hero { height: 100vh; width: 100vw; }", "What mobile bug occurs with 100vh?"),
        ("Units", "dvh, svh, and lvh", "Why were dvh, svh, and lvh introduced in modern CSS?", "On mobile browsers, 100vh doesn't account for disappearing address bars. dvh (dynamic vh) adjusts in real-time as address bars show/hide.", "Intermediate", "Concept", ".full-screen { height: 100dvh; }", "What do svh and lvh stand for?"),
        ("Units", "% Unit", "What is the % (percentage) unit relative to in CSS?", "Percentage is relative to the dimension of its parent containing block (e.g. width: 50% takes half parent width).", "Easy", "Concept", ".col { width: 50%; }", "What is percentage height relative to?"),
        ("Units", "ch and ex Units", "What do the ch and ex units represent in CSS?", "1ch is the width of the '0' character in the current font. 1ex is the x-height of lowercase 'x'.", "Intermediate", "Typography", "p { max-width: 65ch; } /* Optimal line length */", "Why is 65ch considered optimal for readability?"),
        ("Typography", "line-height", "Why is unitless line-height (e.g. line-height: 1.5) better than pixel line-height?", "Unitless line-height scales dynamically with font-size changes on child elements. Fixed pixel line-heights cause overlapping text.", "Intermediate", "Typography", "body { line-height: 1.5; /* Preferred */ }", "What is a comfortable body line-height?"),
        ("Typography", "font-family Stack", "What is a font stack in CSS?", "A comma-separated list of fallback fonts: font-family: 'Inter', system-ui, sans-serif;. The browser uses the first font installed on the system.", "Easy", "Practical", "font-family: 'Inter', system-ui, -apple-system, sans-serif;", "Why end with a generic font family?"),
        ("Typography", "font-display: swap", "What does font-display: swap do in @font-face?", "It displays fallback system text immediately while custom web fonts download, swapping to the custom font once loaded to prevent invisible text.", "Intermediate", "Performance", "@font-face {\n  font-family: 'MyFont';\n  src: url('font.woff2');\n  font-display: swap;\n}", "What is FOIT vs FOUT?"),
        ("Typography", "word-break vs overflow-wrap", "How do you prevent long URLs or unbroken strings from breaking page layout?", "Use overflow-wrap: break-word; or word-break: break-all;.", "Intermediate", "Practical", "p { overflow-wrap: break-word; }", "Which is more standard: overflow-wrap or word-wrap?"),
        ("Transitions", "transition Shorthand", "What are the four components of the transition shorthand property?", "In order: Property (e.g. background-color), Duration (0.3s), Timing function (ease-in-out), and Delay (0s).", "Easy", "Practical", "button { transition: background-color 0.2s ease, transform 0.1s; }", "Why should you avoid transition: all?"),
        ("Transitions", "Why avoid transition: all", "Why is transition: all considered bad practice in production CSS?", "It forces the browser to monitor and animate every single changing property, causing severe performance drops and unintended transition glitches.", "Intermediate", "Performance", "", "What should you specify instead?"),
        ("Transitions", "cubic-bezier() Timing Function", "What is cubic-bezier(p1, p2, p3, p4) in CSS transitions?", "A mathematical Bézier curve defining custom acceleration curves, allowing bouncy or custom acceleration effects.", "Advanced", "Concept", "transition: transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);", "What do the 4 values represent?"),
        ("Transforms", "2D Transforms", "What does the transform property do in CSS?", "transform modifies the visual coordinate space of an element using functions: translate(), rotate(), scale(), and skew().", "Easy", "Concept", ".box:hover { transform: translateY(-4px) scale(1.02); }", "Does transform affect surrounding document flow?"),
        ("Transforms", "transform-origin", "What does transform-origin do in CSS?", "transform-origin sets the anchor point around which rotations and scale transforms occur (default is center 50% 50%).", "Intermediate", "Practical", ".pin { transform-origin: top left; transform: rotate(45deg); }", "Can transform-origin take pixel values?"),
        ("Animations", "@keyframes Syntax", "How do you define a CSS animation using @keyframes?", "Define the keyframe sequence with percentages (0%, 50%, 100%) or 'from' and 'to', then assign via animation property.", "Easy", "Practical", "@keyframes spin {\n  from { transform: rotate(0deg); }\n  to { transform: rotate(360deg); }\n}\n.loader { animation: spin 1s linear infinite; }", "What does infinite mean in animation?"),
        ("Animations", "animation-fill-mode", "What does animation-fill-mode: forwards do?", "It keeps the final styles applied by the last keyframe on the element after the animation finishes playing.", "Intermediate", "Practical", ".fade-in { animation: fadeIn 0.5s ease forwards; }", "What does animation-fill-mode: backwards do?"),
        ("Animations", "animation-play-state", "How do you pause a running CSS animation on hover?", "Set animation-play-state: paused; on the hover selector.", "Easy", "Practical", ".banner:hover { animation-play-state: paused; }", "What is the other value of animation-play-state?"),
        ("CSS Variables", "Declaring Custom Properties", "How do you declare and access a CSS Custom Property (Variable)?", "Declare with double dashes (--primary-color: #0284c7) and access with var(--primary-color).", "Easy", "Practical", ":root { --brand: #38bdf8; }\n.btn { background: var(--brand); }", "Can CSS variables have fallback values?"),
        ("CSS Variables", "Fallback in var()", "How do you provide a fallback value if a CSS variable is undefined?", "Pass the fallback as the second parameter: var(--custom-color, #1e293b).", "Easy", "Practical", "color: var(--text-color, #333333);", "Can a fallback be another var()?"),
        ("CSS Variables", "Scoping of Variables", "How does scoping work with CSS Variables?", "CSS variables follow normal inheritance and cascade: a variable declared on a class overrides the :root variable for that component and all its children.", "Intermediate", "Concept", ".theme-light { --bg: #fff; }\n.theme-dark { --bg: #000; }", "Can JavaScript update CSS variables dynamically?"),
        ("CSS Variables", "Updating CSS Variables via JS", "How do you update a CSS variable dynamically using JavaScript?", "document.documentElement.style.setProperty('--brand-color', '#3b82f6');.", "Easy", "Practical", "document.documentElement.style.setProperty('--theme', 'dark');", "Does updating a root variable trigger a repaint across all consumers?"),
        ("CSS Variables", "CSS Variables vs SASS Variables", "What is the major advantage of CSS custom properties over SASS ($variable)?", "CSS variables are live in the browser DOM, dynamically updatable in real time via JavaScript and media queries, and inherit through elements. SASS variables are compile-time constants.", "Intermediate", "Comparison", "", "Can SASS variables change on screen resize without compiling?"),
        ("Modern CSS", "CSS Nesting", "What is native CSS nesting and how is the '&' used?", "Modern CSS allows nesting child rules inside parent rules directly. '&' references the parent selector.", "Intermediate", "Practical", ".card {\n  background: white;\n  &:hover { background: #f8fafc; }\n  & .title { color: #0f172a; }\n}", "Is preprocessor nesting still required?"),
        ("Modern CSS", "Color Functions", "What is the advantage of hsl() and modern oklch() color formats in CSS?", "hsl and oklch represent colors intuitively (Hue, Saturation, Lightness / Perceptual Chroma). oklch ensures uniform perceived brightness across all hues.", "Intermediate", "Concept", "background: oklch(0.6 0.25 140);", "Why is rgb harder to manipulate programmatically?"),
        ("Modern CSS", "color-mix() Function", "What does color-mix(in srgb, red 40%, blue) do?", "It dynamically mixes two colors together in the specified color space in pure CSS without preprocessors.", "Advanced", "Practical", "background: color-mix(in srgb, var(--brand) 20%, transparent);", "How does this simplify alpha transparency?"),
        ("Modern CSS", "accent-color Property", "What does the accent-color property do on native form inputs?", "accent-color customizes the tint color of native checkboxes, radio buttons, range sliders, and progress bars with a single line.", "Easy", "Practical", ":root { accent-color: #38bdf8; }", "Does accent-color work on normal buttons?"),
        ("Modern CSS", "scrollbar-width and scrollbar-color", "How do you style scrollbars in modern standard CSS?", "Use scrollbar-width (auto, thin, none) and scrollbar-color (thumb-color track-color).", "Intermediate", "Practical", "html { scrollbar-width: thin; scrollbar-color: #555 #111; }", "What was the legacy WebKit scrollbar syntax?"),
        ("Modern CSS", "Responsive MCQ", "Which unit scales with user font settings in browser preferences?", "Option A is correct. rem scales relative to root font size.", "Easy", "MCQ", "", {"A": "rem", "B": "px", "C": "vh", "D": "pt"}, "A", "What does em scale with?"),
        ("Modern CSS", "Animation MCQ", "Which property keeps the final frame styles after a CSS animation finishes?", "Option B is correct. animation-fill-mode: forwards keeps end styles.", "Easy", "MCQ", "", {"A": "animation-iteration-count: infinite", "B": "animation-fill-mode: forwards", "C": "animation-direction: alternate", "D": "animation-play-state: running"}, "B", "What does backwards do?"),
        ("Modern CSS", "Variable MCQ", "What prefix is mandatory when declaring a CSS custom property?", "Option C is correct. Two dashes (--) are required.", "Easy", "MCQ", "", {"A": "$", "B": "@", "C": "--", "D": "#"}, "C", "How do you read the property in CSS?"),
        ("Modern CSS", "Viewport MCQ", "Which viewport unit adjusts in real-time on mobile as URL address bars collapse?", "Option D is correct. dvh (Dynamic Viewport Height) updates dynamically.", "Intermediate", "MCQ", "", {"A": "vh", "B": "lvh", "C": "svh", "D": "dvh"}, "D", "What does svh stand for?"),
        ("CSS Debugging", "CSS Outline for Layout Debugging", "Why is outline: 1px solid red preferred over border: 1px solid red for debugging overflowing elements?", "outlines do not take up layout space or alter element dimensions, so debugging lines won't accidentally cause new layout wrapping.", "Easy", "Debugging", "* { outline: 1px solid red !important; }", "What tool highlights layout shifts automatically?"),
        ("CSS Debugging", "Horizontal Scrollbar Bug", "What is the most common cause of an unwanted horizontal scrollbar on mobile websites?", "An element with fixed width (width: 500px), unconstrained images, or negative margins extending wider than the 100vw viewport.", "Easy", "Debugging", "img { max-width: 100%; }\nbody { overflow-x: hidden; }", "How do you find which element overflows using DevTools?"),
        ("CSS Debugging", "Finding Overflow Element via Console", "How do you find the exact element causing horizontal overflow via the browser console?", "Run: document.querySelectorAll('*').forEach(el => { if (el.offsetWidth > document.documentElement.offsetWidth) console.log(el); });.", "Intermediate", "Debugging", "document.querySelectorAll('*').forEach(el => {\n  if (el.offsetWidth > document.documentElement.offsetWidth) console.log(el);\n});", "What does offsetWidth measure?"),
        ("CSS Debugging", "Specificity Battle Bug", "Why did a style rule written later in the CSS file fail to apply over an earlier rule?", "Because the earlier rule had higher specificity (e.g. #id vs .class). Source order only matters when specificity is exactly equal.", "Intermediate", "Debugging", "", "How does DevTools show overwritten styles?"),
        ("CSS Debugging", "Broken Flex Child Sizing", "Why does an image inside a flex container stretch and distort when flex-direction is row?", "Because align-items: stretch is the default. Add align-self: flex-start or height: auto to preserve natural aspect ratio.", "Easy", "Debugging", "img { align-self: center; height: auto; }", "What does object-fit do to prevent distortion?"),
        ("CSS Debugging", "Collapsing Height with Position Absolute", "Why did a parent container collapse to 0 height after adding position: absolute to its children?", "Absolute elements are removed from normal document flow. The parent no longer sees any in-flow height from absolute children.", "Easy", "Debugging", "", "How do you give the parent height?"),
        ("CSS Debugging", "Missing Background Image", "What is the common reason url('bg.jpg') fails when moved into a /css/ subfolder?", "Relative URLs in CSS files are resolved relative to the CSS file location, not the HTML page location (use url('../images/bg.jpg')).", "Easy", "Debugging", "background-image: url('../images/bg.jpg');", "How are relative URLs in HTML resolved?"),
        ("CSS Debugging", "CSS Minification", "What is CSS minification and why is it essential for production?", "Minification strips whitespace, comments, and shortens color codes, reducing file transfer size for faster page load times.", "Easy", "Practical", "/* Unminified: 50KB -> Minified: 15KB */", "Does minification change code logic?"),
        ("CSS Debugging", "Critical CSS", "What is Critical CSS in web performance optimization?", "Inlining the minimal CSS required to render the above-the-fold viewport content directly inside the <style> tag of <head>.", "Advanced", "Performance", "", "How is the rest of the CSS loaded?"),
        ("CSS Debugging", "BEM Methodology", "What is the BEM (Block, Element, Modifier) naming methodology in CSS?", "A modular naming convention: .block__element--modifier (e.g. .card__button--disabled) that prevents specificity conflicts and promotes maintainability.", "Intermediate", "Concept", ".card__title--highlighted { font-size: 1.25rem; }", "What do the double underscore and double hyphen mean?"),
        ("CSS Debugging", "CSS Reset vs Normalize", "What is the difference between a CSS Reset and Normalize.css?", "A CSS Reset strips all default browser styling completely (0 margin, 0 padding). Normalize.css preserves useful defaults and fixes cross-browser inconsistencies.", "Easy", "Comparison", "", "Which is more common in modern frameworks?")
    ]
    for item in responsive_anim:
        top, subtop, q_text, ans, diff, qtype, code, *rest = item
        mcq_opts, correct_opt, fup = None, None, ""
        if len(rest) == 1:
            fup = rest[0]
        elif len(rest) == 3:
            mcq_opts, correct_opt, fup = rest

        qs.append(make_q(
            f"q-css-{num}", num, "CSS", top, subtop,
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    print(f"Built CSS pack: {len(qs)} questions (Target: >=200)")
    return qs
