"""
bank_builders/pack_es6.py
Generates 215+ questions for ES6+ covering let/const, arrow functions, template literals, destructuring, spread/rest, enhanced objects, modules, classes, Map/Set, Symbol, Iterators/Generators, Optional Chaining, Nullish Coalescing, and modern methods.
"""

from .common import make_q, parse_item

def build_es6_pack(start_num=1):
    qs = []
    num = start_num

    # 1. Variables & Scoping (let, const, TDZ) - 25 Qs
    v_items = [
        ("What major scoping improvements did ES6 introduce over ES5?", "ES6 introduced block-scoped variable declarations using 'let' and 'const', avoiding the function-scoped pitfalls of 'var'.", "Easy", "Concept", "let a = 1;\nconst b = 2;", "Can a block-scoped variable leak out of an if block?"),
        ("What is the Temporal Dead Zone (TDZ) in ES6?", "The TDZ is the zone between the start of a block and the declaration line where accessing a let or const variable throws a ReferenceError.", "Intermediate", "Concept", "{ // TDZ starts\n  // console.log(x); // ReferenceError\n  let x = 10; // TDZ ends\n}", "Does typeof avoid ReferenceError in TDZ?"),
        ("Why does typeof throw ReferenceError on a let variable in the TDZ?", "In ES6, the TDZ was deliberately specified to throw on ANY access (including typeof) to enforce declaring before using.", "Intermediate", "Concept", "typeof myVar; // ReferenceError in TDZ", "How does this differ from undeclared variables?"),
        ("What is the difference between const and Object.freeze()?", "const prevents re-assigning the variable identifier to another reference. Object.freeze() prevents mutating the properties of the object itself.", "Easy", "Comparison", "const user = { name: 'A' };\nuser.name = 'B'; // Allowed\nObject.freeze(user);\nuser.name = 'C'; // Fails silently or throws in strict mode", "Can you reassign a const variable?"),
        ("Why does declaring variables with const make code safer and more readable?", "It signals to developers and the JS engine that the variable binding will never be reassigned, eliminating accidental reassignments.", "Easy", "Concept", "", "When should you use let instead of const?"),
        ("When should you choose 'let' over 'const'?", "Use 'let' only when you know the variable identifier must be reassigned (e.g. loop counters, accumulators, toggle states).", "Easy", "Practical", "let count = 0;\ncount++;", "Does let allow redeclaration in the same scope?"),
        ("Can you redeclare a variable in the same scope using 'let' or 'const'?", "No. Redeclaring with let or const in the same scope throws a SyntaxError: Identifier has already been declared.", "Easy", "Concept", "let x = 1;\nlet x = 2; // SyntaxError", "Does var allow redeclaration?"),
        ("What happens when var x = 1; is declared inside an if block?", "Because var is not block-scoped, x leaks into the enclosing function or global scope.", "Easy", "Concept", "if (true) { var x = 5; }\nconsole.log(x); // 5", "How does let prevent this leak?"),
        ("What is the behavior of 'let' inside a for loop header: for (let i = 0; i < 3; i++)?", "Each iteration receives a new lexical binding for 'i', so closures created inside the loop capture the correct iteration value.", "Intermediate", "Concept", "for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0); // 0, 1, 2\n}", "What would var print instead?"),
        ("Does const work in the header of a for...of loop?", "Yes. In for...of and for...in loops, a new binding is created on each iteration, so const is valid and recommended.", "Intermediate", "Practical", "for (const item of ['a', 'b']) {\n  console.log(item);\n}", "Can const be used in a standard for(;;) loop?"),
        ("Why does for (const i = 0; i < 3; i++) throw TypeError?", "The loop step expression i++ attempts to reassign the const variable 'i' after the first iteration, throwing TypeError.", "Easy", "Debugging", "for (const i = 0; i < 3; i++) {} // TypeError: Assignment to constant variable", "What should be used instead?"),
        ("Are global let and const variables added to the window object in browsers?", "No. Global let and const declarations are stored in the global declarative environment record, not as properties on window.", "Intermediate", "Concept", "let a = 10;\nconsole.log(window.a); // undefined\nvar b = 20;\nconsole.log(window.b); // 20", "Why is not polluting window advantageous?"),
        ("Scoping MCQ: Which statement about let and const is FALSE?", "Option D is correct. let and const are NOT added as properties to the global window object.", "Easy", "MCQ", "", {"A": "They are block-scoped", "B": "They cannot be redeclared in same scope", "C": "They have a Temporal Dead Zone", "D": "They attach to the window object"}, "D", "What keyword DOES attach to window?"),
        ("Scoping MCQ: What error occurs on: const user = { id: 1 }; user = { id: 2 };?", "Option A is correct. Reassigning a const variable throws TypeError: Assignment to constant variable.", "Easy", "MCQ", "", {"A": "TypeError", "B": "ReferenceError", "C": "SyntaxError", "D": "NoError"}, "A", "Is user.id = 2 permitted?"),
        ("Scoping Output: What is logged: let x = 1; { console.log(x); let x = 2; }?", "Output: ReferenceError: Cannot access 'x' before initialization. The inner block shadows outer x, trapping execution in TDZ.", "Intermediate", "Output", "let x = 1;\n{\n  console.log(x); // ReferenceError\n  let x = 2;\n}", "Why does it not read outer x?"),
        ("Scoping Debugging: How do you fix: let a = 1; var a = 2;?", "SyntaxError: Identifier 'a' has already been declared. Remove the redundant declaration or choose a unique variable name.", "Easy", "Debugging", "let a = 1;\n// Remove: var a = 2;", "Can var and let share names in same scope?"),
        ("Can a let variable shadow a var variable in an inner block?", "Yes, inner blocks can shadow outer variables regardless of whether they were declared with var or let.", "Intermediate", "Concept", "var x = 10;\nif (true) {\n  let x = 20; // Valid shadowing\n}", "What about the reverse: var shadowing let in a block?"),
        ("Why is declaring var x inside a block illegal if let x exists in outer function scope?", "SyntaxError: Identifier 'x' has already been declared. var hoists to function scope, colliding with the outer let.", "Intermediate", "Concept", "", "How does the JS engine detect this?"),
        ("What is the scope of a function declared inside a block in ES6 strict mode?", "In ES6 strict mode, function declarations inside blocks are block-scoped to that enclosing block.", "Intermediate", "Concept", "'use strict';\n{\n  function hello() { return 'hi'; }\n}\n// hello(); // ReferenceError", "How did ES5 handle block functions?"),
        ("What happens if you declare a variable without let, const, or var in ES6 strict mode?", "It throws a ReferenceError: variable is not defined, preventing accidental global creation.", "Easy", "Concept", "'use strict';\nscore = 100; // ReferenceError", "What happened in non-strict mode?"),
        ("What does the global object property globalThis do in modern ES?", "globalThis provides a standard, platform-agnostic way to access the global object in browsers (window), Node.js (global), or Web Workers (self).", "Easy", "Concept", "console.log(globalThis.Math === Math); // true", "Why was this needed?"),
        ("Scoping MCQ: What does (function() { let a = b = 5; })(); console.log(typeof a, typeof b); output?", "Option C is correct. 'undefined' 'number'. b = 5 assigns to global b, while 'let a' is scoped to the function.", "Intermediate", "MCQ", "", {"A": "'number' 'number'", "B": "'undefined' 'undefined'", "C": "'undefined' 'number'", "D": "ReferenceError"}, "C", "Why did b leak globally?"),
        ("Scoping Coding: Write a block-scoped loop that logs 0, 1, 2 with 100ms intervals using let.", "for (let i = 0; i < 3; i++) { setTimeout(() => console.log(i), 100); }", "Easy", "Coding", "for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100);\n}", "Why does each callback get the right 'i'?"),
        ("What is the dead zone lifetime?", "From the moment the scope is entered until the variable declaration statement is reached and evaluated.", "Easy", "Concept", "", "Does function hoisting experience TDZ?"),
        ("Do function declarations experience Temporal Dead Zone?", "No. Standard function declarations are hoisted along with their complete function definition, so they are callable anywhere in scope.", "Easy", "Concept", "greet(); // Works!\nfunction greet() {}", "What about function expressions?")
    ]
    for item in v_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Variables & Scoping", "let, const & TDZ",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 2. Arrow Functions & Template Literals - 25 Qs
    af_items = [
        ("What is the syntax of an ES6 arrow function?", "const fn = (param1, param2) => expression; or with a block body: const fn = () => { return val; };.", "Easy", "Concept", "const add = (a, b) => a + b;", "When can parentheses around parameters be omitted?"),
        ("When can parentheses around arrow function parameters be omitted?", "Parentheses can be omitted ONLY when there is exactly ONE parameter: const square = x => x * x;.", "Easy", "Concept", "const double = n => n * 2;", "Can parentheses be omitted with 0 parameters?"),
        ("How do you return an object literal from a concise body arrow function?", "Wrap the object literal in parentheses: const makeObj = () => ({ id: 1 });. Otherwise {} is parsed as a function body.", "Easy", "Practical", "const getUser = id => ({ id, role: 'user' });", "What happens if parentheses are omitted?"),
        ("What happens if you write: const fn = () => { id: 1 }; without parentheses?", "The curly braces are interpreted as a block body and 'id:' is interpreted as a label, returning undefined.", "Intermediate", "Debugging", "const fn = () => { id: 1 };\nfn(); // undefined", "How do you fix it?"),
        ("What are the 4 major differences between arrow functions and regular functions?", "Arrow functions: 1. No own 'this' (lexical). 2. No 'arguments' object. 3. Cannot be used with 'new' (no constructor). 4. No 'prototype' property.", "Intermediate", "Comparison", "", "Can arrow functions be methods on objects?"),
        ("Why should arrow functions NOT be used as object methods?", "Arrow functions inherit 'this' from the outer lexical scope (usually window or module), rather than the object on which the method is called.", "Intermediate", "Scenario", "const user = {\n  name: 'Sam',\n  greet: () => console.log(this.name) // undefined!\n};", "How should object methods be written in ES6?"),
        ("How should object methods be written in ES6?", "Use ES6 concise method syntax: const user = { name: 'Sam', greet() { console.log(this.name); } };.", "Easy", "Practical", "const user = {\n  name: 'Sam',\n  greet() {\n    console.log(this.name); // 'Sam'\n  }\n};", "Does concise method syntax bind 'this' to the object?"),
        ("What happens if you attempt to call 'new' on an arrow function: new (() => {})()?", "It throws a TypeError: ... is not a constructor, because arrow functions lack a [[Construct]] internal method and prototype.", "Intermediate", "Concept", "const Fn = () => {};\nnew Fn(); // TypeError", "Do arrow functions have a .prototype property?"),
        ("What is the value of ArrowFunction.prototype?", "undefined. Arrow functions do not have a prototype property.", "Easy", "Concept", "const f = () => {};\nconsole.log(f.prototype); // undefined", "What does a regular function prototype have?"),
        ("What are template literals in ES6?", "Template literals use backticks (`) and support string interpolation with ${expression} and multi-line strings without escape characters.", "Easy", "Concept", "const greeting = `Hello ${name}, welcome!`;", "Can multi-line strings be written without \\n?"),
        ("How do template literals simplify multi-line strings?", "Newlines inside backticks are preserved verbatim in the resulting string without needing + '\\n' concatenation.", "Easy", "Practical", "const html = `\n  <div>\n    <p>Multi-line</p>\n  </div>\n`;", "How were multi-line strings done in ES5?"),
        ("Can arbitrary expressions and function calls be embedded inside ${} in template literals?", "Yes. Any valid JavaScript expression (arithmetic, ternary, function call, nested template) can be inside ${}.", "Easy", "Practical", "const msg = `Total: $${(price * 1.18).toFixed(2)}`;", "Can you nest template literals?"),
        ("What are tagged template literals in ES6?", "A function tag placed before a template literal: tag`strings... ${expr}`. The tag function receives raw string fragments and evaluated expression values.", "Intermediate", "Concept", "function highlight(strings, ...values) {\n  return strings.reduce((acc, str, i) => `${acc}${str}<b>${values[i] || ''}</b>`, '');\n}", "Where are tagged templates used in real life?"),
        ("Name two major libraries that rely on tagged template literals.", "1. styled-components (e.g. styled.div`color: red;`). 2. GraphQL (e.g. gql`query { ... }`).", "Intermediate", "Practical", "", "What does String.raw do?"),
        ("What does String.raw do in ES6?", "String.raw is a built-in tag function that returns strings with raw escape sequences uninterpreted (e.g. String.raw`C:\\Users` preserves backslashes).", "Intermediate", "Practical", "const path = String.raw`C:\\development\\app`;", "How is String.raw useful for Windows file paths and regex?"),
        ("Arrow MCQ: What does const f = x => ({ val: x }); f(5); return?", "Option B is correct. It returns an object: { val: 5 }.", "Easy", "MCQ", "", {"A": "undefined", "B": "{ val: 5 }", "C": "5", "D": "TypeError"}, "B", "Why are parentheses needed?"),
        ("Arrow MCQ: Which of the following cannot be used with an arrow function?", "Option D is correct. All of these (new, arguments, prototype) are unavailable on arrow functions.", "Easy", "MCQ", "", {"A": "'new' operator", "B": "'arguments' object", "C": "'.prototype' property", "D": "All of the above"}, "D", "How do you access variable arguments in an arrow function?"),
        ("Arrow Output: What is printed: const user = { n: 1, get: () => this.n }; console.log(user.get());?", "Output: undefined. The arrow function lexically inherits 'this' from the outer module or window, where n is undefined.", "Intermediate", "Output", "const user = { n: 1, get: () => this.n };\nconsole.log(user.get()); // undefined", "How do you fix this to output 1?"),
        ("Template Output: What is logged by: const a = 2, b = 3; console.log(`${a + b} is ${a * b}`);?", "Output: '5 is 6'. Both arithmetic expressions are evaluated inside ${}.", "Easy", "Output", "const a = 2, b = 3;\nconsole.log(`${a + b} is ${a * b}`);", "Can a ternary operator be used inside ${}?"),
        ("Arrow Coding: Write an arrow function to filter an array of numbers and return only positive numbers.", "const getPositives = arr => arr.filter(n => n > 0);", "Easy", "Coding", "const getPositives = arr => arr.filter(n => n > 0);\nconsole.log(getPositives([-2, 0, 5, 8])); // [5, 8]", "What is the return value for an empty array?"),
        ("Arrow Coding: Write an arrow function to calculate the average of an array of numbers.", "const average = arr => arr.reduce((acc, val) => acc + val, 0) / arr.length;", "Easy", "Coding", "const average = arr => arr.reduce((a, b) => a + b, 0) / arr.length;\nconsole.log(average([10, 20, 30])); // 20", "What if the array is empty?"),
        ("Arrow Debugging: Why does button.addEventListener('click', () => { this.classList.toggle('active'); }); fail?", "Arrow functions lack their own 'this'. 'this' refers to window rather than the clicked button. Use a regular function or event.currentTarget.", "Easy", "Debugging", "button.addEventListener('click', function() {\n  this.classList.toggle('active');\n});", "How can you use arrow function with event parameter instead?"),
        ("How can you write the click handler with an arrow function safely using the event object?", "Use (e) => e.currentTarget.classList.toggle('active');.", "Easy", "Practical", "button.addEventListener('click', (e) => {\n  e.currentTarget.classList.toggle('active');\n});", "What is the difference between target and currentTarget?"),
        ("What is default parameter evaluation timing in ES6?", "Default parameters are evaluated at call time from left to right, allowing later parameters to reference earlier parameters.", "Intermediate", "Concept", "function greet(name, msg = `Hello ${name}`) {\n  return msg;\n}", "Can an earlier parameter reference a later parameter?"),
        ("Why does function fn(a = b, b = 1) {} throw ReferenceError when called with no arguments?", "'b' is in the Temporal Dead Zone when 'a = b' is evaluated, because parameters are evaluated sequentially from left to right.", "Advanced", "Debugging", "fn(); // ReferenceError: Cannot access 'b' before initialization", "How do you fix this order?")
    ]
    for item in af_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Arrow Functions & Templates", "Syntax & Interpolation",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 3. Destructuring, Rest & Spread - 30 Qs
    drs_items = [
        ("What is array destructuring in ES6?", "Array destructuring unpacks values from arrays or iterables into distinct variables based on their positional index.", "Easy", "Concept", "const [first, second] = [10, 20];", "Can you skip elements in array destructuring?"),
        ("How do you skip unwanted elements in array destructuring?", "Use consecutive commas without variable names: const [first, , third] = [1, 2, 3];.", "Easy", "Practical", "const [a, , c] = [10, 20, 30]; // a = 10, c = 30", "What if there are fewer elements than variables?"),
        ("What value do unbound variables receive in destructuring if array elements are missing?", "Variables without corresponding elements receive undefined (or their default value if provided).", "Easy", "Concept", "const [x, y, z] = [1, 2]; // z is undefined", "How do you provide default values?"),
        ("How do you assign default values in destructuring?", "Use the assignment operator (=): const [a, b = 0] = [1];.", "Easy", "Practical", "const [page = 1, limit = 10] = [];", "When does the default value trigger?"),
        ("Does a default value trigger if the incoming value is null in destructuring?", "No. Default values trigger ONLY when the value is strictly undefined. null is treated as an intentional value.", "Intermediate", "Concept", "const [x = 10] = [null]; // x is null, NOT 10", "What if the value is undefined?"),
        ("How do you swap two variables without a temporary variable in ES6?", "Use array destructuring assignment: [a, b] = [b, a];.", "Easy", "Practical", "let a = 1, b = 2;\n[a, b] = [b, a]; // a = 2, b = 1", "Does this require extra memory allocation?"),
        ("What is object destructuring in ES6?", "Object destructuring extracts properties from an object and binds them to variables matching property keys.", "Easy", "Concept", "const { name, age } = user;", "Can you rename variables during destructuring?"),
        ("How do you rename variables while destructuring an object in ES6?", "Use the colon syntax: const { originalKey: newVariableName } = obj;.", "Easy", "Practical", "const { id: userId, name: userName } = user;", "Can you rename and provide a default value simultaneously?"),
        ("How do you rename a property AND provide a default value in destructuring?", "Combine colon and equals: const { role: userRole = 'guest' } = user;.", "Intermediate", "Practical", "const { role: userRole = 'guest' } = {}; // userRole = 'guest'", "What if role exists?"),
        ("What is nested destructuring?", "Extracting properties from nested child objects or arrays within a single destructuring statement.", "Intermediate", "Practical", "const user = { profile: { email: 'a@b.com' } };\nconst { profile: { email } } = user;", "What happens if profile is undefined?"),
        ("What error occurs if you attempt nested destructuring on an undefined parent: const { a: { b } } = {};?", "TypeError: Cannot read properties of undefined (reading 'b'). Always provide a fallback empty object: const { a: { b } = {} } = {};.", "Intermediate", "Debugging", "const { a: { b } = {} } = {}; // Safe! b is undefined", "How does = {} safeguard nested destructuring?"),
        ("What is the rest operator (...) in function parameters?", "The rest parameter collects all remaining arguments passed to a function into a true JavaScript array.", "Easy", "Concept", "function sum(...numbers) {\n  return numbers.reduce((a, b) => a + b, 0);\n}", "Where must the rest parameter be positioned?"),
        ("Why must the rest parameter always be the last parameter in a parameter list?", "The rest parameter absorbs all remaining arguments. Having parameters after rest causes a SyntaxError: Rest parameter must be last.", "Easy", "Concept", "function test(...rest, last) {} // SyntaxError", "Can a function have multiple rest parameters?"),
        ("What is the spread operator (...) and how does it differ from the rest operator?", "Rest packs elements into an array. Spread unpacks elements of an array or object into individual elements or properties.", "Easy", "Comparison", "const arr = [1, 2, 3];\nconsole.log(...arr); // Spread: logs 1 2 3\nfunction fn(...rest) {} // Rest: gathers args", "Which one is in function call vs definition?"),
        ("How do you shallow clone an object using the spread operator?", "const clone = { ...original };", "Easy", "Practical", "const userCopy = { ...user };", "Are nested objects cloned or shared?"),
        ("Are nested objects copied by reference when using object spread?", "Yes. Object spread performs only a shallow copy. Nested objects remain shared references.", "Easy", "Concept", "const a = { sub: { x: 1 } };\nconst b = { ...a };\nb.sub.x = 2; // a.sub.x is also 2", "How do you perform a deep clone?"),
        ("How do you merge two objects with the spread operator, and how are duplicate keys handled?", "const merged = { ...obj1, ...obj2 };. If both have the same key, the value from the later object overwrites earlier ones.", "Easy", "Practical", "const defaults = { theme: 'light', size: 14 };\nconst overrides = { theme: 'dark' };\nconst config = { ...defaults, ...overrides }; // theme: 'dark'", "Why is this ideal for component props?"),
        ("How do you combine arrays using the spread operator?", "const combined = [...arr1, ...arr2];", "Easy", "Practical", "const all = [1, 2, ...[3, 4], 5]; // [1, 2, 3, 4, 5]", "How does this compare to arr1.concat(arr2)?"),
        ("How do you pass an array of numbers into Math.max() using spread?", "Math.max(...numbersArray);", "Easy", "Practical", "const max = Math.max(...[10, 50, 30]); // 50", "What was used in ES5 before spread?"),
        ("How was Math.max called with an array in ES5 before the spread operator?", "Using apply: Math.max.apply(null, numbersArray);.", "Intermediate", "Comparison", "Math.max.apply(null, [10, 50, 30]);", "Why is spread much cleaner?"),
        ("What does rest syntax do in object destructuring: const { a, ...rest } = obj;?", "It extracts property 'a', and packs all remaining own enumerable properties into a new object called 'rest'.", "Easy", "Practical", "const { password, ...safeUser } = userAccount;", "How is this used to strip sensitive fields?"),
        ("Destructuring MCQ: What is logged by: const [a = 1, b = 2] = [null, undefined]; console.log(a, b);?", "Option C is correct. null is kept for a (null is not undefined); default 2 is used for b (b is undefined).", "Intermediate", "MCQ", "", {"A": "1 2", "B": "null 2", "C": "null 2", "D": "TypeError"}, "C", "Why did a not default to 1?"),
        ("Destructuring MCQ: Where must the rest parameter be located in a function signature?", "Option B is correct. It must always be the last parameter.", "Easy", "MCQ", "", {"A": "First parameter", "B": "Last parameter", "C": "Anywhere", "D": "In middle"}, "B", "What error is thrown if not last?"),
        ("Destructuring Output: What is logged by: const { a, b = 10 } = { a: 0 }; console.log(a, b);?", "Output: 0 10. 0 is a valid falsy value, so 'a' receives 0, while 'b' is undefined in the object and receives default 10.", "Easy", "Output", "const { a, b = 10 } = { a: 0 };\nconsole.log(a, b); // 0 10", "What if a was undefined?"),
        ("Destructuring Coding: Write a function getFullName({ first, last }) that destructures parameters directly.", "const getFullName = ({ first, last = '' }) => `${first} ${last}`.trim();", "Easy", "Coding", "function getFullName({ first, last = '' }) {\n  return `${first} ${last}`.trim();\n}\ngetFullName({ first: 'John', last: 'Doe' }); // 'John Doe'", "What if an empty object or nothing is passed?"),
        ("How do you prevent TypeError when calling a function with destructured parameters without arguments: fn()?", "Provide a default empty object for the parameter: function fn({ a = 1, b = 2 } = {}) {}.", "Intermediate", "Practical", "function setup({ port = 3000, host = 'localhost' } = {}) {\n  console.log(host, port);\n}\nsetup(); // Safe! localhost 3000", "What happens without = {}?"),
        ("Can you destructure a string using array destructuring?", "Yes. Strings are iterable: const [first, second] = 'Hi'; assigns first='H', second='i'.", "Easy", "Practical", "const [first, ...rest] = 'Hello'; // first = 'H', rest = ['e','l','l','o']", "What is rest.join('')?"),
        ("Can you use object destructuring on an array?", "Yes. Arrays are objects with numeric string keys: const { 0: first, length } = [10, 20];.", "Intermediate", "Concept", "const { 0: first, length } = ['a', 'b']; // first='a', length=2", "Why does this work?"),
        ("What does spreading a string into an array do: [...'abc']?", "It converts the string into an array of individual characters: ['a', 'b', 'c'] (properly handling unicode astral symbols).", "Easy", "Practical", "const chars = [...'hello']; // ['h', 'e', 'l', 'l', 'o']", "How does this compare to 'hello'.split('')?"),
        ("Why is [...str] better than str.split('') for strings with emoji/unicode?", "str.split('') breaks surrogate pairs in emoji (split produces broken surrogate halves). Spread iterator handles 32-bit surrogate pairs correctly.", "Advanced", "Comparison", "[...'👍'].length; // 1\n'👍'.split('').length; // 2", "How does unicode surrogate pair work?")
    ]
    for item in drs_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Destructuring, Rest & Spread", "Unpacking & Gathering",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 4. Enhanced Objects, Classes & OOP - 30 Qs
    cls_items = [
        ("What is property shorthand in ES6 object literals?", "If the variable name matches the property key name, you can omit the key: const obj = { name, age }; instead of { name: name, age: age }.", "Easy", "Concept", "const name = 'Sam';\nconst user = { name }; // { name: 'Sam' }", "What is method shorthand?"),
        ("What is method shorthand in ES6 object literals?", "Methods can be written without the function keyword or colon: const obj = { sayHi() {} }; instead of { sayHi: function() {} }.", "Easy", "Concept", "const calc = {\n  add(a, b) { return a + b; }\n};", "Does concise method have a 'prototype' property?"),
        ("What are computed property names in ES6 object literals?", "Property keys can be dynamically computed from expressions inside square brackets: const obj = { [dynamicKey]: 'value' };.", "Easy", "Practical", "const key = 'user_' + id;\nconst obj = { [key]: true };", "Can function calls be inside []?"),
        ("What is an ES6 class?", "A class is a syntactic sugar template for creating objects with constructors, methods, and prototypal inheritance in a clean syntax.", "Easy", "Concept", "class User {\n  constructor(name) { this.name = name; }\n  greet() { return `Hi ${this.name}`; }\n}", "What does typeof ClassName return?"),
        ("What is the constructor method in an ES6 class?", "The constructor method is a special method called automatically when creating a new instance with 'new ClassName()'.", "Easy", "Concept", "class Car {\n  constructor(brand) { this.brand = brand; }\n}", "Can a class have more than one constructor method?"),
        ("Can a class have multiple constructor methods?", "No. A class can have only one constructor method; having more than one throws a SyntaxError: A class may only have one constructor.", "Easy", "Concept", "", "What if you omit the constructor?"),
        ("What happens if you do not define a constructor in an ES6 class?", "A default empty constructor is automatically generated: constructor() {} (or constructor(...args) { super(...args); } in derived classes).", "Intermediate", "Concept", "", "How does inheritance work in ES6 classes?"),
        ("How does a class inherit from another class in ES6?", "Using the 'extends' keyword: class Dog extends Animal {}.", "Easy", "Practical", "class Dog extends Animal {\n  bark() { return 'Woof'; }\n}", "What keyword must be called inside the derived constructor?"),
        ("What does the super keyword do in derived class constructors?", "super() invokes the parent class constructor and binds 'this'. In derived classes, super() must be called before using 'this'.", "Easy", "Concept", "class Dog extends Animal {\n  constructor(name, breed) {\n    super(name);\n    this.breed = breed;\n  }\n}", "What happens if you use 'this' before super()?"),
        ("What error is thrown if you access 'this' before calling super() in a subclass constructor?", "ReferenceError: Must call super constructor in derived class before accessing 'this'.", "Easy", "Debugging", "", "Can super be used to call parent methods?"),
        ("How do you call a parent method from a subclass in ES6?", "Use super.methodName(): super.eat(); calls the parent class's eat method.", "Easy", "Practical", "class Dog extends Animal {\n  eat() {\n    super.eat();\n    console.log('wagging tail');\n  }\n}", "Can super be used in static methods?"),
        ("What is a static method in an ES6 class?", "A static method is defined with the static keyword and is called directly on the class itself, not on instances of the class.", "Easy", "Concept", "class MathUtil {\n  static add(a, b) { return a + b; }\n}\nMathUtil.add(2, 3); // 5", "Can instances call static methods?"),
        ("What are static properties in modern ES classes?", "Static properties are class-level properties shared on the class constructor itself: static appVersion = '1.0.0'.", "Easy", "Practical", "class Config {\n  static API_URL = 'https://api.example.com';\n}", "How do you access static properties?"),
        ("What are private class fields in modern JavaScript?", "Fields prefixed with hash (#) are strictly private to the class and cannot be accessed or modified from outside the class.", "Intermediate", "Concept", "class BankAccount {\n  #balance = 0;\n  getBalance() { return this.#balance; }\n}", "Can subclasses access private # fields?"),
        ("Can subclasses access private (#) fields of their parent class?", "No. Private fields are strictly scoped to the declaring class body. Even subclasses cannot access them.", "Intermediate", "Concept", "", "What happens if code outside accesses user.#balance?"),
        ("What happens if external code tries to access user.#balance?", "A SyntaxError is thrown at parse time: Private field '#balance' must be declared in an enclosing class.", "Intermediate", "Security", "", "How does # differ from the convention of using underscore _prefix?"),
        ("What is the difference between _name and #name in JavaScript classes?", "_name is merely a naming convention (still completely public). #name is enforced by the JavaScript engine and physically inaccessible outside.", "Easy", "Comparison", "", "Are ES6 classes hoisted like function declarations?"),
        ("Are ES6 classes hoisted in JavaScript?", "Yes, classes are hoisted, but they remain uninitialized in the Temporal Dead Zone (TDZ). Calling new Class() before declaration throws ReferenceError.", "Intermediate", "Concept", "new User(); // ReferenceError\nclass User {}", "How does this differ from function declarations?"),
        ("Are ES6 classes in strict mode by default?", "Yes. The body of an ES6 class is always executed in strict mode ('use strict'), even without an explicit 'use strict' directive.", "Easy", "Concept", "", "What are getter and setter methods in classes?"),
        ("How do you define getters and setters in an ES6 class?", "Use the get and set keywords before method names: get prop() {} and set prop(value) {}.", "Easy", "Practical", "class Temperature {\n  constructor(celsius) { this.c = celsius; }\n  get fahrenheit() { return this.c * 1.8 + 32; }\n  set fahrenheit(f) { this.c = (f - 32) / 1.8; }\n}", "Can you have a getter without a setter?"),
        ("What happens if you assign to a property that only has a getter in strict mode?", "In strict mode (always on in classes), assigning to a getter-only property throws a TypeError: Cannot set property... which has only a getter.", "Intermediate", "Concept", "", "What is class expression syntax?"),
        ("What is an ES6 class expression?", "A class can be defined as an expression assigned to a variable: const MyClass = class { ... }; (can be named or anonymous).", "Easy", "Concept", "const User = class {\n  constructor(name) { this.name = name; }\n};", "Where are class expressions useful?"),
        ("Classes MCQ: What keyword is mandatory before using 'this' in a derived subclass constructor?", "Option C is correct. super() must be called first.", "Easy", "MCQ", "", {"A": "parent()", "B": "base()", "C": "super()", "D": "this.init()"}, "C", "What error occurs if omitted?"),
        ("Classes MCQ: How do you declare an engine-enforced private field in an ES class?", "Option B is correct. Prefix with # (e.g. #count = 0).", "Easy", "MCQ", "", {"A": "_count", "B": "#count", "C": "private count", "D": "$count"}, "B", "Can external code read #count?"),
        ("Classes Output: What does typeof class MyClass {} return in JavaScript?", "Option B is correct. typeof MyClass returns 'function'. Classes are functions under the hood.", "Easy", "MCQ", "", {"A": "'object'", "B": "'function'", "C": "'class'", "D": "'constructor'"}, "B", "Why does it return function?"),
        ("Classes Debugging: A developer wrote class Box { constructor(w) { this.w = w; } static area() { return this.w; } }; const b = new Box(5); b.area(). What happens?", "TypeError: b.area is not a function. Static methods are on the class Box itself (Box.area()), not on instances.", "Easy", "Debugging", "Box.area(); // Static call\n// Or remove static for instance method", "How do you make area an instance method?"),
        ("Classes Output: What is logged by: class A { constructor() { console.log('A'); } } class B extends A { constructor() { super(); console.log('B'); } } new B();?", "Output: 'A' then 'B'. super() executes parent constructor A first, then child constructor B.", "Easy", "Output", "new B(); // Logs 'A', then 'B'", "What if super() was called after console.log('B')?"),
        ("Classes Coding: Write a Rectangle class with width and height, and an area getter.", "class Rectangle { constructor(w, h) { this.w = w; this.h = h; } get area() { return this.w * this.h; } }", "Easy", "Coding", "class Rectangle {\n  constructor(w, h) { this.w = w; this.h = h; }\n  get area() { return this.w * this.h; }\n}\nconst r = new Rectangle(5, 4);\nconsole.log(r.area); // 20", "Does r.area need parentheses?"),
        ("Classes Coding: Write a Square class that extends Rectangle and takes only a single 'side' parameter.", "class Square extends Rectangle { constructor(side) { super(side, side); } }", "Easy", "Coding", "class Square extends Rectangle {\n  constructor(side) {\n    super(side, side);\n  }\n}\nconst sq = new Square(5);\nconsole.log(sq.area); // 25", "Why does super(side, side) work elegantly?"),
        ("What is the difference between instanceof and isPrototypeOf()?", "a instanceof B checks if B.prototype is anywhere on a's prototype chain. B.prototype.isPrototypeOf(a) does the same check directly between objects.", "Intermediate", "Comparison", "Animal.prototype.isPrototypeOf(dog); // true", "Can isPrototypeOf test plain objects without constructors?")
    ]
    for item in cls_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Classes & Enhanced Objects", "Object Oriented ES6",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 5. Modules, Map/Set & Symbols - 30 Qs
    mod_items = [
        ("What are ES6 modules (ESM)?", "ES6 modules are the official JavaScript standard format for modular code, using 'export' to share values and 'import' to consume them.", "Easy", "Concept", "// utils.js\nexport const add = (a, b) => a + b;\n// app.js\nimport { add } from './utils.js';", "What is the file extension often used in Node.js for ESM?"),
        ("What is the difference between named export and default export in ES6 modules?", "A module can have multiple named exports (imported with matching names inside {}). A module can have at most ONE default export (imported with any name without {}).", "Easy", "Comparison", "// export default Component;\n// import MyComponent from './Component';", "Can a module have both named and default exports?"),
        ("Can a single file have both default export and named exports?", "Yes! You can have one default export along with any number of named exports in the same module.", "Easy", "Practical", "export default function main() {}\nexport const helper = () => {};\n// In importer:\nimport main, { helper } from './lib.js';", "How do you rename named imports?"),
        ("How do you rename named imports using the 'as' keyword?", "Use 'as': import { originalName as newName } from './module.js'.", "Easy", "Practical", "import { render as domRender } from 'react-dom';", "How do you import all exports into an object?"),
        ("How do you import all exports of a module into a single namespace object?", "Use import * as namespace from './module.js'.", "Easy", "Practical", "import * as MathUtils from './math.js';\nMathUtils.add(1, 2);", "What is dynamic import()?"),
        ("What is dynamic import() in JavaScript?", "dynamic import(modulePath) loads a module asynchronously on demand and returns a Promise that resolves to the module namespace.", "Intermediate", "Concept", "const module = await import('./analytics.js');", "Why is dynamic import essential for code-splitting?"),
        ("What is the difference between CommonJS and ES Modules?", "CommonJS (require/module.exports) is synchronous and used by Node.js traditionally. ES Modules (import/export) are asynchronous, statically analyzable, and supported natively in browsers and modern Node.", "Intermediate", "Comparison", "// CommonJS\nconst fs = require('fs');\n// ESM\nimport fs from 'fs';", "Why does tree-shaking require ES modules?"),
        ("Why does tree-shaking require ES Modules instead of CommonJS?", "ESM imports and exports are static (determined at compile-time before execution), allowing bundlers to detect and remove unused dead code reliably. CommonJS is dynamic at runtime.", "Intermediate", "Concept", "", "What script tag attribute enables ES modules in HTML?"),
        ("How do you enable ES Modules in browser HTML?", "Add type='module' to the <script> tag: <script type='module' src='app.js'></script>.", "Easy", "Practical", "<script type=\"module\" src=\"app.js\"></script>", "Are script type='module' tags deferred by default?"),
        ("Are <script type='module'> tags deferred by default?", "Yes. Module scripts automatically behave as if 'defer' is present; they download in parallel and execute only after HTML parsing completes.", "Intermediate", "Concept", "", "What is CORS requirement for module scripts?"),
        ("Why do ES module scripts in browsers require CORS or an HTTP server to load?", "Browsers block module imports over the file:// protocol due to cross-origin security restrictions. Modules must be served via http:// or https://.", "Intermediate", "Security", "", "What is a Set in ES6?"),
        ("What is a Set in ES6?", "A Set is a built-in collection of unique values where each value may occur only once.", "Easy", "Concept", "const set = new Set([1, 2, 2, 3]);\nconsole.log(set.size); // 3", "What method checks if a value exists in a Set?"),
        ("What are the primary methods of a Set in ES6?", ".add(val), .has(val), .delete(val), .clear(), and the .size property.", "Easy", "Practical", "const s = new Set();\ns.add('a');\ns.has('a'); // true\ns.delete('a');\ns.size; // 0", "What is the time complexity of Set.prototype.has()?"),
        ("What is the time complexity of Set.prototype.has() vs Array.prototype.includes()?", "Set.prototype.has() is O(1) constant time hash lookup. Array.prototype.includes() is O(n) linear search.", "Intermediate", "Comparison", "", "Why is Set ideal for large lookup collections?"),
        ("What is a Map in ES6?", "A Map is an ordered collection of key-value pairs where ANY data type (including objects, functions, and primitives) can be used as keys.", "Easy", "Concept", "const map = new Map();\nconst keyObj = {};\nmap.set(keyObj, 'data');", "How does Map differ from a plain object?"),
        ("What are three key differences between a Map and a plain object?", "1. Map keys can be of ANY type (objects, functions); object keys are strings/symbols. 2. Map preserves insertion order. 3. Map has an explicit .size property (no Object.keys needed).", "Intermediate", "Comparison", "map.set(btn, 'handler');\nmap.size; // 1", "How do you iterate over a Map?"),
        ("What are the primary methods of a Map in ES6?", ".set(key, val), .get(key), .has(key), .delete(key), .clear(), and .size.", "Easy", "Practical", "const m = new Map();\nm.set('id', 101);\nm.get('id'); // 101", "What does map.get(nonExistentKey) return?"),
        ("What is a WeakSet in ES6?", "A WeakSet is a Set that can ONLY store objects and holds weak references to them, allowing unreferenced objects to be garbage collected.", "Intermediate", "Concept", "const ws = new WeakSet();", "Can you iterate over a WeakSet?"),
        ("Why can you NOT iterate or read .size on a WeakSet or WeakMap?", "Because the garbage collector can reclaim objects at any non-deterministic moment, the collection contents cannot be enumerated stably.", "Advanced", "Concept", "", "What is WeakMap?"),
        ("What is a WeakMap in ES6?", "A WeakMap is a Map whose keys MUST be objects (or non-registered symbols) held as weak references, preventing memory leaks.", "Intermediate", "Concept", "const wm = new WeakMap();\nwm.set(domElement, { clicks: 0 });", "Why is WeakMap great for private data and DOM metadata?"),
        ("What is a Symbol in ES6?", "A Symbol is a unique, immutable primitive data type often used as hidden or collision-free object property keys.", "Intermediate", "Concept", "const id = Symbol('id');\nconst id2 = Symbol('id');\nid === id2; // false!", "Are two Symbols with the same description equal?"),
        ("Are two Symbols created with Symbol('desc') equal?", "No! Every call to Symbol() returns a completely unique Symbol primitive: Symbol('a') === Symbol('a') is false.", "Easy", "Concept", "Symbol('x') === Symbol('x'); // false", "How do you create shared global symbols?"),
        ("What is the Global Symbol Registry and how do you access it?", "Use Symbol.for(key). If a symbol with that key exists globally, it returns it; otherwise it creates and registers a new global symbol.", "Intermediate", "Practical", "const s1 = Symbol.for('app');\nconst s2 = Symbol.for('app');\ns1 === s2; // true!", "What does Symbol.keyFor do?"),
        ("What are Well-Known Symbols in JavaScript?", "Built-in symbols that expose internal language algorithms, such as Symbol.iterator, Symbol.hasInstance, and Symbol.toStringTag.", "Advanced", "Concept", "", "What does Symbol.iterator do?"),
        ("What does Symbol.iterator do in JavaScript?", "It specifies the default iterator function for an object. Objects implementing [Symbol.iterator]() can be used in for...of loops and spread operators.", "Intermediate", "Concept", "const iterable = {\n  *[Symbol.iterator]() { yield 1; yield 2; }\n};\nfor (const x of iterable) console.log(x); // 1, 2", "How do you make any custom object iterable?"),
        ("Modules MCQ: Which syntax correctly imports a default export?", "Option A is correct. Default exports are imported without curly braces.", "Easy", "MCQ", "", {"A": "import MyComp from './Comp';", "B": "import { MyComp } from './Comp';", "C": "import * as MyComp from './Comp';", "D": "require(MyComp)"}, "A", "When are curly braces needed?"),
        ("Modules MCQ: What is the main security reason ES modules require an HTTP server in browsers?", "Option C is correct. Browser CORS policies block module file imports over the local file:// protocol.", "Intermediate", "MCQ", "", {"A": "HTML5 restriction", "B": "CSS loading rules", "C": "CORS security policy", "D": "V8 memory limit"}, "C", "How do you serve files locally?"),
        ("Map/Set MCQ: What does new Set([1, 2, 2, 3]).size return?", "Option B is correct. Set discards duplicates; size is 3.", "Easy", "MCQ", "", {"A": "4", "B": "3", "C": "2", "D": "undefined"}, "B", "What values does the set contain?"),
        ("Map Coding: Write a function to count the frequency of words in an array using a Map.", "function wordCount(words) { const map = new Map(); for (const w of words) map.set(w, (map.get(w) || 0) + 1); return map; }", "Easy", "Coding", "function wordCount(words) {\n  const m = new Map();\n  for (const w of words) {\n    m.set(w, (m.get(w) || 0) + 1);\n  }\n  return m;\n}", "What does map.get(w) || 0 handle?"),
        ("Symbol Output: What is logged by: const id = Symbol('id'); const obj = { [id]: 123, name: 'A' }; console.log(Object.keys(obj));?", "Output: ['name']. Symbol keys are non-enumerable in Object.keys() and for...in loops. Use Object.getOwnPropertySymbols(obj) to see symbols.", "Intermediate", "Output", "const id = Symbol('id');\nconst obj = { [id]: 123, name: 'A' };\nconsole.log(Object.keys(obj)); // ['name']", "How do you access symbol keys on an object?")
    ]
    for item in mod_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Modules, Map/Set & Symbols", "Modules & Data Structures",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 6. Iterators, Generators & Modern Syntax (Optional Chaining, Nullish Coalescing) - 25 Qs
    gen_items = [
        ("What is the Iterable protocol in JavaScript?", "An object is iterable if it implements a [Symbol.iterator]() method that returns an iterator object conforming to the Iterator protocol.", "Intermediate", "Concept", "", "Name 4 built-in iterables."),
        ("What are 4 built-in iterable objects in JavaScript?", "Array, String, Map, and Set (as well as TypedArrays and arguments).", "Easy", "Concept", "", "Are plain objects iterable?"),
        ("What is the Iterator protocol in JavaScript?", "An object is an iterator if it implements a next() method that returns an object: { value: Any, done: Boolean }.", "Intermediate", "Concept", "const iter = [1][Symbol.iterator]();\niter.next(); // { value: 1, done: false }", "What is done set to when finished?"),
        ("What is a generator function in JavaScript?", "A function marked with an asterisk (function*) that can pause execution using 'yield' and resume on demand when its generator's next() is called.", "Intermediate", "Concept", "function* numbers() {\n  yield 1;\n  yield 2;\n}", "Can generators yield infinite sequences?"),
        ("How can a generator produce an infinite sequence without crashing the browser?", "Generators evaluate lazily on-demand: while (true) { yield n++; }. It only runs when .next() is explicitly invoked.", "Advanced", "Practical", "function* idGenerator() {\n  let id = 1;\n  while (true) yield id++;\n}\nconst ids = idGenerator();\nids.next().value; // 1\nids.next().value; // 2", "Why does while(true) not block here?"),
        ("What does the yield* keyword do in a generator?", "yield* delegates execution to another iterable or generator function sequentially.", "Advanced", "Concept", "function* a() { yield 1; }\nfunction* b() { yield* a(); yield 2; }", "What is generator delegation?"),
        ("Can you pass values into a generator using next(value)?", "Yes. Passing a value to next(val) sends that value into the generator as the result of the paused yield expression.", "Advanced", "Concept", "function* gen() {\n  const x = yield 'start';\n  console.log(x); // 'hello'\n}\nconst g = gen();\ng.next();\ng.next('hello');", "How is this used in redux-saga?"),
        ("What is the optional chaining operator (?.) in ES2020?", "Optional chaining returns undefined if an object or reference in the property chain is null or undefined, without throwing a TypeError.", "Easy", "Concept", "const street = user?.address?.street;", "How was this handled before ES2020?"),
        ("How does optional chaining work with function calls: fn?.()?", "If fn is null or undefined, fn?.() evaluates safely to undefined instead of throwing TypeError: fn is not a function.", "Easy", "Practical", "onSuccess?.(data);", "What if fn exists but is a number?"),
        ("What happens if you use optional chaining on a property that exists but is not a function: const x = 5; x?.();?", "It throws a TypeError: x is not a function. Optional chaining only checks if the target is null or undefined; it does not check data types.", "Intermediate", "Debugging", "const x = 5;\nx?.(); // TypeError: x is not a function", "Why does it still throw TypeError?"),
        ("How does optional chaining work with dynamic property bracket notation?", "Use ?.[key]: const val = obj?.[dynamicProperty];.", "Easy", "Practical", "const role = user?.['user-role'];", "Can it be used on arrays?"),
        ("How does optional chaining work on arrays?", "Use ?.[index]: const first = items?.[0];.", "Easy", "Practical", "const first = list?.[0];", "What does it return if list is null?"),
        ("What is the nullish coalescing operator (??) in ES2020?", "?? returns the right-hand operand ONLY when the left-hand operand is null or undefined (preserves 0, false, and '').", "Easy", "Concept", "const score = userScore ?? 0;", "Why is ?? better than || for configuration options?"),
        ("Why is ?? superior to || for setting numeric default settings?", "|| treats 0 as falsy and overwrites it with the default (e.g. timeout || 5000 replaces 0ms with 5000ms). ?? preserves 0.", "Easy", "Comparison", "const port = userPort ?? 3000; // If userPort is 0, port is 0\nconst badPort = userPort || 3000; // If userPort is 0, port is 3000", "Can ?? and || be mixed without parentheses?"),
        ("Why does JavaScript prohibit mixing ?? and && or || without parentheses: a || b ?? c?", "Mixing ?? with && or || without explicit parentheses throws a SyntaxError due to ambiguity in precedence. Always wrap in (): (a || b) ?? c.", "Intermediate", "Concept", "const x = (a || b) ?? c; // Valid", "How does this prevent logical bugs?"),
        ("What are Logical Assignment Operators (??=, &&=, ||=) in ES2021?", "They combine logical operations with assignment: a ??= b assigns b to a ONLY if a is null or undefined. a ||= b assigns if a is falsy.", "Intermediate", "Practical", "options.timeout ??= 3000;\nuser.name ||= 'Anonymous';", "What does a &&= b do?"),
        ("What does a &&= b do in JavaScript?", "It assigns b to a ONLY if a is currently truthy.", "Intermediate", "Concept", "let loggedIn = true;\nloggedIn &&= 'Active';", "How is this useful in state updates?"),
        ("What are numeric separators in modern JavaScript (ES2021)?", "Underscores (_) used as visual digit separators inside number literals to improve readability: const billion = 1_000_000_000;.", "Easy", "Concept", "const salary = 120_000;", "Does numeric separator affect the value of the number?"),
        ("What is Array.prototype.findLast() in ES2023?", "findLast() iterates the array in reverse and returns the value of the first element that satisfies the testing condition.", "Easy", "Practical", "const lastNegative = [1, -2, 3, -4, 5].findLast(x => x < 0); // -4", "What does findLastIndex do?"),
        ("What is Array.prototype.findLastIndex() in ES2023?", "findLastIndex() iterates in reverse and returns the index of the first element satisfying the test condition, or -1.", "Easy", "Practical", "const idx = [1, -2, 3, -4].findLastIndex(x => x < 0); // 3", "Why is findLast cleaner than reverse().find()?"),
        ("Why is findLast() better than arr.reverse().find()?", "arr.reverse() mutates the original array in place and reverses all elements before searching. findLast() searches in reverse without mutating.", "Intermediate", "Comparison", "", "What is Object.hasOwn in ES2022?"),
        ("What is Object.hasOwn(obj, prop) in ES2022?", "A safe, static replacement for obj.hasOwnProperty(prop) that works reliably even on Object.create(null) instances.", "Easy", "Concept", "Object.hasOwn(user, 'email'); // true", "Why was hasOwnProperty problematic?"),
        ("Modern ES MCQ: What is logged by: const x = 0 ?? 10; const y = 0 || 10; console.log(x, y);?", "Option B is correct. x is 0 (?? keeps 0); y is 10 (|| rejects 0).", "Easy", "MCQ", "", {"A": "10 10", "B": "0 10", "C": "0 0", "D": "10 0"}, "B", "Why does ?? keep 0?"),
        ("Modern ES Output: What is logged by: const obj = null; console.log(obj?.user?.name ?? 'Guest');?", "Output: 'Guest'. Optional chaining safely returns undefined, and ?? provides the fallback 'Guest'.", "Easy", "Output", "const obj = null;\nconsole.log(obj?.user?.name ?? 'Guest'); // 'Guest'", "Does it throw any error?"),
        ("Modern ES Coding: Write a generator function fibonacci() that yields Fibonacci numbers infinitely.", "function* fibonacci() { let [prev, curr] = [0, 1]; while (true) { yield prev; [prev, curr] = [curr, prev + curr]; } }", "Intermediate", "Coding", "function* fibonacci() {\n  let [prev, curr] = [0, 1];\n  while (true) {\n    yield prev;\n    [prev, curr] = [curr, prev + curr];\n  }\n}\nconst fib = fibonacci();\nconsole.log(fib.next().value, fib.next().value, fib.next().value); // 0, 1, 1", "How do you take the first 5 numbers?")
    ]
    for item in gen_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Iterators & Modern Syntax", "Generators & ES2020+",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    # 7. Modern Array Methods & Standards - 50 Qs
    extra_items = [
        ("What does Array.of() do in ES6?", "Array.of(...elements) creates a new Array instance with the given elements, avoiding the single-number array length pitfall of new Array(3).", "Easy", "Concept", "Array.of(3); // [3]\nnew Array(3); // [ <3 empty items> ]", "Why was Array.of created?"),
        ("What is the difference between Array(5) and Array.of(5)?", "Array(5) creates an empty array of length 5. Array.of(5) creates an array containing a single numeric element [5].", "Easy", "Comparison", "", "What does Array.from do?"),
        ("What does Array.prototype.copyWithin() do?", "copyWithin(target, start, end) shallow copies a section of an array to another location in the same array in place without changing its length.", "Advanced", "Practical", "[1, 2, 3, 4, 5].copyWithin(0, 3); // [4, 5, 3, 4, 5]", "Does copyWithin mutate the array?"),
        ("What does Array.prototype.fill() do in ES6?", "fill(value, start, end) fills specified elements in an array with a static value in place, mutating the array.", "Easy", "Practical", "new Array(3).fill(0); // [0, 0, 0]", "Why is new Array(3).fill({}) risky?"),
        ("Why is new Array(3).fill({}) a common bug in JavaScript?", "fill({}) fills the array with the exact same shared object reference. Mutating arr[0].x mutates arr[1].x and arr[2].x as well.", "Intermediate", "Debugging", "const arr = Array.from({ length: 3 }, () => ({})); // Safe! Separate objects", "How do you create unique objects?"),
        ("What does String.prototype.codePointAt() do in ES6?", "codePointAt() returns the full non-negative Unicode code point value of a character, properly handling 32-bit surrogate pairs where charCodeAt fails.", "Intermediate", "Concept", "'👍'.codePointAt(0); // 128077", "How does this differ from charCodeAt?"),
        ("What does String.fromCodePoint() do in ES6?", "String.fromCodePoint() returns a string created by using the specified sequence of Unicode code points.", "Intermediate", "Practical", "String.fromCodePoint(128077); // '👍'", "What does String.fromCharCode do with emoji?"),
        ("What is the difference between Object.is() and === for +0 and -0?", "Object.is(+0, -0) evaluates to false. === evaluates +0 === -0 to true.", "Intermediate", "Comparison", "Object.is(+0, -0); // false\n+0 === -0; // true", "Why does Object.is distinguish them?"),
        ("What is the difference between Object.is() and === for NaN?", "Object.is(NaN, NaN) evaluates to true. === evaluates NaN === NaN to false.", "Easy", "Comparison", "Object.is(NaN, NaN); // true\nNaN === NaN; // false", "How does React use Object.is?"),
        ("What does Promise.allSettled() solve that Promise.all() cannot?", "Promise.allSettled waits for all promises to finish even if some reject. Promise.all aborts immediately on the first rejection.", "Easy", "Comparison", "", "What format do settled objects have?"),
        ("What does Promise.any() reject with when all promises fail?", "It rejects with an AggregateError containing all individual rejection reasons in its .errors property.", "Intermediate", "Concept", "", "What is the difference between Promise.any and Promise.race?"),
        ("What is RegExp sticky flag /y in ES6?", "The 'y' flag performs 'sticky' matching: it matches only from the exact position indicated by the lastIndex property of the regular expression.", "Advanced", "Concept", "const regex = /foo/y;", "How does sticky differ from global /g?"),
        ("What is RegExp unicode flag /u in ES6?", "The 'u' flag enables full Unicode handling, treating surrogate pairs as single characters in character sets and dot wildcards.", "Intermediate", "Concept", "/^.$/u.test('👍'); // true", "What happens without the 'u' flag on emoji?"),
        ("What is RegExp dotAll flag /s in ES2018?", "The 's' flag allows the dot (.) wildcard to match newline characters (\\n, \\r), which it normally does not match.", "Intermediate", "Concept", "/hello.world/s.test('hello\\nworld'); // true", "How did developers match all characters before /s?"),
        ("What are RegExp named capture groups in ES2018?", "Groups named with (?<name>...) format whose captured matches can be read via match.groups.name instead of numerical indices.", "Intermediate", "Practical", "const regex = /(?<year>\\d{4})-(?<month>\\d{2})/;\nconst { groups: { year, month } } = regex.exec('2026-10');", "Why are named capture groups clearer?"),
        ("What are RegExp lookbehind assertions in ES2018?", "Positive lookbehind (?<=...) and negative lookbehind (?<!...) assert that what precedes the current match matches or does not match a pattern.", "Advanced", "Concept", "const price = /(?<=\\$)\\d+/.exec('$100')[0]; // '100'", "How does lookbehind differ from lookahead?"),
        ("What does Promise.prototype.finally() do in ES2018?", "finally(callback) executes cleanup logic when a promise settles (fulfilled or rejected) and yields the original promise result unchanged.", "Easy", "Practical", "fetch(url).then(handle).catch(err).finally(cleanup);", "Does finally receive any arguments?"),
        ("Does Promise.prototype.finally() receive any arguments in its callback?", "No. The finally callback receives no arguments because it is intended for generic cleanup regardless of outcome.", "Easy", "Concept", "", "Can finally return a promise?"),
        ("What is Asynchronous Iteration (for await...of) in ES2018?", "for await...of iterates over async iterable collections or streams of promises sequentially, awaiting each value before the next iteration.", "Intermediate", "Concept", "for await (const chunk of stream) {\n  console.log(chunk);\n}", "Where is for await...of heavily used in Node.js?"),
        ("What is an Async Generator function in ES2018?", "An async function* that can use both 'await' and 'yield', producing an asynchronous iterable of promises.", "Advanced", "Concept", "async function* fetchPages() {\n  yield await fetchPage(1);\n  yield await fetchPage(2);\n}", "How do you consume an async generator?"),
        ("What is Object.fromEntries() in ES2019?", "Object.fromEntries() transforms an iterable of [key, value] pairs into an object (the inverse of Object.entries()).", "Easy", "Practical", "const obj = Object.fromEntries([['name', 'A'], ['age', 25]]);", "How is it used with Map?"),
        ("How do you convert a Map to an Object using Object.fromEntries?", "Object.fromEntries(myMap);", "Easy", "Practical", "const map = new Map([['a', 1]]);\nconst obj = Object.fromEntries(map); // { a: 1 }", "How do you convert Object back to Map?"),
        ("What does String.prototype.trimStart() and trimEnd() do in ES2019?", "trimStart() removes whitespace from the start of a string; trimEnd() removes whitespace from the end.", "Easy", "Practical", "'  hi  '.trimStart(); // 'hi  '", "What were their previous non-standard names?"),
        ("What does Array.prototype.flat() do in ES2019?", "flat(depth) creates a new array with sub-array elements concatenated recursively up to the specified depth.", "Easy", "Practical", "[1, [2, [3]]].flat(2); // [1, 2, 3]", "What is the default depth?"),
        ("What is the default depth of Array.prototype.flat()?", "Default depth is 1.", "Easy", "Concept", "[1, [2, [3]]].flat(); // [1, 2, [3]]", "How do you flatten completely?"),
        ("What does Array.prototype.flatMap() do in ES2019?", "flatMap(fn) applies a mapping function to each element and flattens the result by one level.", "Intermediate", "Practical", "['a b', 'c d'].flatMap(x => x.split(' ')); // ['a', 'b', 'c', 'd']", "Why is flatMap faster than .map().flat()?"),
        ("What is optional catch binding in ES2019?", "In ES2019, the error parameter in catch blocks is optional: try { ... } catch { /* no (e) parameter needed */ }.", "Easy", "Practical", "try {\n  JSON.parse(data);\n} catch {\n  return defaultValue;\n}", "When is omitting the error parameter useful?"),
        ("What is BigInt in ES2020?", "BigInt is a primitive data type that can represent arbitrary precision integers beyond Number.MAX_SAFE_INTEGER.", "Easy", "Concept", "const big = 9007199254740991n + 100n;", "How do you write a BigInt literal?"),
        ("How do you write a BigInt literal in JavaScript?", "Append 'n' to the end of an integer: e.g. 100n or BigInt(100).", "Easy", "Practical", "const val = 123456789012345678901234567890n;", "Can BigInt be mixed with regular numbers in arithmetic?"),
        ("Can you mix BigInt and Number in arithmetic operations like 10n + 5?", "No. Mixing BigInt and Number throws TypeError: Cannot mix BigInt and other types. You must explicitly convert one.", "Intermediate", "Concept", "10n + BigInt(5); // 15n", "Can BigInt represent decimals?"),
        ("Can BigInt represent fractional decimal numbers?", "No. BigInt is strictly for whole integers. Division truncates towards zero (5n / 2n === 2n).", "Easy", "Concept", "5n / 2n; // 2n (truncates)", "What does 5 / 2 return with numbers?"),
        ("What is globalThis in ES2020?", "globalThis provides a universal standard property to access the global object in any JavaScript environment.", "Easy", "Concept", "globalThis.setTimeout;", "What was used before globalThis?"),
        ("What is String.prototype.matchAll() in ES2020?", "matchAll(regex) returns an iterator of all matching results (including capture groups) against a regex with the 'g' flag.", "Intermediate", "Practical", "const matches = [...str.matchAll(/(\\w+)/g)];", "Why is matchAll better than exec in a while loop?"),
        ("What is String.prototype.replaceAll() in ES2021?", "replaceAll(search, replaceWith) replaces all occurrences of a string or regex match without needing /g regex.", "Easy", "Practical", "'a-b-a'.replaceAll('a', 'z'); // 'z-b-z'", "What does replace('a', 'z') do without regex?"),
        ("What are Numeric Separators in ES2021?", "Underscores (_) used inside numeric literals to make large numbers readable: const ms = 1_000_000;.", "Easy", "Practical", "const num = 1_000_000;", "Does the underscore change the numeric value?"),
        ("What are Logical Assignment Operators in ES2021?", "a ||= b (assigns if a is falsy), a &&= b (assigns if a is truthy), a ??= b (assigns if a is null or undefined).", "Easy", "Concept", "let x = null;\nx ??= 50; // x becomes 50", "When does ??= trigger?"),
        ("What is Promise.any() in ES2021?", "Promise.any resolves with the first fulfilled promise, or rejects with AggregateError if all reject.", "Easy", "Concept", "Promise.any([p1, p2]);", "How does it differ from Promise.race?"),
        ("What is Array.prototype.at() in ES2022?", "at(index) returns the item at index, supporting negative numbers to count from the end (arr.at(-1)).", "Easy", "Practical", "const arr = [10, 20, 30];\narr.at(-1); // 30", "Does at() work on strings?"),
        ("Does String.prototype.at() exist in ES2022?", "Yes. Strings also support .at(-1) to read the last character: 'hello'.at(-1) returns 'o'.", "Easy", "Practical", "'hello'.at(-1); // 'o'", "What does 'hello'.at(-2) return?"),
        ("What is Object.hasOwn() in ES2022?", "A safe static method checking for an own property: Object.hasOwn(obj, prop).", "Easy", "Practical", "Object.hasOwn(user, 'name');", "What did it replace?"),
        ("What is Error cause in ES2022?", "Error constructors accept an options object with a 'cause' property to chain errors: new Error('Failed', { cause: err }).", "Intermediate", "Practical", "try {\n  fetchData();\n} catch (err) {\n  throw new Error('Data load failed', { cause: err });\n}", "How do you access the original error?"),
        ("What is Top-level await in ES2022?", "await can be used directly at the top level of an ES module without wrapping inside an async function.", "Easy", "Concept", "const data = await fetch('/api').then(r => r.json());", "Where is top-level await supported?"),
        ("What is Array.prototype.toSorted() in ES2023?", "toSorted(compareFn) returns a new sorted array without mutating the original array.", "Easy", "Practical", "const sorted = items.toSorted((a, b) => a - b);", "Does original items array change?"),
        ("What is Array.prototype.toReversed() in ES2023?", "toReversed() returns a new reversed array without mutating the original array.", "Easy", "Practical", "const rev = items.toReversed();", "What was the mutating version?"),
        ("What is Array.prototype.toSpliced() in ES2023?", "toSpliced(start, deleteCount, ...items) returns a new array with items removed/added without mutating original array.", "Intermediate", "Practical", "const updated = items.toSpliced(1, 1, 'new');", "Does items array change?"),
        ("What is Array.prototype.with() in ES2023?", "with(index, value) returns a new array with the element at the specified index replaced by value, without mutating original.", "Easy", "Practical", "const next = [1, 2, 3].with(1, 99); // [1, 99, 3]", "Why is with() great for React state?"),
        ("What is Array.prototype.findLast() in ES2023?", "findLast(fn) searches from right to left and returns the first element matching condition.", "Easy", "Practical", "[1, 2, 3, 4].findLast(x => x % 2 === 0); // 4", "What does findLastIndex return?"),
        ("What is Hashbang (#!) syntax support in ES2023?", "JavaScript engines natively recognize and ignore the #! (shebang) line at the start of a script for direct CLI executable scripts (e.g. #!/usr/bin/env node).", "Intermediate", "Concept", "#!/usr/bin/env node\nconsole.log('CLI App');", "Why was this standardized?"),
        ("What is Promise.withResolvers() in ES2024?", "Promise.withResolvers() returns an object containing a new promise and its resolve and reject functions: const { promise, resolve, reject } = Promise.withResolvers();.", "Intermediate", "Practical", "const { promise, resolve, reject } = Promise.withResolvers();\nsetTimeout(() => resolve('done'), 1000);", "Why is Promise.withResolvers cleaner than new Promise()?"),
        ("What is Object.groupBy() in ES2024?", "Object.groupBy(iterable, callback) groups elements of an iterable into an object keyed by the callback return values.", "Intermediate", "Practical", "const items = [{ cat: 'fruit', name: 'apple' }, { cat: 'fruit', name: 'banana' }];\nconst grouped = Object.groupBy(items, i => i.cat); // { fruit: [...] }", "How did developers do this before ES2024?")
    ]
    for item in extra_items:
        q_text, ans, diff, qtype, code, mcq_opts, correct_opt, fup = parse_item(item)
        qs.append(make_q(
            f"q-es6-{num}", num, "ES6+", "Modern ES Standards", "ES2016 to ES2024",
            q_text, ans, difficulty=diff, question_type=qtype,
            code_example=code, follow_up=fup,
            mcq_options=mcq_opts, correct_option=correct_opt
        ))
        num += 1

    print(f"Built ES6+ pack: {len(qs)} questions (Target: >=200)")
    return qs
