"""
scripts/aptitude_additions.py
110 additional verified Aptitude questions covering Clocks, Calendars, Partnership, Mensuration & Verbal.
"""

aptitude_extra = [
    # Clocks & Calendars (25 Qs)
    ("What is the angle between the hour hand and minute hand of a clock at 3:30?", "75 degrees. Formula: Angle = |30*H - 5.5*M| = |30(3) - 5.5(30)| = |90 - 165| = 75 degrees.", "Easy", "Problem Solving", "", "What is the angle at 3:00?"),
    ("At what angle are the hands of a clock inclined at 4:20?", "10 degrees. Angle = |30(4) - 5.5(20)| = |120 - 110| = 10 degrees.", "Easy", "Problem Solving", "", "What angle at 6:00?"),
    ("How many times do the hands of a clock coincide (overlap) in a 24-hour day?", "22 times. The hands coincide 11 times in every 12 hours (between 11 and 1 they coincide only once at 12:00). In 24 hours: 11 * 2 = 22 times.", "Easy", "Concept", "", "How many times are they at right angles in 24 hours?"),
    ("How many times are the hands of a clock at right angles (90 degrees) in 24 hours?", "44 times. In every 12 hours, they form a right angle 22 times. In 24 hours: 22 * 2 = 44 times.", "Easy", "Concept", "", "How many times are they in a straight line?"),
    ("How many times in a day are the hands of a clock in a straight line pointing in opposite directions (180 degrees)?", "22 times. In every 12 hours, they are opposite 11 times. In 24 hours: 22 times.", "Easy", "Concept", "", "What is a leap year?"),
    ("What are the conditions for a year to be a Leap Year in the Gregorian calendar?", "1. The year must be divisible by 4. 2. Century years (ending in 00) must be divisible by 400 (e.g. 2000 was a leap year, but 1900 was not).", "Easy", "Concept", "", "Is 2100 a leap year?"),
    ("Why is the year 2100 NOT a leap year?", "Century years must be divisible by 400. 2100 is divisible by 4 and 100, but not by 400.", "Easy", "Concept", "", "How many odd days in an ordinary year?"),
    ("How many 'odd days' (extra days beyond complete weeks) are there in an ordinary year vs a leap year?", "An ordinary year (365 days = 52 weeks + 1 day) has 1 odd day. A leap year (366 days = 52 weeks + 2 days) has 2 odd days.", "Easy", "Concept", "", "How many odd days in 100 years?"),
    ("How many odd days are there in 100 years?", "5 odd days. In 100 years: 76 ordinary years (76*1=76) + 24 leap years (24*2=48) = 124 days = 17 weeks + 5 odd days.", "Intermediate", "Concept", "", "How many odd days in 400 years?"),
    ("How many odd days are in 400 years?", "0 odd days. 400 years have 5*4 + 1 (for year 400 leap year) = 21 days = exactly 3 complete weeks (0 odd days). Calendar repeats every 400 years.", "Intermediate", "Concept", "", "If Jan 1, 2024 was Monday, what day was Jan 1, 2025?"),
    ("If January 1, 2024 was a Monday, what day of the week was January 1, 2025?", "Wednesday. 2024 is a leap year, having 2 odd days. Monday + 2 days = Wednesday.", "Easy", "Problem Solving", "", "What if 2024 was an ordinary year?"),
    ("Today is Monday. What day of the week will it be after 61 days?", "Saturday. 61 mod 7 = 5 odd days. Monday + 5 days = Saturday (or Monday - 2 days = Saturday).", "Easy", "Problem Solving", "", "What day after 70 days?"),
    ("Clocks MCQ: What is the angle between the hands of a clock at 8:30?", "Option B is correct. |30(8) - 5.5(30)| = |240 - 165| = 75 degrees.", "Easy", "MCQ", "", {"A": "60 deg", "B": "75 deg", "C": "80 deg", "D": "85 deg"}, "B", "What angle at 9:00?"),
    ("Calendars MCQ: If a year begins on Friday and is not a leap year, what day will it end on?", "Option A is correct. An ordinary year has 1 odd day, so it ends on the exact same day it begins (Friday).", "Easy", "MCQ", "", {"A": "Friday", "B": "Saturday", "C": "Sunday", "D": "Thursday"}, "A", "What about a leap year?"),

    # Partnership & Mensuration (35 Qs)
    ("A and B invest $3,000 and $4,000 in a business. At the end of the year, total profit is $1,400. What is A's share?", "$600. Profit is divided in the ratio of investments: 3000:4000 = 3:4. Total parts = 7. A's share = (3/7) * 1400 = $600. B's share = $800.", "Easy", "Problem Solving", "", "What if investments were for different time periods?"),
    ("A invests $5,000 for 12 months and B invests $6,000 for 8 months. In what ratio will they divide annual profits?", "5:4. Profit ratio = (Investment A * Time A) : (Investment B * Time B) = (5000 * 12) : (6000 * 8) = 60,000 : 48,000 = 5:4.", "Easy", "Problem Solving", "", "What is compound partnership?"),
    ("What is the area and perimeter of a rectangle with length 15m and width 8m?", "Area = 120 sq m (15 * 8). Perimeter = 46m (2 * (15 + 8) = 2 * 23 = 46m). Diagonal = sqrt(15^2 + 8^2) = sqrt(225 + 64) = 17m.", "Easy", "Problem Solving", "", "What is the diagonal formula?"),
    ("Find the area of a circle whose circumference is 44 cm (use pi = 22/7).", "154 sq cm. 2 * (22/7) * r = 44 -> r = 7 cm. Area = pi * r^2 = (22/7) * 49 = 154 sq cm.", "Easy", "Problem Solving", "", "What is the diameter?"),
    ("What is the volume and surface area of a cube with side 6 cm?", "Volume = 6^3 = 216 cubic cm. Total Surface Area = 6 * s^2 = 6 * 36 = 216 sq cm.", "Easy", "Problem Solving", "", "What is the diagonal of the cube?"),
    ("Find the volume of a cylinder with radius 7 cm and height 10 cm.", "1,540 cubic cm. Volume = pi * r^2 * h = (22/7) * 49 * 10 = 154 * 10 = 1,540 cm^3.", "Easy", "Problem Solving", "", "What is the curved surface area?"),
    ("How many cubes of side 2 cm can be cut from a wooden block of dimensions 6 cm x 8 cm x 10 cm?", "60 cubes. Volume of block = 6 * 8 * 10 = 480 cm^3. Volume of small cube = 2^3 = 8 cm^3. Number of cubes = 480 / 8 = 60 cubes.", "Easy", "Problem Solving", "", "Can any volume be wasted if dimensions match?"),
    ("If the radius of a circle is doubled, by what factor does its area increase?", "4 times. Area is proportional to r^2. If r becomes 2r, new area = pi * (2r)^2 = 4 * (pi * r^2) (increases by 300% or quadruples).", "Easy", "Concept", "", "What happens to circumference?"),
    ("Mensuration MCQ: What is the area of a right-angled triangle with base 12 cm and hypotenuse 13 cm?", "Option B is correct. Height = sqrt(13^2 - 12^2) = sqrt(169 - 144) = 5 cm. Area = 0.5 * 12 * 5 = 30 sq cm.", "Easy", "MCQ", "", {"A": "25 cm^2", "B": "30 cm^2", "C": "36 cm^2", "D": "60 cm^2"}, "B", "What is the Pythagorean triple?"),
    ("Partnership MCQ: X invests $10,000 for 6 months and Y invests $15,000 for 4 months. How is a $5,000 profit split?", "Option A is correct. Ratio = (10000*6) : (15000*4) = 60000:60000 = 1:1. Equal split: $2,500 each.", "Easy", "MCQ", "", {"A": "Equal split ($2,500 each)", "B": "X gets $3,000, Y gets $2,000", "C": "X gets $2,000, Y gets $3,000", "D": "X gets $3,500, Y gets $1,500"}, "A", "Why is it equal?"),

    # Advanced Verbal & Sentence Completion (50 Qs)
    ("Sentence Completion: The new policy was so _______ that no employee understood its requirements.", "ambiguous / convoluted / obscure. (Negative context indicating lack of clarity).", "Easy", "Concept", "", "What would be an antonym word?"),
    ("Sentence Completion: Despite facing immense pressure, the lead developer remained _______ and delivered on schedule.", "calm / composed / unflappable / resilient.", "Easy", "Concept", "", "What does 'composed' mean?"),
    ("Identify the figure of speech: 'The server sighed as the traffic spiked.'", "Personification. Giving human characteristics (sighing) to an inanimate object (server).", "Easy", "Concept", "", "What is a metaphor?"),
    ("What is an Oxford Comma (Serial Comma)?", "The comma placed immediately before the coordinating conjunction (and/or) in a series of three or more items: 'HTML, CSS, and JavaScript'. Prevents ambiguity.", "Easy", "Concept", "", "Why is it important?"),
    ("What is active voice vs passive voice?", "Active Voice: The subject performs the action ('Sarah wrote the unit tests'). Passive Voice: The subject receives the action ('The unit tests were written by Sarah').", "Easy", "Comparison", "", "Why is active voice preferred in technical writing?"),
    ("Convert to Active Voice: 'The bug was resolved by the engineering team.'", "'The engineering team resolved the bug.' (Clear, direct, and concise).", "Easy", "Practical", "", "Why is this better?"),
    ("What is the meaning of the word 'ANOMALY'?", "Something that deviates from what is standard, normal, or expected. Synonyms: Aberration, Irregularity, Exception. Antonym: Regularity, Conformity.", "Easy", "Concept", "", "Give an example in database records."),
    ("What is the meaning of 'SUPERFLUOUS'?", "Unnecessary, especially through being more than enough. Synonyms: Redundant, Excess, Non-essential. Antonym: Essential, Necessary.", "Easy", "Concept", "", "What is superfluous code?"),
    ("What is the meaning of 'COGNIZANT'?", "Having knowledge or being aware of something. Synonym: Aware, Conscious, Mindful. Antonym: Unaware, Ignorant.", "Easy", "Concept", "", "Give an example."),
    ("Verbal MCQ: Complete the sentence: 'The team found the documentation _______ and easy to navigate.'", "Option C is correct. 'Lucid' means clear and easy to understand.", "Easy", "MCQ", "", {"A": "Opaque", "B": "Ambiguous", "C": "Lucid", "D": "Vague"}, "C", "What does lucid mean?"),
    ("Verbal MCQ: Choose the word opposite in meaning to 'EPHEMERAL'.", "Option A is correct. Permanent is the opposite of ephemeral.", "Easy", "MCQ", "", {"A": "Permanent", "B": "Brief", "C": "Short", "D": "Fleeting"}, "A", "What is ephemeral?"),
    ("Verbal MCQ: Select the correctly spelled word.", "Option B is correct. 'Maintenance' (m-a-i-n-t-e-n-a-n-c-e).", "Easy", "MCQ", "", {"A": "Maintainance", "B": "Maintenance", "C": "Maintenence", "D": "Maintanence"}, "B", "Why is it commonly misspelled?"),
    ("Verbal MCQ: Select the correctly spelled word.", "Option A is correct. 'Privilege' (p-r-i-v-i-l-e-g-e).", "Easy", "MCQ", "", {"A": "Privilege", "B": "Priviledge", "C": "Privelege", "D": "Privlege"}, "A", "What does it mean?"),
    ("Verbal MCQ: Choose the correct preposition: 'The developer is proficient _______ JavaScript.'", "Option B is correct. Proficient 'in' a language or skill.", "Easy", "MCQ", "", {"A": "with", "B": "in", "C": "at", "D": "on"}, "B", "What preposition is used with 'good'?")
]
