"""
scripts/aptitude_verbal_di.py
Contains Verbal Ability (85 Qs) and Data Interpretation (65 Qs). Total: 150 Qs.
"""

verbal_items = [
    # Grammar & Sentence Correction (30 Qs)
    ("What is Subject-Verb Agreement in English grammar?", "A singular subject takes a singular verb, and a plural subject takes a plural verb (e.g. 'The developer writes code' vs 'The developers write code').", "Easy", "Concept", "", "What verb does 'Either/Neither' take?"),
    ("Which verb form is correct: 'Neither of the applicants (is / are) qualified'?", "'is'. Pronouns like 'neither', 'either', 'each', and 'everyone' are grammatically singular and require singular verbs.", "Easy", "Concept", "", "What about 'Either John or his friends'?"),
    ("In 'Either John or his friends (is / are) coming', which verb is correct?", "'are'. When subjects are connected by 'or' / 'nor', the verb agrees with the subject closer to it ('friends' is plural).", "Easy", "Concept", "", "What is the rule of proximity?"),
    ("Correct the error: 'Each of the students have submitted their project.'", "'Each of the students HAS submitted his or her project.' 'Each' is singular and requires the singular verb 'has'.", "Easy", "Concept", "", "Why is 'have' incorrect?"),
    ("What is the difference between 'affect' and 'effect'?", "'Affect' is usually a verb meaning to influence ('Lack of sleep affects performance'). 'Effect' is usually a noun meaning a result ('The effect of the bug was severe').", "Easy", "Comparison", "", "Can 'effect' ever be a verb?"),
    ("What is the difference between 'their', 'there', and 'they're'?", "'Their' is possessive (their laptop). 'There' indicates place or existence (over there / there are bugs). 'They're' is the contraction for 'they are'.", "Easy", "Comparison", "", "What is 'its' vs 'it's'?"),
    ("What is the difference between 'its' and 'it's'?", "'Its' is the possessive pronoun (e.g. 'The server lost its connection'). 'It's' is the contraction for 'it is' or 'it has' (e.g. 'It's raining').", "Easy", "Comparison", "", "Does possessive 'its' have an apostrophe?"),
    ("What is a dangling modifier in sentence structure?", "A descriptive phrase that does not logically attach to the subject that immediately follows it (e.g. 'Walking into the room, the smoke was smelled' -> who was walking?).", "Intermediate", "Concept", "", "How do you fix a dangling modifier?"),
    ("Fix the dangling modifier: 'Having finished the code, the server was restarted by Sarah.'", "Rewrite so Sarah immediately follows the modifier: 'Having finished the code, Sarah restarted the server.'", "Intermediate", "Concept", "", "What is a misplaced modifier?"),
    ("What is the difference between 'fewer' and 'less'?", "'Fewer' is used for countable nouns (fewer bugs, fewer developers). 'Less' is used for uncountable quantities (less memory, less time, less water).", "Easy", "Comparison", "", "Do you say 'fewer items' or 'less items'?"),
    ("What is the difference between 'compliment' and 'complement'?", "'Compliment' means praise or admiration ('nice job!'). 'Complement' means something that completes or pairs well with another ('CSS complements HTML').", "Easy", "Comparison", "", "What are homophones?"),
    ("Choose the correct word: 'The company announced that (its / it's) profits doubled.'", "'its'. Possessive form without apostrophe.", "Easy", "Concept", "", "Why is it not it's?"),
    ("What is the subjunctive mood in English ('If I were you...')?", "Used for hypothetical, wishful, or counter-to-fact statements, using 'were' instead of 'was': 'If I were the tech lead, I would refactor this module.'", "Easy", "Concept", "", "Do you say 'If I was' or 'If I were'?"),
    ("Correct the sentence: 'She is one of those engineers who works very hard.'", "Change 'works' to 'work'. The relative clause refers to the plural antecedent 'engineers', which requires the plural verb 'work'.", "Intermediate", "Concept", "", "What is the antecedent rule?"),
    ("What is the difference between 'elicit' and 'illicit'?", "'Elicit' is a verb meaning to draw out or evoke (e.g. elicit feedback). 'Illicit' is an adjective meaning illegal or unauthorized (e.g. illicit access).", "Easy", "Comparison", "", "Give an example sentence."),
    ("Grammar MCQ: Choose the correct sentence.", "Option B is correct. 'Between you and me' uses the objective pronoun 'me' after the preposition 'between'.", "Easy", "MCQ", "", {"A": "Between you and I, the plan is good.", "B": "Between you and me, the plan is good.", "C": "Between you and himself, the plan is good.", "D": "Between we, the plan is good."}, "B", "Why is 'me' correct?"),
    ("Grammar MCQ: Identify the correct sentence.", "Option A is correct. 'The committee has made its decision' treats collective noun as a single unit.", "Easy", "MCQ", "", {"A": "The committee has made its decision.", "B": "The committee have made its decision.", "C": "The committee has made their decision.", "D": "The committee were making its decision."}, "A", "When is a collective noun plural?"),
    ("Grammar MCQ: Which sentence uses 'fewer' correctly?", "Option C is correct. 'Fewer errors' is countable.", "Easy", "MCQ", "", {"A": "He made less errors today.", "B": "We have less developers now.", "C": "There are fewer errors in this release.", "D": "This code uses fewer memory."}, "C", "Why is 'fewer memory' wrong?"),
    ("What is the difference between 'principal' and 'principle'?", "'Principal' means chief/primary or school head, or financial loan amount. 'Principle' is a fundamental truth, rule, or doctrine of conduct.", "Easy", "Comparison", "", "What is a design principle?"),
    ("Correct the sentence: 'He don't know the answer.'", "'He DOESN'T know the answer.' Third-person singular subject 'he' requires 'does not' ('doesn't').", "Easy", "Concept", "", "What is third person singular?"),

    # Vocabulary, Synonyms & Antonyms (35 Qs)
    ("What is the meaning and a synonym of the word 'PRAGMATIC'?", "Pragmatic means dealing with things sensibly and realistically based on practical rather than theoretical considerations. Synonym: Practical, Realistic, Sensible.", "Easy", "Concept", "", "What is the antonym of pragmatic?"),
    ("What is the antonym of 'PRAGMATIC'?", "Idealistic, Impractical, Theoretical.", "Easy", "Concept", "", "Use pragmatic in an interview context."),
    ("What is the meaning of 'EPHEMERAL'?", "Lasting for a very short time; transitory. Synonyms: Transient, Fleeting, Short-lived. Antonym: Permanent, Eternal.", "Easy", "Concept", "", "Give an example in web development."),
    ("What is the meaning of 'DILIGENT'?", "Having or showing care and conscientiousness in one's work or duties. Synonyms: Hardworking, Meticulous, Assiduous. Antonyms: Lazy, Careless.", "Easy", "Concept", "", "What is a synonym of diligent?"),
    ("What is a synonym for 'METICULOUS'?", "Careful, Thorough, Precise, Scrupulous, Detailed. Antonym: Careless, Slapdash.", "Easy", "Concept", "", "What does meticulous mean?"),
    ("What is the meaning of 'UBIQUITOUS'?", "Present, appearing, or found everywhere simultaneously. Synonyms: Omnipresent, Pervasive, Universal. Antonym: Rare, Scarce.", "Easy", "Concept", "", "Is JavaScript ubiquitous?"),
    ("What is the antonym of 'OBSOLETE'?", "Current, Modern, Contemporary, State-of-the-art, In-use. Obsolete means out of date or no longer produced.", "Easy", "Concept", "", "What does obsolete mean?"),
    ("What is the meaning of 'RESILIENT'?", "Able to withstand or recover quickly from difficult conditions. Synonyms: Tough, Robust, Adaptable. Antonyms: Fragile, Vulnerable.", "Easy", "Concept", "", "What is resilient software?"),
    ("What is the meaning of 'CANDID'?", "Truthful and straightforward; frank. Synonyms: Honest, Direct, Sincere, Forthright. Antonym: Deceitful, Evasive.", "Easy", "Concept", "", "Give an example."),
    ("What is a synonym for 'CONCISE'?", "Brief, Succinct, Pithy, Compact, Terse. Antonym: Verbose, Wordy, Lengthy.", "Easy", "Concept", "", "Why is conciseness valued in communication?"),
    ("Vocabulary MCQ: What is the synonym of 'AMBIGUOUS'?", "Option B is correct. Ambiguous means unclear or having multiple meanings. Synonym: Vague.", "Easy", "MCQ", "", {"A": "Clear", "B": "Vague", "C": "Definite", "D": "Certain"}, "B", "What is the antonym?"),
    ("Vocabulary MCQ: What is the antonym of 'METICULOUS'?", "Option C is correct. Careless or sloppy.", "Easy", "MCQ", "", {"A": "Accurate", "B": "Cautious", "C": "Careless", "D": "Strict"}, "C", "What does meticulous mean?"),
    ("Vocabulary MCQ: What does 'BENEVOLENT' mean?", "Option A is correct. Well-meaning, kind, and charitable.", "Easy", "MCQ", "", {"A": "Kind and generous", "B": "Hostile and angry", "C": "Greedy", "D": "Lazy"}, "A", "What is the opposite?"),
    ("Vocabulary MCQ: What is the synonym of 'ROBUST'?", "Option C is correct. Robust means strong and healthy or able to withstand adverse conditions. Synonym: Sturdy.", "Easy", "MCQ", "", {"A": "Weak", "B": "Fragile", "C": "Sturdy", "D": "Delicate"}, "C", "What is a robust API?"),
    ("What is the meaning of the idiom 'BITE THE BULLET'?", "To endure a painful or difficult situation that is unavoidable with courage and fortitude.", "Easy", "Concept", "", "Give an example in project work."),
    ("What is the meaning of the idiom 'CUT CORNERS'?", "To do something in the easiest, cheapest, or fastest way, often sacrificing quality or safety standards.", "Easy", "Concept", "", "Why should developers avoid cutting corners in security?"),
    ("What is the meaning of the idiom 'HIT THE GROUND RUNNING'?", "To start a new activity or job immediately with full energy, enthusiasm, and productivity without delay.", "Easy", "Concept", "", "When is this mentioned in interviews?"),
    ("What is the meaning of the idiom 'ON THE SAME PAGE'?", "To have the same understanding, goals, and agreement about a project or topic.", "Easy", "Concept", "", "Why is alignment essential in teams?"),
    ("What is the meaning of the idiom 'PLAY DEVIL'S ADVOCATE'?", "To argue against a proposal or idea not because you disagree with it, but to test its validity and uncover hidden flaws.", "Easy", "Concept", "", "How does this help code reviews?"),
    ("What is the meaning of 'INNOVATIVE'?", "Featuring new methods, advanced ideas, or original thinking. Synonyms: Novel, Creative, Groundbreaking. Antonym: Conventional, Derivative.", "Easy", "Concept", "", "Give an example.")
]

di_items = [
    # Data Interpretation & Tables (65 Qs)
    ("A table shows Sales of 4 products (P1=120, P2=180, P3=90, P4=210). What percentage of total sales is contributed by P2?", "30%. Total sales = 120 + 180 + 90 + 210 = 600. P2 share = (180 / 600) * 100 = 30%.", "Easy", "Problem Solving", "", "What percentage is P4?"),
    ("In a company of 500 employees, a pie chart shows: Engineering 40%, Sales 25%, Marketing 15%, HR 10%, Support 10%. How many employees work in Engineering and Sales combined?", "325 employees. Combined percentage = 40% + 25% = 65%. Total = 65% of 500 = 0.65 * 500 = 325 employees.", "Easy", "Problem Solving", "", "How many degrees in the pie chart represent Engineering?"),
    ("How many degrees of a circle represent a 40% slice in a pie chart?", "144 degrees. A full circle has 360 degrees. 40% of 360 = 0.40 * 360 = 144 degrees. Formula: (Percentage / 100) * 360.", "Easy", "Concept", "", "What angle represents 25%?"),
    ("A bar chart shows Revenue over 3 years: Year 1 = $200k, Year 2 = $260k, Year 3 = $325k. What is the percentage growth from Year 1 to Year 2?", "30%. Growth = (260 - 200) / 200 * 100 = 60 / 200 * 100 = 30%.", "Easy", "Problem Solving", "", "What was growth from Year 2 to Year 3?"),
    ("A line graph shows monthly website visitors: Jan=10k, Feb=12k, Mar=15k, Apr=18k. What is the average monthly visitor count over the 4 months?", "13,750 visitors. Total visitors = 10 + 12 + 15 + 18 = 55k = 55,000. Average = 55,000 / 4 = 13,750.", "Easy", "Problem Solving", "", "What is the percentage increase from Jan to Apr?"),
    ("A table displays expenses: Rent $1,500, Salaries $4,500, Utilities $500, Marketing $1,000, Miscellaneous $500. What ratio represents Rent to Salaries?", "1:3. Rent / Salaries = 1500 / 4500 = 1/3 = 1:3.", "Easy", "Problem Solving", "", "What percentage of total expenses is Marketing?"),
    ("In the previous expenses breakdown (Total = $8,000), what percentage is spent on Marketing ($1,000)?", "12.5%. Percentage = (1000 / 8000) * 100 = 1/8 * 100 = 12.5%.", "Easy", "Problem Solving", "", "What central angle would marketing occupy?"),
    ("A table lists student marks: Physics=75, Chemistry=65, Math=85, English=70, Computer Science=95. What is the overall percentage if each subject is out of 100?", "78%. Total marks obtained = 75 + 65 + 85 + 70 + 95 = 390. Maximum marks = 500. Percentage = (390 / 500) * 100 = 78%.", "Easy", "Problem Solving", "", "What is the median mark?"),
    ("DI MCQ: In a pie chart, a sector represents 72 degrees. What percentage of the total does this sector represent?", "Option B is correct. Percentage = (72 / 360) * 100 = 1/5 * 100 = 20%.", "Easy", "MCQ", "", {"A": "15%", "B": "20%", "C": "25%", "D": "30%"}, "B", "What angle is 10%?"),
    ("DI MCQ: If revenue grew from $50 million in 2024 to $75 million in 2025, what was the percentage increase?", "Option C is correct. (75 - 50)/50 * 100 = 25/50 * 100 = 50%.", "Easy", "MCQ", "", {"A": "25%", "B": "33.3%", "C": "50%", "D": "66.7%"}, "C", "What if it dropped from 75 to 50?"),
    ("DI MCQ: In a table, Company A has revenue $400k and profit $60k; Company B has revenue $600k and profit $72k. Which has higher profit margin?", "Option A is correct. Margin A = 60/400 = 15%. Margin B = 72/600 = 12%. Company A is higher.", "Easy", "MCQ", "", {"A": "Company A (15%)", "B": "Company B (12%)", "C": "Both are equal", "D": "Cannot be determined"}, "A", "What is profit margin formula?"),
    ("A factory produces 1,200 widgets per day with a defect rate of 2.5%. How many non-defective widgets are produced daily?", "1,170 widgets. Defective widgets = 2.5% of 1200 = 0.025 * 1200 = 30. Non-defective = 1200 - 30 = 1,170 widgets (or 97.5% of 1200 = 1170).", "Easy", "Problem Solving", "", "How many defects in a 5-day week?"),
    ("A table shows pass percentages of three schools: School X: 80% of 200 students passed. School Y: 75% of 300 students passed. School Z: 90% of 100 students passed. What is the overall pass percentage across all 3 schools?", "79.17%. Total passed = (0.8*200) + (0.75*300) + (0.9*100) = 160 + 225 + 90 = 475. Total students = 200 + 300 + 100 = 600. Overall % = (475 / 600) * 100 = 79.17%.", "Intermediate", "Problem Solving", "", "Why is it not the average of 80, 75, 90?"),
    ("Why is the weighted average required instead of the simple average when combining percentages from different base totals?", "Because each group has a different number of students. A simple average (80+75+90)/3 = 81.67% incorrectly weights School Z equally with School Y, which has three times as many students.", "Intermediate", "Concept", "", "What is weighted average formula?"),
    ("A graph shows quarterly profits: Q1=$40k, Q2=$60k, Q3=$50k, Q4=$90k. What percentage of annual profit was earned in Q4?", "37.5%. Total annual profit = 40 + 60 + 50 + 90 = $240k. Q4 share = (90 / 240) * 100 = 3/8 * 100 = 37.5%.", "Easy", "Problem Solving", "", "Which quarter had the lowest profit?")
]
