"""
scripts/dsa_questions_part3.py
190 verified questions for Stacks, Queues, Linked Lists, Trees, BST, Graphs, Sorting & Searching.
"""

dsa_stacks_queues = [
    # Stacks & Queues (40 Qs)
    ("What is a Stack and what principle does it follow?", "A Stack is a linear data structure following the LIFO (Last In, First Out) principle: the last element added is the first one removed.", "Easy", "Concept", "const stack = [];\nstack.push(1); // Push\nconst top = stack.pop(); // Pop", "What are the core operations on a stack?"),
    ("What are the primary operations of a Stack and their time complexities?", "push(x): add to top (O(1)). pop(): remove from top (O(1)). peek() / top(): view top element without removing (O(1)). isEmpty(): check if empty (O(1)).", "Easy", "Concept", "", "What is Stack Overflow in recursion?"),
    ("What is Stack Overflow?", "A runtime error that occurs when the call stack memory limit is exceeded, typically caused by infinite recursion without a valid base case.", "Easy", "Concept", "", "What is the Valid Parentheses problem?"),
    ("How do you solve the Valid Parentheses problem (e.g. '({[]})') using a Stack?", "Iterate through characters: push opening brackets onto the stack. For closing brackets, check if stack is non-empty and top matches; if yes, pop; else invalid. At end, stack must be empty.", "Easy", "Problem Solving", "function isValid(s) {\n  const stack = [];\n  const map = { ')': '(', '}': '{', ']': '[' };\n  for (const c of s) {\n    if (c in map) {\n      if (stack.pop() !== map[c]) return false;\n    } else stack.push(c);\n  }\n  return stack.length === 0;\n}", "What is the time and space complexity?"),
    ("What is Min Stack (Stack with getMin() in O(1) time)?", "A stack that supports push, pop, top, and retrieving the minimum element in constant O(1) time by maintaining an auxiliary stack of minimums.", "Intermediate", "Concept", "class MinStack {\n  constructor() { this.stack = []; this.minStack = []; }\n  push(val) {\n    this.stack.push(val);\n    const min = this.minStack.length === 0 ? val : Math.min(val, this.getMin());\n    this.minStack.push(min);\n  }\n  pop() { this.stack.pop(); this.minStack.pop(); }\n  top() { return this.stack[this.stack.length - 1]; }\n  getMin() { return this.minStack[this.minStack.length - 1]; }\n}", "How does the auxiliary stack track minimums?"),
    ("What is a Queue and what principle does it follow?", "A Queue is a linear data structure following the FIFO (First In, First Out) principle: the first element added is the first one to be removed.", "Easy", "Concept", "", "What are the primary operations on a Queue?"),
    ("What are the core Queue operations and their time complexities?", "enqueue(x): add element to the rear/back (O(1)). dequeue(): remove element from the front (O(1)). peek(): inspect front element (O(1)). isEmpty(): check if empty (O(1)).", "Easy", "Concept", "", "Why is implementing a queue using a JavaScript Array with arr.shift() inefficient?"),
    ("Why is array.shift() inefficient for implementing Queues in JavaScript?", "arr.shift() takes O(n) linear time because all remaining elements must shift down in memory. A proper queue should use a linked list or circular buffer for O(1) dequeue.", "Easy", "Comparison", "", "What is a Circular Queue and what problem does it solve?"),
    ("What is a Circular Queue and how does it avoid memory wastage?", "A queue where the last position connects back to the first position in a circular ring, reusing freed front slots using modulo arithmetic: (rear + 1) % capacity.", "Intermediate", "Concept", "", "How do you implement a Queue using two Stacks?"),
    ("How do you implement a FIFO Queue using two LIFO Stacks (stackIn, stackOut)?", "enqueue: Push to stackIn. dequeue: If stackOut is empty, pop all elements from stackIn and push to stackOut (reversing their order). Pop from stackOut in amortized O(1) time!", "Intermediate", "Problem Solving", "class MyQueue {\n  constructor() { this.in = []; this.out = []; }\n  push(x) { this.in.push(x); }\n  pop() {\n    if (!this.out.length) while (this.in.length) this.out.push(this.in.pop());\n    return this.out.pop();\n  }\n}", "What is the amortized time of pop?"),
    ("What is a Deque (Double-Ended Queue)?", "A generalized queue that allows insertion and deletion of elements at BOTH the front and the rear in O(1) constant time.", "Easy", "Concept", "", "What is a Priority Queue?"),
    ("What is a Priority Queue and what data structure implements it efficiently?", "An abstract data structure where each element has a priority; elements with higher priority are dequeued before lower priority ones. Implemented efficiently using a Binary Heap in O(log n) time.", "Intermediate", "Concept", "", "Stack MCQ: Which principle governs the order of operations in a Stack?"),
    ("Stack MCQ: What data structure principle does a Stack follow?", "Option A is correct. LIFO (Last In, First Out).", "Easy", "MCQ", "", {"A": "LIFO", "B": "FIFO", "C": "LILO", "D": "Random"}, "A", "What principle does Queue follow?"),
    ("Queue MCQ: Which operation removes an element from the front of a Queue?", "Option B is correct. Dequeue removes from front.", "Easy", "MCQ", "", {"A": "Enqueue", "B": "Dequeue", "C": "Push", "D": "Pop"}, "B", "Where does enqueue add?")
]

dsa_linked_lists = [
    # Linked Lists (40 Qs)
    ("What is a Singly Linked List and what are its components?", "A linear data structure where elements (nodes) are stored non-contiguously in memory; each node contains a value and a pointer (next) to the next node in the sequence.", "Easy", "Concept", "class ListNode {\n  constructor(val, next = null) {\n    this.val = val;\n    this.next = next;\n  }\n}", "What does the tail node's next pointer point to?"),
    ("What does the 'next' pointer of the tail node in a singly linked list point to?", "null, indicating the end of the list.", "Easy", "Concept", "", "What are the advantages of Linked Lists over Arrays?"),
    ("What are the advantages of Linked Lists over static Arrays?", "1. Dynamic size (allocates nodes on demand without pre-allocation). 2. O(1) insertion and deletion at the head without shifting remaining elements.", "Easy", "Comparison", "", "What are the disadvantages of Linked Lists compared to Arrays?"),
    ("What are the disadvantages of Linked Lists compared to Arrays?", "1. No O(1) random access (searching requires O(n) traversal). 2. Extra memory overhead for storing pointer references. 3. Poor CPU cache locality due to scattered memory.", "Easy", "Comparison", "", "What is a Doubly Linked List?"),
    ("What is a Doubly Linked List and how does it differ from a Singly Linked List?", "Each node contains TWO pointers: 'next' (points to subsequent node) and 'prev' (points to previous node), enabling bidirectional traversal.", "Easy", "Concept", "class DoublyNode {\n  constructor(val) { this.val = val; this.prev = null; this.next = null; }\n}", "What is the memory trade-off of a Doubly Linked List?"),
    ("How do you Reverse a Singly Linked List iteratively in O(n) time and O(1) space?", "Use three pointers: prev = null, curr = head, next = null. In a loop: next = curr.next, curr.next = prev, prev = curr, curr = next. Return prev as new head.", "Easy", "Problem Solving", "function reverseList(head) {\n  let prev = null, curr = head;\n  while (curr) {\n    const next = curr.next;\n    curr.next = prev;\n    prev = curr;\n    curr = next;\n  }\n  return prev;\n}", "Can this be done recursively?"),
    ("How do you find the Middle Node of a Singly Linked List in a single pass?", "Use the Tortoise and Hare approach: slow pointer moves 1 step, fast pointer moves 2 steps. When fast reaches the end (fast === null || fast.next === null), slow is at the exact middle!", "Easy", "Problem Solving", "let slow = head, fast = head;\nwhile (fast && fast.next) {\n  slow = slow.next;\n  fast = fast.next.next;\n}\nreturn slow; // Middle node!", "Why is this single-pass?"),
    ("How do you detect if a Linked List has a cycle (Floyd's Cycle Detection)?", "Slow pointer moves 1 step, fast pointer moves 2 steps. If fast meets slow, a cycle exists (return true). If fast reaches null, no cycle exists.", "Easy", "Problem Solving", "let slow = head, fast = head;\nwhile (fast && fast.next) {\n  slow = slow.next;\n  fast = fast.next.next;\n  if (slow === fast) return true; // Cycle detected!\n}\nreturn false;", "How do you find the starting node of the cycle?"),
    ("How do you find the starting node of a cycle in a linked list?", "After slow and fast meet, reset slow to head. Move both slow and fast 1 step at a time; the node where they meet again is the entry point of the cycle.", "Intermediate", "Concept", "", "How do you merge two sorted linked lists into one sorted list?", "Use a dummy head node. Compare heads of both lists, attach the smaller node to the merged tail, advance pointer, and attach any remaining nodes at end.", "Easy", "Problem Solving", "const dummy = new ListNode(0);\nlet tail = dummy;\nwhile (l1 && l2) {\n  if (l1.val < l2.val) { tail.next = l1; l1 = l1.next; }\n  else { tail.next = l2; l2 = l2.next; }\n  tail = tail.next;\n}\ntail.next = l1 || l2;\nreturn dummy.next;", "Why use a dummy node?"),
    ("Why is using a Sentinel / Dummy Node a standard best practice in linked list manipulation?", "It eliminates special edge-case handling for the head node (like inserting into an empty list or deleting the head), making pointer logic clean and bug-free.", "Easy", "Best Practice", "", "How do you remove the Nth node from the end of a linked list in one pass?"),
    ("How do you remove the Nth node from the end of a linked list in a single pass?", "Use two pointers separated by n steps. Advance both together until the first pointer reaches the end; the second pointer is now right before the target node to delete.", "Intermediate", "Problem Solving", "", "Linked List MCQ: What is the time complexity to insert a node at the head of a linked list?"),
    ("Linked List MCQ: What is the time complexity of inserting a node at the beginning of a singly linked list?", "Option A is correct. O(1) constant time (new Node -> head).", "Easy", "MCQ", "", {"A": "O(1)", "B": "O(n)", "C": "O(log n)", "D": "O(n^2)"}, "A", "What is insertion at the tail without tail pointer?"),
    ("Linked List MCQ: Which technique detects cycles in a linked list using O(1) space?", "Option C is correct. Floyd's cycle-finding algorithm (two pointers).", "Easy", "MCQ", "", {"A": "Binary Search", "B": "Breadth First Search", "C": "Floyd's Tortoise and Hare", "D": "Divide and Conquer"}, "C", "What space does storing visited nodes in a Set take?")
]

dsa_trees_bst = [
    # Trees & Binary Search Trees (40 Qs)
    ("What is a Binary Tree?", "A hierarchical tree data structure in which each node has at most two children, referred to as the left child and the right child.", "Easy", "Concept", "class TreeNode {\n  constructor(val) { this.val = val; this.left = null; this.right = null; }\n}", "What is the root node?"),
    ("What is a Binary Search Tree (BST)?", "A binary tree with the BST property: for every node, all values in its left subtree are strictly LESS than the node's value, and all values in its right subtree are strictly GREATER.", "Easy", "Concept", "", "What is the time complexity of search in a BST?"),
    ("What is the time complexity of search, insert, and delete in a balanced BST vs skewed BST?", "Balanced BST (AVL, Red-Black): O(log n) time. Skewed / Degenerate BST (linked list shape): O(n) worst-case time.", "Easy", "Comparison", "", "What are the 3 Depth-First Search (DFS) tree traversals?"),
    ("What are the 3 standard DFS tree traversals?", "1. Inorder: Left -> Root -> Right. 2. Preorder: Root -> Left -> Right. 3. Postorder: Left -> Right -> Root.", "Easy", "Concept", "", "What is unique about Inorder Traversal of a Binary Search Tree?"),
    ("What is the special property of Inorder Traversal on a Binary Search Tree?", "Inorder traversal of a BST visits nodes in strictly ASCENDING sorted order!", "Easy", "Concept", "function inorder(root) {\n  if (!root) return;\n  inorder(root.left);\n  console.log(root.val); // Sorted output!\n  inorder(root.right);\n}", "How do you validate if a tree is a valid BST?"),
    ("How do you validate whether a binary tree is a valid Binary Search Tree?", "Pass valid range [min, max] down the recursive calls. Root must satisfy min < root.val < max; left child must satisfy (min, root.val); right child must satisfy (root.val, max).", "Intermediate", "Problem Solving", "function isValidBST(root, min = -Infinity, max = Infinity) {\n  if (!root) return true;\n  if (root.val <= min || root.val >= max) return false;\n  return isValidBST(root.left, min, root.val) && isValidBST(root.right, root.val, max);\n}", "Why is checking root.left.val < root.val alone insufficient?"),
    ("Why is checking only immediate children (root.left.val < root.val) insufficient to validate a BST?", "Because a node in the right subtree might have a child smaller than the tree's global root, violating the global BST property.", "Intermediate", "Concept", "", "What is Breadth-First Search (Level-Order Traversal) of a binary tree?"),
    ("What is Level-Order Traversal (BFS) and what data structure is used to implement it?", "Traversing the tree level-by-level from top to bottom, left to right. Implemented iteratively using a FIFO Queue.", "Easy", "Concept", "function levelOrder(root) {\n  if (!root) return [];\n  const queue = [root], result = [];\n  while (queue.length) {\n    const node = queue.shift();\n    result.push(node.val);\n    if (node.left) queue.push(node.left);\n    if (node.right) queue.push(node.right);\n  }\n  return result;\n}", "What is the time complexity of Level Order Traversal?"),
    ("What is the Maximum Depth (Height) of a binary tree?", "The number of nodes along the longest path from the root node down to the farthest leaf node: 1 + Math.max(maxDepth(left), maxDepth(right)).", "Easy", "Problem Solving", "const maxDepth = root => !root ? 0 : 1 + Math.max(maxDepth(root.left), maxDepth(root.right));", "What is an empty tree height?"),
    ("What is Lowest Common Ancestor (LCA) in a BST?", "In a BST, starting from root: if both p and q are smaller than root, LCA is in left subtree. If both are larger, LCA is in right subtree. If they split, current root IS the LCA!", "Intermediate", "Problem Solving", "function lowestCommonAncestor(root, p, q) {\n  if (p.val < root.val && q.val < root.val) return lowestCommonAncestor(root.left, p, q);\n  if (p.val > root.val && q.val > root.val) return lowestCommonAncestor(root.right, p, q);\n  return root; // Split point is LCA!\n}", "What is LCA in a general binary tree?"),
    ("What is a Complete Binary Tree vs a Full Binary Tree?", "Full Binary Tree: Every node has either 0 or 2 children. Complete Binary Tree: All levels are completely filled except possibly the last level, which is filled from left to right.", "Intermediate", "Comparison", "", "What is a Balanced Binary Tree (AVL tree)?"),
    ("What is a Balanced Binary Tree?", "A tree where for every node, the height difference (balance factor) between left and right subtrees is at most 1, guaranteeing O(log n) operations.", "Intermediate", "Concept", "", "Trees MCQ: Which traversal of a Binary Search Tree outputs values in sorted ascending order?"),
    ("Trees MCQ: Which traversal produces sorted values from a BST?", "Option B is correct. Inorder traversal (Left, Root, Right) outputs sorted keys.", "Easy", "MCQ", "", {"A": "Preorder", "B": "Inorder", "C": "Postorder", "D": "Level-order"}, "B", "What does Preorder visit first?"),
    ("Trees MCQ: What data structure is used to perform Level-Order traversal of a tree?", "Option B is correct. A Queue is used for BFS level-order traversal.", "Easy", "MCQ", "", {"A": "Stack", "B": "Queue", "C": "Priority Queue", "D": "Hash Map"}, "B", "What data structure is used for DFS traversal?")
]

dsa_sorting_searching = [
    # Sorting & Searching Algorithms (40 Qs)
    ("What is Binary Search and what prerequisite must the input array satisfy?", "An efficient search algorithm that finds the position of a target value within a SORTED array by repeatedly halving the search interval in O(log n) time.", "Easy", "Concept", "let l = 0, r = arr.length - 1;\nwhile (l <= r) {\n  const mid = Math.floor(l + (r - l) / 2);\n  if (arr[mid] === target) return mid;\n  if (arr[mid] < target) l = mid + 1;\n  else r = mid - 1;\n}", "Why use l + (r - l) / 2 instead of (l + r) / 2?"),
    ("Why should 'mid = l + (r - l) / 2' be used instead of '(l + r) / 2'?", "In languages with fixed-size integers (C++, Java), (l + r) can cause integer overflow if sum exceeds 2^31 - 1. l + (r - l)/2 is overflow-safe.", "Easy", "Best Practice", "", "How does Bubble Sort work and what is its time complexity?", "Repeatedly steps through the list, compares adjacent elements, and swaps them if in wrong order. Best: O(n) with swap flag. Average & Worst: O(n^2). Space: O(1).", "Easy", "Concept", "", "How does Selection Sort work?"),
    ("How does Selection Sort work and what is its time complexity?", "Finds the minimum element from the unsorted part and swaps it with the first unsorted element. Time: O(n^2) in all cases (best, average, worst). Space: O(1).", "Easy", "Concept", "", "How does Insertion Sort work?"),
    ("How does Insertion Sort work and when is it particularly fast?", "Builds the sorted array one element at a time by inserting each element into its proper position among previously sorted elements. O(n) best-case for nearly sorted arrays.", "Easy", "Concept", "", "How does Merge Sort work and what is its time and space complexity?"),
    ("What is Merge Sort and what are its time and space complexities?", "A divide-and-conquer algorithm that recursively splits the array into two halves, sorts each half, and merges the sorted halves. Time: O(n log n) in all cases. Auxiliary Space: O(n).", "Easy", "Concept", "", "Is Merge Sort stable?"),
    ("Is Merge Sort a stable sort?", "Yes! When merging two sub-arrays, if two elements are equal, the element from the left sub-array is chosen first, preserving original relative order.", "Easy", "Concept", "", "How does Quick Sort work and what is its worst-case time complexity?"),
    ("How does Quick Sort work and when does worst-case O(n^2) occur?", "Picks a 'pivot', partitions elements into those smaller and larger than pivot, and recursively sorts partitions. Average: O(n log n). Worst: O(n^2) when pivot is always smallest/largest element (e.g. sorted array with first element as pivot).", "Intermediate", "Concept", "", "How do you avoid Quick Sort's worst-case O(n^2)?"),
    ("How do you prevent Quick Sort from degrading to O(n^2)?", "1. Choose pivot randomly (Randomized Quick Sort). 2. Use median-of-three pivot selection (median of first, middle, and last elements).", "Intermediate", "Best Practice", "", "What is TimSort in modern programming languages?"),
    ("What is TimSort and where is it used?", "A hybrid stable sorting algorithm combining Merge Sort and Insertion Sort. Used as the default sorting algorithm in Python, Java, and modern JavaScript engines (V8).", "Intermediate", "Concept", "", "Sorting MCQ: What is the worst-case time complexity of Merge Sort?"),
    ("Sorting MCQ: What is the time complexity of Merge Sort in the worst case?", "Option C is correct. Merge Sort is always O(n log n).", "Easy", "MCQ", "", {"A": "O(n)", "B": "O(n^2)", "C": "O(n log n)", "D": "O(2^n)"}, "C", "What is its space complexity?"),
    ("Sorting MCQ: Which sorting algorithm has an O(n) best-case time complexity on already-sorted input?", "Option A is correct. Insertion Sort runs in O(n) on sorted arrays.", "Easy", "MCQ", "", {"A": "Insertion Sort", "B": "Selection Sort", "C": "Merge Sort", "D": "Heap Sort"}, "A", "Why is it O(n)?")
]
