"""
scripts/dsa_questions_part2.py
90 verified questions for Arrays, Strings, Hash Tables, Sets, Two Pointers & Sliding Window.
"""

dsa_arrays_strings = [
    # Arrays & Strings (50 Qs)
    ("What is an Array and how is memory allocated for static arrays?", "An array is a linear data structure that stores elements of the same data type in contiguous memory locations, enabling O(1) random index access.", "Easy", "Concept", "", "Why are arrays contiguous in memory?"),
    ("Why does contiguous memory allocation allow O(1) random access in arrays?", "The memory address of arr[i] is computed directly via a mathematical offset: Base_Address + (i * Element_Size), requiring zero traversal.", "Easy", "Concept", "", "What is a Dynamic Array?"),
    ("How does a Dynamic Array (e.g. JavaScript Array, Java ArrayList) handle resizing?", "When capacity is reached, it allocates a new internal array of double capacity (2x), copies all existing elements, and frees the old array (amortized O(1) append).", "Intermediate", "Concept", "", "What is the time complexity of array search in unsorted vs sorted arrays?"),
    ("What is the time complexity of searching an element in an unsorted array vs a sorted array?", "Unsorted array: O(n) linear search. Sorted array: O(log n) binary search.", "Easy", "Comparison", "", "What is the Two Sum problem?"),
    ("How do you solve the Two Sum problem in O(n) time using a Hash Map?", "Iterate through the array; for each number x, check if (target - x) is present in the hash map. If yes, return indices; otherwise, store x and its index.", "Easy", "Concept", "function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const comp = target - nums[i];\n    if (map.has(comp)) return [map.get(comp), i];\n    map.set(nums[i], i);\n  }\n}", "What is the brute-force time complexity of Two Sum?"),
    ("What is the brute force time and space complexity of Two Sum?", "Time: O(n^2) using nested loops. Space: O(1). The hash map approach trades O(n) space to achieve O(n) time.", "Easy", "Comparison", "", "What is Dutch National Flag algorithm (Sort Colors 0, 1, 2)?"),
    ("What is the Dutch National Flag algorithm and how does it sort an array of 0s, 1s, and 2s in O(n) time and O(1) space?", "It maintains three pointers: low, mid, and high. Swap 0s to low, 2s to high, leaving 1s in the middle in a single pass.", "Intermediate", "Concept", "let low = 0, mid = 0, high = arr.length - 1;\nwhile (mid <= high) {\n  if (arr[mid] === 0) { [arr[low], arr[mid]] = [arr[mid], arr[low]]; low++; mid++; }\n  else if (arr[mid] === 1) { mid++; }\n  else { [arr[mid], arr[high]] = [arr[high], arr[mid]]; high--; }\n}", "Why is this single-pass?"),
    ("How do you rotate an array to the right by k steps in O(n) time and O(1) extra space?", "1. Normalize k = k % n. 2. Reverse the entire array. 3. Reverse the first k elements. 4. Reverse the remaining n-k elements.", "Intermediate", "Concept", "const rotate = (arr, k) => {\n  k = k % arr.length;\n  reverse(arr, 0, arr.length - 1);\n  reverse(arr, 0, k - 1);\n  reverse(arr, k, arr.length - 1);\n};", "Why does triple reverse rotate an array?"),
    ("How do you find the missing number in an array of numbers from 1 to n of size n-1?", "Calculate expected sum S = n * (n + 1) / 2. Sum the actual array elements. Missing number = Expected_Sum - Actual_Sum.", "Easy", "Problem Solving", "const missing = (n * (n + 1) / 2) - arr.reduce((a, b) => a + b, 0);", "How can this be solved with XOR to prevent integer overflow?"),
    ("How does XOR solve the missing number problem without integer overflow?", "XOR all numbers from 1 to n, and XOR all numbers in the array. Since x ^ x = 0 and x ^ 0 = x, duplicate numbers cancel out, leaving the missing number!", "Intermediate", "Concept", "let xor = 0;\nfor (let i = 1; i <= n; i++) xor ^= i;\nfor (const num of arr) xor ^= num;\nreturn xor; // Missing number!", "Why is XOR overflow-safe?"),
    ("How do you remove duplicates from a sorted array in-place?", "Use two pointers: slow pointer i tracks unique elements, fast pointer j scans. When arr[j] != arr[i], increment i and assign arr[i] = arr[j]. Returns length i+1.", "Easy", "Problem Solving", "let i = 0;\nfor (let j = 1; j < arr.length; j++) {\n  if (arr[j] !== arr[i]) { i++; arr[i] = arr[j]; }\n}\nreturn i + 1;", "Does this work on unsorted arrays?"),
    ("Can the two-pointer in-place deduplication work on unsorted arrays?", "No. Elements must be sorted so duplicates are contiguous. For unsorted arrays, use a Set in O(n) space.", "Easy", "Concept", "", "What is an Anagram in strings?"),
    ("What is an Anagram and how do you check if two strings are anagrams in O(n) time?", "Two strings are anagrams if they contain the exact same characters with identical frequencies. Count frequencies using a hash map or 26-element array in O(n) time.", "Easy", "Concept", "function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  const count = {};\n  for (const c of s) count[c] = (count[c] || 0) + 1;\n  for (const c of t) {\n    if (!count[c]) return false;\n    count[c]--;\n  }\n  return true;\n}", "What is the time complexity of sorting both strings to check anagrams?"),
    ("What is the time complexity of checking anagrams by sorting both strings?", "O(n log n) where n is string length. Using a character frequency hash map is faster at O(n) time.", "Easy", "Comparison", "", "What is a Palindrome and how do you verify one in O(n) time and O(1) space?", "A word that reads the same backward as forward (e.g. 'racecar'). Use two pointers starting at opposite ends moving inward, checking equality of characters.", "Easy", "Concept", "function isPalindrome(s) {\n  let l = 0, r = s.length - 1;\n  while (l < r) {\n    if (s[l] !== s[r]) return false;\n    l++; r--;\n  }\n  return true;\n}", "Does this check ignore case and punctuation?"),
    ("How do you find the first non-repeating character in a string?", "Perform two passes: Pass 1: Build a frequency map of all characters in O(n). Pass 2: Iterate through the string and return the first character with count 1.", "Easy", "Problem Solving", "function firstUniqChar(s) {\n  const count = {};\n  for (const c of s) count[c] = (count[c] || 0) + 1;\n  for (let i = 0; i < s.length; i++) {\n    if (count[s[i]] === 1) return i;\n  }\n  return -1;\n}", "What is the space complexity of this character map?"),
    ("What is the space complexity of storing character counts of ASCII strings?", "O(1) constant auxiliary space, because the alphabet size is bounded (at most 256 ASCII characters or 26 lowercase English letters).", "Easy", "Concept", "", "What is Longest Common Prefix problem?"),
    ("How do you find the Longest Common Prefix among an array of strings?", "Horizontal scanning: Take the first string as prefix, compare with each subsequent string, trimming the prefix until it matches the beginning of each string.", "Easy", "Problem Solving", "let prefix = strs[0];\nfor (let i = 1; i < strs.length; i++) {\n  while (strs[i].indexOf(prefix) !== 0) {\n    prefix = prefix.substring(0, prefix.length - 1);\n  }\n}", "What is the vertical scanning alternative?"),
    ("What is String Compression (Run-Length Encoding)?", "Replacing consecutive repeated characters with the character followed by its count (e.g. 'aabcccccaaa' -> 'a2b1c5a3').", "Easy", "Concept", "", "When should run-length encoding NOT be used?"),
    ("When should Run-Length Encoding NOT be used for compression?", "When characters rarely repeat consecutively (e.g. 'abcdef' -> 'a1b1c1d1e1f1'), doubling the string length and causing negative compression.", "Easy", "Concept", "", "Arrays MCQ: What is the time complexity of searching an element in an unsorted array of n elements?"),
    ("Arrays MCQ: What is the worst-case time to find an element in an unsorted array?", "Option C is correct. Linear scan takes O(n) time.", "Easy", "MCQ", "", {"A": "O(1)", "B": "O(log n)", "C": "O(n)", "D": "O(n^2)"}, "C", "When can you search in O(log n)?"),
    ("Arrays MCQ: Which operation on a dynamic array takes O(n) worst-case time?", "Option D is correct. unshift() inserts at the beginning and shifts all elements.", "Easy", "MCQ", "", {"A": "arr[5]", "B": "arr.push(1)", "C": "arr.pop()", "D": "arr.unshift(1)"}, "D", "Why does unshift shift elements?"),
    ("Strings MCQ: What is the optimal time complexity to check if two strings of length n are anagrams?", "Option B is correct. Frequency counting achieves O(n) linear time.", "Easy", "MCQ", "", {"A": "O(1)", "B": "O(n)", "C": "O(n log n)", "D": "O(n^2)"}, "B", "What does sorting both strings take?")
]

dsa_hash_two_pointers = [
    # Hash Tables, Sets, Two Pointers & Sliding Window (40 Qs)
    ("What is a Hash Table (Hash Map) and how does it store key-value pairs?", "A data structure that maps keys to values using a Hash Function to compute an index into an array of buckets, providing average O(1) lookup, insert, and delete.", "Easy", "Concept", "", "What is a Hash Function?"),
    ("What is a Hash Function in computer science?", "A deterministic function that converts an input key of arbitrary size into a fixed-size integer hash code within the array bounds.", "Easy", "Concept", "", "What are the properties of a good hash function?"),
    ("What are the characteristics of a good hash function?", "1. Deterministic (same key always yields same hash). 2. Uniform distribution (minimizes collisions). 3. Fast O(1) computation.", "Easy", "Concept", "", "What is a Hash Collision?"),
    ("What is a Hash Collision and why are collisions inevitable?", "A collision occurs when two distinct keys produce the exact same array index. By the Pigeonhole Principle, collisions are inevitable when keyspace > table size.", "Easy", "Concept", "", "What are the two primary techniques for handling hash collisions?"),
    ("What are the two main collision resolution techniques?", "1. Separate Chaining (each bucket stores a linked list of entries). 2. Open Addressing (probes alternative bucket slots: Linear Probing, Quadratic Probing, Double Hashing).", "Intermediate", "Comparison", "", "What is the Load Factor in a hash table?"),
    ("What is the Load Factor (alpha) in hash tables and what does it trigger?", "Load Factor = Number of elements (n) / Number of buckets (k). When load factor exceeds a threshold (typically 0.75), the table rehashes and doubles in size.", "Intermediate", "Concept", "", "What is Rehashing?"),
    ("What is Rehashing in hash tables?", "Allocating a larger array (usually 2x capacity) and re-computing the bucket index for all existing entries using the new table size.", "Intermediate", "Concept", "", "What is the difference between JavaScript Object and Map?"),
    ("What are the key differences between JavaScript Object and Map in DSA?", "Map keys can be ANY type (objects, functions, primitives), preserves insertion order, has O(1) size property, and is optimized for frequent additions/removals. Object keys are only strings/symbols.", "Easy", "Comparison", "const map = new Map();\nmap.set({ id: 1 }, 'val'); // Objects as keys allowed!", "When should you prefer Map over Object?"),
    ("What is a Set and how does it guarantee uniqueness?", "A Set is a collection of unique values. It uses an internal hash table where values act as hash keys, rejecting duplicates in O(1) average time.", "Easy", "Concept", "const unique = [...new Set([1, 2, 2, 3])]; // [1, 2, 3]", "What is the time complexity of Set insertion?"),
    ("How do you find the intersection of two arrays using a Set?", "Convert one array to a Set in O(n), then filter the second array with set.has() in O(m) time. Total time: O(n + m).", "Easy", "Problem Solving", "function intersection(nums1, nums2) {\n  const set1 = new Set(nums1);\n  return nums2.filter(x => set1.has(x));\n}", "What is the space complexity?"),
    ("What is the Sliding Window pattern and what problems does it solve?", "Maintaining a subset of elements between two indices (left and right) that expands and shrinks dynamically to find optimal subarrays/substrings without nested loops.", "Intermediate", "Concept", "", "What is the Maximum Sum Subarray of size k problem?"),
    ("How do you find the maximum sum of any contiguous subarray of size k in O(n) time?", "Compute sum of the first k elements. Then slide the window: subtract element exiting on the left (arr[i-k]) and add element entering on the right (arr[i]).", "Easy", "Problem Solving", "let sum = 0;\nfor (let i = 0; i < k; i++) sum += arr[i];\nlet max = sum;\nfor (let i = k; i < arr.length; i++) {\n  sum += arr[i] - arr[i - k];\n  max = Math.max(max, sum);\n}", "Why is this O(n) instead of O(n*k)?"),
    ("How do you find the Longest Substring Without Repeating Characters in O(n) time?", "Use a sliding window with a Set or Map storing character last-seen indices. Expand right pointer; if a duplicate appears, advance left pointer past the previous occurrence.", "Intermediate", "Problem Solving", "function lengthOfLongestSubstring(s) {\n  const map = new Map();\n  let maxLen = 0, l = 0;\n  for (let r = 0; r < s.length; r++) {\n    if (map.has(s[r]) && map.get(s[r]) >= l) {\n      l = map.get(s[r]) + 1;\n    }\n    map.set(s[r], r);\n    maxLen = Math.max(maxLen, r - l + 1);\n  }\n  return maxLen;\n}", "What is the time and space complexity?"),
    ("What is the Container With Most Water problem and its two-pointer solution?", "Pointers at both ends of array. Calculate area = (r - l) * min(h[l], h[r]). Move the pointer pointing to the SHORTER height inward to potentially find a taller line.", "Intermediate", "Problem Solving", "let l = 0, r = height.length - 1, maxArea = 0;\nwhile (l < r) {\n  const area = (r - l) * Math.min(height[l], height[r]);\n  maxArea = Math.max(maxArea, area);\n  if (height[l] < height[r]) l++;\n  else r--;\n}", "Why move the shorter line pointer?"),
    ("Why does moving the shorter pointer in Container With Most Water guarantee correctness?", "Keeping the shorter line and reducing width can only produce smaller areas. The only way to increase area is to find a taller line by moving past the shorter boundary.", "Intermediate", "Concept", "", "What is the Trapping Rain Water problem?"),
    ("How is the Trapping Rain Water problem solved in O(n) time and O(1) space?", "Two pointers (left, right) with maxLeft and maxRight trackers. Process the smaller side: water trapped at index = maxBoundary - height[i].", "Advanced", "Problem Solving", "", "What is the three sum (3Sum) problem?"),
    ("How do you solve the 3Sum problem (a + b + c = 0) in O(n^2) time?", "1. Sort the array. 2. Loop through each element i. 3. Use two pointers (left = i+1, right = n-1) to find pairs summing to -arr[i]. Skip duplicates.", "Intermediate", "Problem Solving", "", "Why sort the array first in 3Sum?"),
    ("Two Pointers MCQ: In a sorted array, what happens to the sum when the right pointer moves left?", "Option B is correct. Moving the right pointer left decreases the sum.", "Easy", "MCQ", "", {"A": "Increases", "B": "Decreases", "C": "Stays the same", "D": "Doubles"}, "B", "What happens when left moves right?"),
    ("Hash Table MCQ: What is the average time complexity to insert a key-value pair into a hash table?", "Option A is correct. Average insert is O(1) constant time.", "Easy", "MCQ", "", {"A": "O(1)", "B": "O(log n)", "C": "O(n)", "D": "O(n log n)"}, "A", "What is worst-case when collisions occur?")
]
