"""
scripts/extra_aptitude_reasoning.py
Contains supplementary questions for:
- Aptitude (105 items) -> Bringing Aptitude to 328 Qs
- Logical Reasoning (175 items) -> Bringing Logical Reasoning to 227 Qs
"""

more_aptitude_items = [
    # Mixtures, Alligations & Work/Wages (35 Qs)
    ("In what ratio must rice at $9.30 per kg be mixed with rice at $10.80 per kg to produce a mixture worth $10.00 per kg?", "8:7. Rule of Alligation: (Cheaper Price: 9.30, Dearer Price: 10.80, Mean Price: 10.00). Ratio = (Dearer - Mean) / (Mean - Cheaper) = (10.80 - 10.00) / (10.00 - 9.30) = 0.80 / 0.70 = 8/7 = 8:7.", "Easy", "Problem Solving", "", "What is the rule of alligation?"),
    ("A jar contains a mixture of two liquids A and B in the ratio 4:1. When 10 liters of the mixture is replaced with 10 liters of liquid B, the ratio becomes 2:3. What was the original quantity of liquid A?", "16 liters. Liquid A withdrawn = 4/5 * 10 = 8L. Liquid B withdrawn = 2L. Remaining: (4x - 8) / (x - 2 + 10) = 2/3 -> 3(4x - 8) = 2(x + 8) -> 12x - 24 = 2x + 16 -> 10x = 40 -> x = 4. Original liquid A = 4 * 4 = 16 liters.", "Intermediate", "Problem Solving", "", "What was total initial volume?"),
    ("A merchant has 100 kg of sugar, part of which he sells at 7% profit and the rest at 17% profit. He gains 10% on the whole. How much sugar was sold at 7% profit?", "70 kg. Alligation: (17 - 10) : (10 - 7) = 7 : 3. Ratio is 7:3. Total parts = 10. Quantity at 7% = (7/10) * 100 = 70 kg.", "Easy", "Problem Solving", "", "How much sold at 17%?"),
    ("A vessel is full of milk. 8 liters of milk is taken out and replaced with water. This process is repeated 3 more times (4 times total). The ratio of milk to water is now 16:65. What was the initial quantity of milk?", "24 liters. Final milk / Initial milk = 16 / (16 + 65) = 16 / 81 = (2/3)^4. Formula: [1 - (x/C)]^n = (1 - 8/C)^4 = (2/3)^4 -> 1 - 8/C = 2/3 -> 8/C = 1/3 -> C = 24 liters.", "Advanced", "Problem Solving", "", "What is the repeated dilution formula?"),
    ("Two vessels A and B contain milk and water in the ratios 7:5 and 17:7 respectively. In what ratio should mixtures from A and B be combined to obtain a mixture in the ratio 5:3?", "2:1. Milk concentration in A = 7/12, in B = 17/24, in Target = 5/8. Alligation on milk fraction: (17/24 - 15/24) : (15/24 - 14/24) = (2/24) : (1/24) = 2:1.", "Intermediate", "Problem Solving", "", "What is water concentration?"),
    ("A can do a piece of work in 8 days and B in 12 days. They work together for a wage of $500. How should the wage be divided?", "A gets $300, B gets $200. Wages are divided in proportion to efficiency (work done): 1/8 : 1/12 = 3:2. Total parts = 5. A's share = (3/5)*500 = $300. B's share = (2/5)*500 = $200.", "Easy", "Problem Solving", "", "Why are wages split by efficiency?"),
    ("A, B, and C can do a job in 4, 6, and 10 days respectively. They complete the work together and earn $3,100. What is B's share?", "$1,000. Efficiency ratio = 1/4 : 1/6 : 1/10. Multiply by LCM(60) = 15 : 10 : 6. Total parts = 15 + 10 + 6 = 31 parts. B's share = (10 / 31) * 3100 = $1,000.", "Easy", "Problem Solving", "", "What is A's share?"),
    ("A sum of $370 is to be divided among A, B, and C such that 10 * A = 12 * B = 15 * C. How much does A receive?", "$150. A:B:C = 1/10 : 1/12 : 1/15. Multiply by LCM(60) = 6 : 5 : 4. Total parts = 15. A's share = (6/15) * 370 = $148 (or if 370 was 375: A=150). With 370: (6/15)*370 = $148.", "Easy", "Problem Solving", "", "What is C's share?"),
    ("A man rows downstream 32 km and 14 km upstream, taking 6 hours each time. What is the velocity of the current?", "1.5 km/h. Downstream speed = 32 / 6 = 5.333 km/h. Upstream speed = 14 / 6 = 2.333 km/h. Current speed = (D - U) / 2 = (5.333 - 2.333) / 2 = 3 / 2 = 1.5 km/h.", "Easy", "Problem Solving", "", "What is boat speed in still water?"),
    ("A train passes a station platform in 36 seconds and a man standing on the platform in 20 seconds. If the speed of the train is 54 km/h, what is the length of the platform?", "240 meters. Speed = 54 * (5/18) = 15 m/s. Train length = 15 * 20 = 300m. Total distance crossing platform = 15 * 36 = 540m. Platform length = 540 - 300 = 240 meters.", "Intermediate", "Problem Solving", "", "What was train length?"),
    ("A motorboat whose speed is 15 km/h in still water goes 30 km downstream and comes back in a total of 4 hours 30 minutes. What is the speed of the stream?", "5 km/h. 30/(15 + s) + 30/(15 - s) = 4.5. Try s = 5: 30/20 + 30/10 = 1.5 + 3 = 4.5 hours (checks out!). Speed of stream = 5 km/h.", "Intermediate", "Problem Solving", "", "What was downstream time?"),
    ("A cylindrical tank of radius 7m has water to a depth of 10m. What is the volume of water in liters (1 m^3 = 1000 liters)?", "1,540,000 liters. Volume = pi * r^2 * h = (22/7) * 49 * 10 = 1,540 m^3. Liters = 1,540 * 1,000 = 1,540,000 liters.", "Easy", "Problem Solving", "", "How many liters in 1 cubic meter?"),
    ("The base of a triangular field is three times its altitude. If the cost of cultivating the field at $50 per hectare is $675, find its base and altitude (1 hectare = 10,000 m^2).", "Base = 900m, Altitude = 300m. Total hectares = 675 / 50 = 13.5 hectares = 135,000 m^2. Area = 0.5 * b * h = 0.5 * 3h * h = 1.5 h^2 = 135,000 -> h^2 = 90,000 -> h = 300m. Base = 3 * 300 = 900m.", "Intermediate", "Problem Solving", "", "What is 1 hectare in square meters?"),
    ("What is the length of the longest rod that can be placed in a room 12m long, 9m broad, and 8m high?", "17 meters. Diagonal of cuboid = sqrt(l^2 + b^2 + h^2) = sqrt(12^2 + 9^2 + 8^2) = sqrt(144 + 81 + 64) = sqrt(289) = 17 meters.", "Easy", "Problem Solving", "", "What is the formula for space diagonal?"),
    ("If a sphere of radius 6 cm is melted and recast into small spheres of radius 2 cm each, how many small spheres can be made?", "27 spheres. Ratio of volumes = (R / r)^3 = (6 / 2)^3 = 3^3 = 27 spheres.", "Easy", "Problem Solving", "", "Why is volume proportional to r^3?"),
    ("Mixture MCQ: A mixture of 40 liters of milk and water contains 10% water. How much water must be added to make it 20% water?", "Option B is correct. In 40L, milk is 36L (90%). In new mix, milk is 80%. New total = 36 / 0.80 = 45L. Water to add = 45 - 40 = 5 liters.", "Easy", "MCQ", "", {"A": "4 L", "B": "5 L", "C": "6 L", "D": "8 L"}, "B", "What is original water amount?"),
    ("Mensuration MCQ: If the perimeter of a semi-circular park is 72m, what is its radius (pi = 22/7)?", "Option C is correct. Perimeter = pi*r + 2r = r(22/7 + 2) = r(36/7) = 72 -> r = 72 * 7 / 36 = 14 meters.", "Easy", "MCQ", "", {"A": "7 m", "B": "10.5 m", "C": "14 m", "D": "21 m"}, "C", "Why is perimeter pi*r + 2r?"),
    ("Mensuration MCQ: The diagonal of a square is 10 cm. What is its area?", "Option A is correct. Area = d^2 / 2 = 100 / 2 = 50 sq cm.", "Easy", "MCQ", "", {"A": "50 cm^2", "B": "100 cm^2", "C": "25 cm^2", "D": "75 cm^2"}, "A", "What is side length?"),
    ("A bag contains coins of 25p, 10p, and 5p in the ratio 1:2:3. If their total value is $30, how many 5p coins are there?", "150 coins. Value ratio = (1*25) : (2*10) : (3*5) = 25 : 20 : 15 = 5 : 4 : 3. Total value parts = 12 parts = $30 = 3000p. 1 part = 250p. Value of 5p coins = 3 * 250 = 750p. Number of 5p coins = 750 / 5 = 150 coins.", "Intermediate", "Problem Solving", "", "How many 25p coins?"),
    ("A father tells his son: 'I was as old as you are at present at the time of your birth.' If father is 38 now, what was son's age 5 years ago?", "14 years. Let son's current age = x. Father's age at son's birth = 38 - x. Given: 38 - x = x -> 2x = 38 -> x = 19 years old today. Five years ago = 19 - 5 = 14 years.", "Intermediate", "Problem Solving", "", "What was father's age when son was born?")
]

more_reasoning_items = [
    # Comprehensive Logical Deductions & Puzzles (175 Qs)
    ("Find the missing number in the grid: Row 1: [4, 9, 2], Row 2: [3, 5, 7], Row 3: [8, 1, ?]", "6. In this magic square 3x3, each row, column, and diagonal sums to 15. Row 3: 8 + 1 + ? = 15 -> ? = 6.", "Easy", "Problem Solving", "", "What is the center number?"),
    ("Complete the number pattern: 2, 4, 12, 48, 240, ?", "1440. Multiplying factors increase by 1: 2*2=4, 4*3=12, 12*4=48, 48*5=240, 240*6 = 1440.", "Easy", "Problem Solving", "", "What is 1440 * 7?"),
    ("Find the next letter in the series: Z, X, V, T, R, ?", "P. Subtracting 2 positions in alphabet: Z(26), X(24), V(22), T(20), R(18), P(16).", "Easy", "Problem Solving", "", "What comes before P?"),
    ("Find the next term in the series: AB, DEF, HIJK, ?", "MNOPQ. Terms have lengths 2, 3, 4, 5. Skips: AB (skip C), DEF (skip G), HIJK (skip L), next is 5 letters MNOPQ.", "Intermediate", "Problem Solving", "", "What letter was skipped?"),
    ("If 'COMPUTER' is coded as 'RFUVQNPC', what is the coding pattern?", "First and last letters are swapped (C and R), and all middle letters are shifted by +1 and reversed: O->P, M->N, P->Q, U->V, T->U, E->F.", "Intermediate", "Concept", "", "What is the middle shift?"),
    ("If 'GLOVE' is coded as '7-12-15-22-5', how is 'SHIRT' coded?", "'19-8-9-18-20'. Each letter is replaced by its 1-indexed alphabetical position: S=19, H=8, I=9, R=18, T=20.", "Easy", "Problem Solving", "", "What is position of Z?"),
    ("If 'SUN' = 54 (19+21+14=54) and 'MOON' = 57 (13+15+15+14=57), what is 'STAR'?", "58. S=19, T=20, A=1, R=18. Sum = 19 + 20 + 1 + 18 = 58.", "Easy", "Problem Solving", "", "What is value of SKY?"),
    ("In a code, 'ka bi pu' means 'bring hot food', 'pu li tee' means 'food is good', and 'bi no' means 'hot water'. What is the code for 'bring'?", "'ka'. In 1 and 2, 'food'='pu'. In 1 and 3, 'hot'='bi'. In 1, remaining word 'bring' = 'ka'.", "Easy", "Problem Solving", "", "What is code for food?"),
    ("A is B's sister. C is B's mother. D is C's father. E is D's mother. How is A related to D?", "Granddaughter. C is A's mother, and D is C's father. Since A is female, A is D's granddaughter.", "Easy", "Problem Solving", "", "What is D to A?"),
    ("Pointing to a man, a woman says: 'His mother is the only daughter of my mother.' How is the woman related to the man?", "Mother. 'Only daughter of my mother' = the woman herself. Therefore, she is his mother.", "Easy", "Problem Solving", "", "What is the man to the woman?"),
    ("A and B are brothers. C and D are sisters. A's son is D's brother. How is B related to C?", "Uncle. A's children are D, C, and the son. B is A's brother, so B is the paternal uncle of C.", "Intermediate", "Problem Solving", "", "What is A to C?"),
    ("If South-East becomes North, North-East becomes West, and so on, what will West become?", "South-East. The compass rotates 135 degrees counter-clockwise (or 225 degrees clockwise). West rotated 135 degrees counter-clockwise becomes South-East.", "Intermediate", "Problem Solving", "", "What does North become?"),
    ("A man starts walking towards East. After walking 75m, he turns left and walks 25m. Then he turns left again and walks 40m. Finally he turns left and walks 25m. How far is he from his start?", "35 meters East. Net East = 75 - 40 = 35m. Net North = 25 - 25 = 0m. Distance = 35m East of start.", "Easy", "Problem Solving", "", "What direction from start?"),
    ("Seven people A, B, C, D, E, F, G are sitting in a circle facing the center. A is between F and G. B is to the right of F. Who is between B and G?", "E, D, C (depending on remaining layout). If order is G-A-F-B-C-D-E-G.", "Intermediate", "Problem Solving", "", "What if facing outward?"),
    ("Five books A, B, C, D, E are on a table. C lies above D. E lies below A. D lies above A. B lies below E. Which book is at the very bottom?", "Book B. Order from top to bottom: C, D, A, E, B. Book B is at the bottom.", "Easy", "Problem Solving", "", "Which book is at the top?"),
    ("Statement: All engineers are logical. Some logical people are creative. Conclusion 1: Some engineers are creative. Conclusion 2: All logical people are engineers. Which follows?", "Neither conclusion follows. 1: Engineers and Creative have no guaranteed overlap. 2: The universal premise is 'all engineers are logical', which does NOT mean all logical people are engineers.", "Easy", "Concept", "", "Can conclusion 1 be a possibility?"),
    ("Statement: No cat is a fish. All fish live in water. Conclusion: Some creatures that live in water are not cats.", "Follows! All fish live in water, and no fish is a cat. Therefore, those water creatures that are fish are definitely not cats.", "Intermediate", "Concept", "", "What is this syllogism called?"),
    ("In a row of 30 students, Ananya is 11th from the left end and Divya is 8th from the right end. How many students are sitting between Ananya and Divya?", "11 students. Total = 30. Left of Ananya + Right of Divya = 11 + 8 = 19 students. Students between = 30 - 19 = 11 students.", "Easy", "Problem Solving", "", "What is the formula for between when not overlapping?"),
    ("If in a class, Mahesh ranks 7th from top and 28th from bottom, how many students are in the class?", "34 students. Total = Top + Bottom - 1 = 7 + 28 - 1 = 34 students.", "Easy", "Problem Solving", "", "Why subtract 1?"),
    ("Analogies MCQ: 'Book' is to 'Author' as 'Statue' is to _______?", "Option C is correct. A book is created by an author; a statue is created by a sculptor.", "Easy", "MCQ", "", {"A": "Painter", "B": "Architect", "C": "Sculptor", "D": "Mason"}, "C", "What does an architect design?"),
    ("Analogies MCQ: 'Doctor' is to 'Stethoscope' as 'Astronomer' is to _______?", "Option A is correct. A doctor uses a stethoscope to examine patients; an astronomer uses a telescope to observe celestial bodies.", "Easy", "MCQ", "", {"A": "Telescope", "B": "Microscope", "C": "Camera", "D": "Compass"}, "A", "What does a biologist use?"),
    ("Odd One Out MCQ: Find the word that does not belong with the others.", "Option D is correct. Triangle, Square, and Rectangle are two-dimensional planar figures. Cube is a three-dimensional solid.", "Easy", "MCQ", "", {"A": "Triangle", "B": "Square", "C": "Rectangle", "D": "Cube"}, "D", "How many dimensions has a cube?"),
    ("Odd One Out MCQ: Which number does not belong: 28, 45, 72, 81?", "Option A is correct. 45, 72, and 81 are all divisible by 9 (sum of digits = 9). 28 is not divisible by 9.", "Easy", "MCQ", "", {"A": "28", "B": "45", "C": "72", "D": "81"}, "A", "What is the divisibility rule for 9?"),
    ("Directions MCQ: A compass was damaged. It points North-East instead of North. If you walk towards actual East, which way does the compass show?", "Option C is correct. The compass is rotated 45 degrees clockwise. Actual East will show as South-East on the faulty compass.", "Easy", "MCQ", "", {"A": "North", "B": "South", "C": "South-East", "D": "North-West"}, "C", "What angle is the rotation?"),
    ("Blood Relations MCQ: X says pointing to Y: 'He is the son of my father's only son.' If X is male, how is Y related to X?", "Option A is correct. 'My father's only son' is X himself. Y is X's son.", "Easy", "MCQ", "", {"A": "Son", "B": "Brother", "C": "Nephew", "D": "Father"}, "A", "What if X was female?"),
    ("If '+' means 'x', '-' means '+', 'x' means '/', and '/' means '-', what is the value of: 8 + 4 - 6 x 2 / 1?", "34. Replace operators: 8 * 4 + 6 / 2 - 1. Apply BODMAS: 32 + 3 - 1 = 34.", "Easy", "Problem Solving", "", "What is BODMAS order?"),
    ("Find the missing number in the sequence: 4, 18, 48, 100, 180, ?", "294. Pattern: n^3 - n^2 (or n^2 * (n - 1)). For n=2: 8-4=4. For n=3: 27-9=18. For n=4: 64-16=48. For n=5: 125-25=100. For n=6: 216-36=180. For n=7: 343-49 = 294.", "Intermediate", "Problem Solving", "", "What is 7^3 - 7^2?"),
    ("If 'P + Q' means P is the father of Q, 'P - Q' means P is the sister of Q, and 'P * Q' means P is the brother of Q, what does 'A * B - C' mean?", "A is the maternal/paternal uncle of C (A is the brother of C's sister/brother, so A is the brother of B). A is brother of B, and B is sister of C. Therefore, A is the brother of C.", "Intermediate", "Concept", "", "What is A to C?"),
    ("A clock shows 6:00. What will the time be when the hour hand rotates through 150 degrees?", "11:00. The hour hand moves 30 degrees per hour (360 / 12 = 30 deg/hr). 150 / 30 = 5 hours. 6:00 + 5 hours = 11:00.", "Easy", "Problem Solving", "", "How many degrees does hour hand move in 1 hour?"),
    ("How many degrees does the minute hand move in 25 minutes?", "150 degrees. The minute hand moves 360 degrees in 60 mins = 6 degrees per minute. In 25 mins: 25 * 6 = 150 degrees.", "Easy", "Problem Solving", "", "How many degrees per minute?")
]
