"""
scripts/mongo_additions.py
Supplementary MongoDB questions to ensure MongoDB reaches 220+ items.
"""

mongo_extra_items = [
    # Multi-document Transactions & Sessions - 10 Qs
    ("Does MongoDB support multi-document ACID transactions?", "Yes! Starting in version 4.0 (replica sets) and 4.2 (sharded clusters), MongoDB supports multi-document ACID transactions using sessions.", "Easy", "Concept", "const session = client.startSession();\nsession.startTransaction();", "What are the performance costs of multi-document transactions?"),
    ("Why should multi-document transactions be used sparingly in MongoDB?", "Transactions hold locks on modified documents, consume server cache memory, and incur latency overhead. Document embedding should be the primary pattern for atomic writes.", "Intermediate", "Best Practice", "", "How do you execute a transaction in Mongoose?",),
    ("How do you execute a transaction in Mongoose with Node.js?", "Start a session, wrap queries in session.withTransaction(), and pass { session } option to each operation.", "Intermediate", "Practical", "const session = await mongoose.startSession();\nawait session.withTransaction(async () => {\n  await Account.updateOne({ _id: fromId }, { $inc: { balance: -100 } }, { session });\n  await Account.updateOne({ _id: toId }, { $inc: { balance: 100 } }, { session });\n});\nsession.endSession();", "What happens if an error is thrown inside withTransaction?"),
    ("What happens if an exception is thrown inside session.withTransaction()?", "MongoDB automatically aborts the transaction, rolls back all changes, and closes open locks automatically.", "Easy", "Concept", "", "What is the maximum execution time limit for a MongoDB transaction?"),
    ("What is the default transaction lifetime limit in MongoDB?", "The default transaction lifetime is 60 seconds (transactionLifetimeLimitSeconds). Transactions open longer than 60 seconds are automatically aborted.", "Intermediate", "Concept", "", "Transactions MCQ: Which method starts an ACID transaction on a client session in MongoDB?"),
    ("Transactions MCQ: Which method initiates a transaction in the MongoDB driver?", "Option B is correct. session.startTransaction() starts an ACID transaction.", "Easy", "MCQ", "", {"A": "db.beginTransaction()", "B": "session.startTransaction()", "C": "client.transaction()", "D": "db.startACID()"}, "B", "What ends the session?"),
    ("Transactions MCQ: What happens if an unhandled error occurs within session.withTransaction()?", "Option C is correct. The transaction is automatically aborted and changes rolled back.", "Easy", "MCQ", "", {"A": "Changes are partially committed", "B": "Database hangs", "C": "Transaction automatically aborts and rolls back", "D": "Retried indefinitely"}, "C", "How do you handle retries?"),
    ("Transactions Coding: Write a money transfer between two accounts using MongoDB transactions.", "const session = client.startSession(); await session.withTransaction(async () => { await accounts.updateOne({ _id: a }, { $inc: { bal: -50 } }, { session }); await accounts.updateOne({ _id: b }, { $inc: { bal: 50 } }, { session }); }); session.endSession();", "Intermediate", "Coding", "async function transfer(fromId, toId, amount) {\n  const session = client.startSession();\n  try {\n    await session.withTransaction(async () => {\n      await accounts.updateOne({ _id: fromId }, { $inc: { balance: -amount } }, { session });\n      await accounts.updateOne({ _id: toId }, { $inc: { balance: amount } }, { session });\n    });\n  } finally {\n    await session.endSession();\n  }\n}", "Why is session.endSession() placed in a finally block?"),
    ("Why must session.endSession() be placed in a finally block?", "To guarantee that the session is always closed and server resources are released, even if the transaction fails with an unhandled exception.", "Easy", "Best Practice", "", "What is Read Concern in MongoDB transactions?"),
    ("What is Read Concern 'snapshot' in MongoDB transactions?", "It guarantees that all reads within the transaction see a consistent, isolated point-in-time snapshot of the data, unaffected by concurrent writes.", "Advanced", "Concept", "", "What is Change Streams in MongoDB?"),

    # Change Streams & Real-Time Events - 8 Qs
    ("What are Change Streams in MongoDB?", "Change Streams allow applications to subscribe to real-time data changes (inserts, updates, deletes) in a collection, database, or deployment using the oplog.", "Intermediate", "Concept", "const changeStream = collection.watch();\nchangeStream.on('change', next => console.log(next));", "What requirement must be met to use Change Streams?"),
    ("What is the prerequisite for using Change Streams in MongoDB?", "The MongoDB deployment MUST be a Replica Set or Sharded Cluster because Change Streams rely on the oplog.", "Intermediate", "Concept", "", "How do you filter Change Streams to only watch for 'insert' operations?",),
    ("How do you filter a Change Stream for specific operations?", "Pass an aggregation pipeline to .watch(): collection.watch([ { $match: { operationType: 'insert' } } ]).", "Intermediate", "Practical", "const stream = db.orders.watch([\n  { $match: { operationType: 'insert', 'fullDocument.total': { $gt: 100 } } }\n]);", "What information does a change stream event contain?"),
    ("What does a Change Stream event object contain?", "operationType ('insert', 'update', 'delete', 'replace'), documentKey (the _id), fullDocument, updateDescription (updated fields), and clusterTime.", "Intermediate", "Concept", "", "What is resumeToken in Change Streams?",),
    ("What is a resumeToken (_id) in Change Streams?", "An opaque token returned with each change event that allows an application to resume listening from the exact last processed event after network downtime.", "Advanced", "Architecture", "collection.watch([], { resumeAfter: lastResumeToken });", "How does this prevent missed events?"),
    ("Change Streams MCQ: What cluster architecture is required to use MongoDB Change Streams?", "Option B is correct. A Replica Set or Sharded Cluster is mandatory.", "Easy", "MCQ", "", {"A": "Standalone mongod", "B": "Replica Set or Sharded Cluster", "C": "WiredTiger single instance", "D": "GridFS deployment"}, "B", "Why is it required?"),
    ("Change Streams Coding: Watch the 'messages' collection and log newly inserted chat messages in real time.", "const stream = messages.watch([{ $match: { operationType: 'insert' } }]); stream.on('change', change => console.log('New message:', change.fullDocument.text));", "Easy", "Coding", "const stream = db.collection('messages').watch([\n  { $match: { operationType: 'insert' } }\n]);\nstream.on('change', change => {\n  console.log('New chat message:', change.fullDocument);\n});", "How do you close a change stream?"),

    # Geospatial Queries & Advanced Indexes - 12 Qs
    ("What is GeoJSON in MongoDB?", "A standard format for encoding geographic data structures (Point, LineString, Polygon) using coordinates: { type: 'Point', coordinates: [longitude, latitude] }.", "Easy", "Concept", "{ location: { type: 'Point', coordinates: [-73.97, 40.77] } }", "Why is coordinates order longitude then latitude?"),
    ("What is the order of coordinates in MongoDB GeoJSON?", "Strictly [Longitude, Latitude] (X, Y axis order). Reversing them causes queries to look in the wrong hemisphere!", "Easy", "Best Practice", "coordinates: [longitude, latitude]", "What index type is used for GeoJSON queries?"),
    ("What index type supports geospatial queries on a sphere in MongoDB?", "The '2dsphere' index: db.places.createIndex({ location: '2dsphere' }).", "Easy", "Concept", "db.restaurants.createIndex({ location: '2dsphere' });", "What does $near operator do in geospatial queries?"),
    ("What does the $near operator do in MongoDB geospatial queries?", "It finds documents nearest to a specified GeoJSON point and sorts them by distance from closest to farthest automatically.", "Intermediate", "Practical", "db.places.find({\n  location: {\n    $near: {\n      $geometry: { type: 'Point', coordinates: [-73.96, 40.78] },\n      $maxDistance: 1000 // In meters\n    }\n  }\n});", "What does $geoWithin operator do?"),
    ("What is the difference between $near and $geoWithin in MongoDB?", "$near sorts results by distance and requires an index. $geoWithin selects documents inside a bounding polygon or circle without sorting by distance.", "Intermediate", "Comparison", "", "What is a Wildcard Index ($**) in MongoDB?",),
    ("What is a Wildcard Index ($**) in MongoDB?", "An index that indexes all fields in dynamic or unpredictable user-defined attribute schemas: createIndex({ 'customAttributes.$**': 1 }).", "Advanced", "Concept", "db.products.createIndex({ 'attributes.$**': 1 });", "When should Wildcard indexes be used?"),
    ("When are Wildcard indexes useful?", "In e-commerce product catalogs where different categories have completely different, dynamic custom attributes (e.g. shirt size vs TV screen resolution).", "Intermediate", "Scenario", "", "What is a Clustered Collection in MongoDB (v5.3+)?"),
    ("What is a Clustered Collection in MongoDB v5.3+?", "A collection stored ordered by a clustered index key (similar to SQL clustered tables), improving insert performance and range scan speed.", "Advanced", "Concept", "db.createCollection('logs', { clusteredIndex: { key: { _id: 1 }, unique: true } });", "Geospatial MCQ: What coordinate order does MongoDB GeoJSON require?"),
    ("Geospatial MCQ: What is the correct order of coordinates in a GeoJSON Point?", "Option A is correct. [longitude, latitude].", "Easy", "MCQ", "", {"A": "[longitude, latitude]", "B": "[latitude, longitude]", "C": "[altitude, latitude]", "D": "[x, y, z]"}, "A", "What happens if reversed?"),
    ("Geospatial MCQ: Which index type is required for spherical Earth distance calculations in MongoDB?", "Option C is correct. 2dsphere index calculates spherical distance.", "Easy", "MCQ", "", {"A": "2d", "B": "geo", "C": "2dsphere", "D": "spatial"}, "C", "What is 2d used for?"),
    ("Geospatial Coding: Find all coffee shops within 500 meters of a coordinate.", "db.shops.find({ location: { $near: { $geometry: { type: 'Point', coordinates: [lng, lat] }, $maxDistance: 500 } } });", "Easy", "Coding", "db.shops.find({\n  location: {\n    $near: {\n      $geometry: { type: 'Point', coordinates: [77.5946, 12.9716] },\n      $maxDistance: 500\n    }\n  }\n});", "What unit is maxDistance in?"),

    # Mongoose Advanced & Schema Patterns - 10 Qs
    ("What are Mongoose Discriminators?", "A schema inheritance mechanism that allows storing different model schemas in the same underlying MongoDB collection with a __t type key.", "Intermediate", "Concept", "const Event = mongoose.model('Event', eventSchema);\nconst ClickedEvent = Event.discriminator('Clicked', new mongoose.Schema({ url: String }));", "When are discriminators useful?"),
    ("When should you use Mongoose Discriminators?", "When you have shared common fields across polymorphic entities (e.g. Notification base model with EmailNotification and PushNotification variants).", "Intermediate", "Scenario", "", "What is deep population in Mongoose?",),
    ("How do you perform Deep Population across multiple levels in Mongoose?", "Pass a nested populate object: populate({ path: 'author', populate: { path: 'profile' } }).", "Intermediate", "Practical", "const post = await Post.findById(id).populate({\n  path: 'comments',\n  populate: { path: 'author', select: 'name avatar' }\n});", "What performance risk exists with deep population?"),
    ("Why should deep population across 3+ levels be avoided in high-traffic APIs?", "Each populate level executes additional database queries, leading to severe latency and N+1 query bottlenecks. Use aggregation $lookup instead.", "Intermediate", "Performance", "", "What is Mongoose timestamps option?",),
    ("What does { timestamps: true } in a Mongoose schema do?", "It automatically adds and manages createdAt and updatedAt Date fields on every document.", "Easy", "Practical", "const userSchema = new mongoose.Schema({ name: String }, { timestamps: true });", "Can createdAt be modified by users?"),
    ("How do you soft-delete documents in Mongoose?", "Add an isDeleted: Boolean (or deletedAt: Date) field, and filter queries with pre('find') middleware: this.where({ isDeleted: false }).", "Easy", "Practical", "schema.pre(/^find/, function(next) {\n  this.where({ isDeleted: false });\n  next();\n});", "Why is soft deletion common in SaaS applications?"),
    ("Mongoose MCQ: Which schema option automatically manages createdAt and updatedAt fields?", "Option B is correct. timestamps: true automatically adds both fields.", "Easy", "MCQ", "", {"A": "autoDate: true", "B": "timestamps: true", "C": "audit: true", "D": "trackTime: true"}, "B", "What types are the fields?"),
    ("Mongoose Debugging: A developer called await User.updateOne({ _id }, { $set: { password: '123' } }) but the pre('save') hash hook didn't fire. Why?", "updateOne() is a query-level operation that bypasses document-level pre('save') hooks. Use user = await User.findById(); user.password = '123'; await user.save();.", "Intermediate", "Debugging", "-- FIX:\nconst user = await User.findById(id);\nuser.password = newPassword;\nawait user.save(); // pre('save') fires and hashes password!", "What hook fires on updateOne?"),
    ("What is MongoDB Atlas?", "MongoDB Atlas is MongoDB's fully managed multi-cloud database-as-a-service (DBaaS), offering automated backups, scaling, monitoring, and security patching.", "Easy", "Concept", "", "What is the standard MongoDB connection string URI format?"),
    ("What does a mongodb+srv:// connection URI indicate?", "The 'mongodb+srv://' prefix uses DNS SRV records to automatically discover all replica set nodes without listing each host IP individually in the URI.", "Easy", "Concept", "mongodb+srv://user:pass@cluster0.mongodb.net/myDB?retryWrites=true&w=majority", "Why is mongodb+srv preferred over standard mongodb://?")
]
