"""
scripts/project_part2.py
Second batch of fresher Project Interview questions.
"""

project_part2_items = [
    ('How did you implement protected routes in your React application?', "Created a `<ProtectedRoute>` wrapper component that checks the user's authentication status from context. If authenticated, it renders `<Outlet />` (or children); if unauthenticated, it redirects to `/login` using `<Navigate to='/login' replace />` while saving the attempted location in route state.", 'Easy', 'Practical', "const ProtectedRoute = () => {\n  const { user, loading } = useAuth();\n  const location = useLocation();\n  if (loading) return <Spinner />;\n  return user ? <Outlet /> : <Navigate to='/login' state={{ from: location }} replace />;\n};", 'How do you redirect the user back to their original requested page after a successful login?'),
    ('How did you handle the redirect back to the intended page after login?', "Extracted `location.state?.from?.pathname || '/dashboard'` and passed it to `navigate(redirectPath, { replace: true })` inside the login submit handler.", 'Easy', 'Practical', "const from = location.state?.from?.pathname || '/dashboard';\nnavigate(from, { replace: true });", 'Why is `{ replace: true }` used when redirecting after login?'),
    ('What custom hooks did you write in your project and what problems did they solve?', '1) `useAuth`: exposes user profile, login, and logout methods. 2) `useFetch`: encapsulates API call loading, error, and data states with abort controller. 3) `useDebounce`: debounces rapid input typing for search. 4) `useOnClickOutside`: closes dropdowns/modals when clicking outside.', 'Easy', 'Practical', '', 'Can custom hooks call other custom hooks in React?'),
    ('How did you implement Axios interceptors in your project?', 'Configured a centralized Axios client instance: 1) Request Interceptor: automatically attached `Authorization: Bearer <token>` to all outgoing requests. 2) Response Interceptor: intercepted 401 Unauthorized responses to attempt automatic token refresh or redirect to login.', 'Intermediate', 'Practical', "const api = axios.create({ baseURL: '/api' });\napi.interceptors.request.use(config => {\n  const token = getToken();\n  if (token) config.headers.Authorization = `Bearer ${token}`;\n  return config;\n});", 'Why is using an Axios interceptor cleaner than manually adding headers in every API call?'),
    ('How did you implement a custom `useDebounce` hook in React?', 'Maintained `debouncedValue` in state. In `useEffect`, set a `setTimeout` to update `debouncedValue` after delay ms, and returned a cleanup function `clearTimeout` to cancel the timer if value changes before the delay passes.', 'Easy', 'Practical', 'function useDebounce(value, delay = 300) {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => {\n    const timer = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n  return debounced;\n}', 'What is the default recommended delay for search inputs (300-500ms)?'),
    ('How did you handle error boundaries in your React application?', "Wrapped top-level route components in a React Error Boundary class component implementing `componentDidCatch` and `getDerivedStateFromError`, rendering a fallback 'Something went wrong' UI with a reset button to prevent the entire app from crashing on unhandled render errors.", 'Intermediate', 'Practical', 'class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() { return { hasError: true }; }\n  componentDidCatch(error, info) { logErrorToService(error, info); }\n  render() {\n    if (this.state.hasError) return <FallbackUI onReset={() => this.setState({ hasError: false })} />;\n    return this.props.children;\n  }\n}', 'Can functional components implement `componentDidCatch` directly?'),
    ('What CSS styling methodology did you choose for your project and why?', 'Explain chosen styling: e.g. Vanilla CSS with CSS Variables and BEM conventions (no bundle bloat, zero dependencies, full CSS control, theme variables) or CSS Modules (scoped styles preventing global namespace collisions).', 'Easy', 'Concept', '', 'What are the trade-offs between CSS Modules and Tailwind CSS?'),
    ('How did you implement Dark Mode / Light Mode theming in your project?', "Defined color tokens as CSS variables on `:root` and `[data-theme='dark']`. Created a `ThemeContext` tracking theme state, persisted the user's choice in `localStorage`, and synced with the user's system preferences using `window.matchMedia('(prefers-color-scheme: dark)')`.", 'Easy', 'Practical', ":root {\n  --bg-primary: #ffffff;\n  --text-primary: #111827;\n}\n[data-theme='dark'] {\n  --bg-primary: #0f172a;\n  --text-primary: #f8fafc;\n}", 'How do you prevent a white flash when refreshing a page in dark mode?'),
    ('How do you prevent a theme flash (white flash) on page reload in dark mode?', "Run a small blocking script inside the HTML `<head>` before body render that reads `localStorage.getItem('theme')` and sets the `data-theme` attribute on `document.documentElement` immediately.", 'Intermediate', 'Practical', "<script>\n  const t = localStorage.getItem('theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');\n  document.documentElement.setAttribute('data-theme', t);\n</script>", "Why must this script be placed in `<head>` rather than inside React's `useEffect`?"),
    ('How did you handle modal dialogs and accessibility (a11y) in your project?', "Used React Portals (`ReactDOM.createPortal`) to render modal markup outside the parent DOM hierarchy directly into `document.body`. Added `role='dialog'`, `aria-modal='true'`, trapped focus inside the modal, and listened for the `Escape` key to close.", 'Intermediate', 'Practical', "return ReactDOM.createPortal(\n  <div role='dialog' aria-modal='true' className='modal-backdrop'>\n    <div className='modal-content'>{children}</div>\n  </div>,\n  document.body\n);", 'Why is rendering modals via React Portals better than rendering them inline?'),
    ('What is prop drilling and how did you prevent it in your application?', 'Prop drilling is passing props through multiple levels of intermediate components that do not need the data themselves. Prevented by using React Context API for genuinely global data (User, Theme, Cart) or component composition (`children` prop).', 'Easy', 'Concept', '', 'When is component composition better than creating a new Context?'),
    ('How did you handle confirmation dialogs before dangerous user actions (e.g. Delete)?', 'Rendered a confirmation modal displaying the item name and warning consequences. Required explicit user confirmation click before sending the DELETE API request, rather than triggering immediate deletion.', 'Easy', 'Practical', '', 'Why is `window.confirm()` considered poor UX for modern web apps?'),
    ('How did you handle toast notifications / feedback messages in your project?', 'Implemented a global Toast Notification system using Context (or `react-hot-toast` / custom container) that renders temporary floating alerts (success, error, warning) that automatically auto-dismiss after 3000ms.', 'Easy', 'Practical', "const { addToast } = useToast();\n// Inside action:\naddToast('Product successfully added to cart', 'success');", 'Why is toast notification superior to alert()?'),
    ('How did you optimize re-renders in your React component tree?', '1) Kept state as local as possible to prevent parent re-renders from re-rendering the entire tree. 2) Memoized expensive computations using `useMemo`. 3) Memoized callback functions passed to memoized children using `useCallback`. 4) Profiled components using React DevTools Profiler.', 'Intermediate', 'Practical', '', 'Why should you not wrap every single component in `React.memo` blindly?'),
    ('How did you handle infinite scroll vs standard page number pagination?', 'Evaluated user experience: infinite scroll is great for exploratory feeds (social media, discovery), whereas numbered pagination is superior for goal-oriented search results (e-commerce orders, admin tables) where users need to bookmark or share specific pages.', 'Easy', 'Comparison', '', 'How do you implement infinite scroll in React using Intersection Observer?'),
    ('How did you handle form state management in your application?', 'Used controlled components with state tracking values, validation errors, and submission status. For larger forms, used a schema validation library to validate all fields before submission.', 'Easy', 'Practical', "const [form, setForm] = useState({ email: '', password: '' });\nconst [errors, setErrors] = useState({});\nconst handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });", 'What is the difference between controlled and uncontrolled form inputs in React?'),
    ('How did you display inline validation errors next to form fields?', 'Associated each input with an error message using `aria-describedby` for accessibility, setting `aria-invalid={!!errors.email}` and displaying the error text below the input in red with an icon.', 'Easy', 'Practical', "<input\n  id='email'\n  name='email'\n  aria-invalid={!!errors.email}\n  aria-describedby={errors.email ? 'email-error' : undefined}\n/>\n{errors.email && <span id='email-error' className='error'>{errors.email}</span>}", 'Why is `aria-describedby` important for screen readers?'),
    ('How did you prevent users from submitting a form multiple times by clicking repeatedly?', 'Set an `isSubmitting` boolean state to `true` upon submission and disabled the submit button (`disabled={isSubmitting}`) while displaying a loading spinner inside the button until the API call settled.', 'Easy', 'Practical', "<button type='submit' disabled={isSubmitting}>\n  {isSubmitting ? <Spinner /> : 'Save'}\n</button>", 'What happens if an API call times out without resetting `isSubmitting` in a `finally` block?'),
    ('Why is placing state resets in a `finally` block crucial for async actions?', 'Because `finally` guarantees execution whether the Promise resolves successfully or rejects with an error, ensuring loading spinners are always turned off and buttons re-enabled.', 'Easy', 'Concept', 'try {\n  setIsLoading(true);\n  await submitData();\n} catch (err) {\n  setError(err.message);\n} finally {\n  setIsLoading(false); // Always runs!\n}', 'What bug occurs if `setIsLoading(false)` is only placed at the end of the `try` block?'),
    ('How did you handle password confirmation validation on registration forms?', 'Checked that `form.password === form.confirmPassword` during validation. If mismatched, set a specific error message on the confirmPassword field and aborted submission before making an API call.', 'Easy', 'Practical', "if (password !== confirmPassword) {\n  setErrors(prev => ({ ...prev, confirmPassword: 'Passwords do not match' }));\n  return;\n}", 'Should password confirmation be checked on frontend, backend, or both?'),
    ('Did your project use WebSockets or real-time communication, and why?', 'If applicable: used Socket.io for bidirectional, event-based real-time communication (e.g. live chat messages, order status updates, collaborative notifications) without polling overhead.', 'Intermediate', 'Concept', "// Frontend\nconst socket = io('https://api.myapp.com');\nsocket.emit('joinRoom', roomId);\nsocket.on('newMessage', msg => setMessages(prev => [...prev, msg]));", 'How does Socket.io fall back if WebSockets are blocked by firewalls (HTTP long polling)?'),
    ('How did you authenticate WebSocket connections in Socket.io?', 'Passed the JWT token in the `auth` handshake option: `io({ auth: { token } })`. On the server, used middleware `io.use()` to verify the token before allowing the socket connection to establish.', 'Intermediate', 'Security', "// Server Socket.io auth middleware\nio.use((socket, next) => {\n  const token = socket.handshake.auth.token;\n  try {\n    socket.user = jwt.verify(token, JWT_SECRET);\n    next();\n  } catch (err) {\n    next(new Error('Authentication error'));\n  }\n});", 'What happens if an unauthenticated socket tries to connect?'),
    ('How did you prevent memory leaks with WebSocket listeners in React components?', "Registered socket event listeners inside `useEffect` and returned a cleanup function removing the listeners using `socket.off('eventName')` when the component unmounted.", 'Easy', 'Practical', "useEffect(() => {\n  socket.on('message', handleNewMessage);\n  return () => {\n    socket.off('message', handleNewMessage);\n  };\n}, []);", 'What happens if socket event listeners are not removed on unmount?'),
    ('What is the difference between broadcasting to all users vs emitting to a specific room in Socket.io?', '`io.emit()` broadcasts the message to every connected client on the server. `socket.to(roomId).emit()` sends the message only to clients that have joined that specific room (e.g. specific conversation channel or order).', 'Easy', 'Comparison', "socket.to(`room_${orderId}`).emit('orderStatusUpdated', newStatus);", 'How does a socket join a room (`socket.join(roomId)`)?'),
]
