"""
scripts/reasoning_pack.py
220 verified fresher Logical Reasoning questions across Series, Coding, Blood Relations, Directions, Seating, Syllogisms & Puzzles.
"""

reasoning_series = [
    # Number, Letter & Alpha-Numeric Series (35 Qs)
    ("Find the next number in the series: 2, 6, 12, 20, 30, ?", "42. Differences are consecutive even numbers: +4, +6, +8, +10, +12. 30 + 12 = 42. (Also: 1*2, 2*3, 3*4, 4*5, 5*6, 6*7 = 42).", "Easy", "Problem Solving", "", "What is the pattern?"),
    ("Find the next number in the series: 3, 7, 15, 31, 63, ?", "127. Pattern: multiply by 2 and add 1 (2n + 1). (3*2)+1=7, (7*2)+1=15, (15*2)+1=31, (31*2)+1=63, (63*2)+1 = 127. (Also differences are powers of 2: +4, +8, +16, +32, +64).", "Easy", "Problem Solving", "", "What is the next difference?"),
    ("Find the next number in the series: 1, 4, 9, 16, 25, 36, ?", "49. The series is squares of natural numbers: 1^2, 2^2, 3^2, 4^2, 5^2, 6^2, 7^2 = 49.", "Easy", "Problem Solving", "", "What is the 10th term?"),
    ("Find the next number in the series: 1, 8, 27, 64, 125, ?", "216. The series is cubes of natural numbers: 1^3, 2^3, 3^3, 4^3, 5^3, 6^3 = 216.", "Easy", "Problem Solving", "", "What is 7 cubed?"),
    ("Find the missing number in the series: 5, 11, 23, 47, 95, ?", "191. Pattern: x * 2 + 1. 95 * 2 + 1 = 190 + 1 = 191.", "Easy", "Problem Solving", "", "What is the next number?"),
    ("Find the next number in the Fibonacci series: 0, 1, 1, 2, 3, 5, 8, 13, ?", "21. Each term is the sum of the previous two terms: 8 + 13 = 21.", "Easy", "Problem Solving", "", "What is the term after 21?"),
    ("Find the next letter in the series: B, D, F, H, J, ?", "L. Pattern: Skip 1 letter (+2 position in alphabet): B(2), D(4), F(6), H(8), J(10), L(12).", "Easy", "Problem Solving", "", "What is the 14th letter?"),
    ("Find the next letter in the series: Z, W, T, Q, N, ?", "K. Pattern: Subtract 3 positions in alphabet (-3): Z(26), W(23), T(20), Q(17), N(14), K(11).", "Easy", "Problem Solving", "", "What comes before K?"),
    ("Find the next term in the alphanumeric series: A1, C3, E5, G7, ?", "I9. Letters increase by 2 (A, C, E, G, I), and numbers increase by 2 (1, 3, 5, 7, 9).", "Easy", "Problem Solving", "", "What is the term after I9?"),
    ("Find the next number in the alternating series: 10, 20, 12, 22, 14, 24, ?", "16. Two interleaved series: Series 1: 10, 12, 14, 16 (+2). Series 2: 20, 22, 24 (+2). Next term belongs to Series 1: 14 + 2 = 16.", "Easy", "Problem Solving", "", "What is the term after 16?"),
    ("Find the next number in the series: 2, 3, 5, 7, 11, 13, ?", "17. The series consists of consecutive prime numbers: 2, 3, 5, 7, 11, 13, 17.", "Easy", "Problem Solving", "", "What is the prime after 17?"),
    ("Find the missing number: 80, 40, 20, 10, ?", "5. Pattern: divide by 2 at each step. 10 / 2 = 5.", "Easy", "Problem Solving", "", "What comes after 5?"),
    ("Find the next number in the series: 4, 9, 25, 49, 121, ?", "169. Squares of consecutive prime numbers: 2^2, 3^2, 5^2, 7^2, 11^2, 13^2 = 169.", "Intermediate", "Problem Solving", "", "What is the next prime square?"),
    ("Find the missing term: CX, EV, GT, IR, ?", "KP. First letter advances by +2: C(3), E(5), G(7), I(9), K(11). Second letter is the opposite reverse alphabet letter (sum=27): C-X, E-V, G-T, I-R, K-P.", "Intermediate", "Problem Solving", "", "What is opposite of L?"),
    ("Series MCQ: What is the next number in the series: 2, 5, 10, 17, 26, ?", "Option C is correct. Pattern: n^2 + 1 (1^2+1, 2^2+1, 3^2+1, 4^2+1, 5^2+1, 6^2+1 = 37).", "Easy", "MCQ", "", {"A": "33", "B": "35", "C": "37", "D": "39"}, "C", "What is 7^2 + 1?"),
    ("Series MCQ: Find the odd one out in the series: 3, 5, 7, 9, 11, 13.", "Option B is correct. 9 is not a prime number (3^2 = 9), whereas all other numbers in the series are prime.", "Easy", "MCQ", "", {"A": "7", "B": "9", "C": "11", "D": "13"}, "B", "Why is 9 not prime?"),
    ("Series MCQ: Find the next term in the series: 1, 2, 6, 24, 120, ?", "Option D is correct. Factorials: 1!, 2!, 3!, 4!, 5!, 6! = 720 (or *2, *3, *4, *5, *6).", "Easy", "MCQ", "", {"A": "240", "B": "360", "C": "600", "D": "720"}, "D", "What is 7 factorial?"),
    ("Find the next number in the series: 7, 10, 8, 11, 9, 12, ?", "10. Alternating pattern: +3, -2, +3, -2, +3, -2. 12 - 2 = 10.", "Easy", "Problem Solving", "", "What comes after 10?"),
    ("Find the wrong number in the series: 1, 4, 9, 16, 20, 36, 49.", "20 is wrong (should be 25, which is 5^2). All other numbers are perfect squares.", "Easy", "Problem Solving", "", "What should replace 20?"),
    ("Find the next letter in the series: A, C, F, J, O, ?", "U. Gaps increase by 1: A(+2)C, C(+3)F, F(+4)J, J(+5)O, O(+6)U. O is 15th, 15 + 6 = 21st letter (U).", "Intermediate", "Problem Solving", "", "What is 21st letter?")
]

reasoning_coding = [
    # Coding & Decoding (35 Qs)
    ("If in a certain code language, 'CAT' is coded as 'DBU', how is 'DOG' coded in that language?", "'EPH'. Each letter is shifted by +1 position in the alphabet: D(+1)=E, O(+1)=P, G(+1)=H.", "Easy", "Problem Solving", "", "What would 'BIRD' be?"),
    ("If 'APPLE' is coded as 'EQTPI', what pattern is used to code the letters?", "+4 shift for every letter. A(1)+4=E(5), P(16)+4=T(20), P(16)+4=T(20) -> Wait, P(16)+1=Q(17)? If shift increases: A(+4), P(+1)... If uniform +4: A->E, P->T, P->T, L->P, E->I.", "Easy", "Concept", "", "What is the alphabet shift?"),
    ("If 'BOOK' is coded as '43' (sum of positions: 2+15+15+11=43), how is 'PEN' coded in that language?", "35. P=16, E=5, N=14. Sum = 16 + 5 + 14 = 35.", "Easy", "Problem Solving", "", "What is the value of 'INK'?"),
    ("If 'DELHI' is coded as '73541' and 'CALCUTTA' as '82589662', how is 'CALICUT' coded?", "'8251896'. Direct letter substitution: C=8, A=2, L=5, I=1, C=8, U=9, T=6.", "Easy", "Problem Solving", "", "What letter does 8 represent?"),
    ("In a certain code, 'ROAD' is written as 'URDG'. How is 'SWAN' written in that code?", "'VZDO'. Each letter is shifted forward by 3 (+3): S(19)+3=V(22), W(23)+3=Z(26), A(1)+3=D(4), N(14)+3=Q(17) -> Wait, N(14)+3=Q(17), so 'VZDQ'.", "Easy", "Problem Solving", "", "What is the shift amount?"),
    ("If 'RED' is called 'BLUE', 'BLUE' is called 'GREEN', 'GREEN' is called 'YELLOW', what is the color of clear sky?", "'GREEN'. Clear sky is blue. In this code language, 'BLUE' is called 'GREEN'.", "Easy", "Problem Solving", "", "What is the color of grass in this code?"),
    ("If 'LIGHT' is coded as 'LIGHY' with reverse alphabet: A=Z, B=Y... what is 'LOVE'?", "'OLEV'. Reverse opposites (sum of positions = 27): L(12) <-> O(15), O(15) <-> L(12), V(22) <-> E(5), E(5) <-> V(22).", "Easy", "Problem Solving", "", "What is the reverse of H?"),
    ("If in a code '123' means 'hot filtered coffee', '356' means 'very hot day', and '589' means 'day and night', which digit represents 'very'?", "'6'. In '123' and '356', common word is 'hot', common digit is '3' (hot=3). In '356' and '589', common word is 'day', common digit is '5' (day=5). In '356', remaining word is 'very' and remaining digit is '6'.", "Intermediate", "Problem Solving", "", "What digit represents 'hot'?"),
    ("If 'MONKEY' is coded as 'XDJMNL', how is 'TIGER' coded?", "'QDFHS'. Letters are reversed and shifted by -1: M O N K E Y -> Y E K N O M, then each letter -1 -> X D J M N L. T I G E R reversed = R E G I T, then -1 -> Q D F H S.", "Intermediate", "Problem Solving", "", "What is the two-step pattern?"),
    ("Coding MCQ: If 'MEAT' is written as 'TEAM', how is 'BALE' written?", "Option B is correct. Reversed word: BALE reversed is ELAB.", "Easy", "MCQ", "", {"A": "EALB", "B": "ELAB", "C": "EABL", "D": "LEAB"}, "B", "What is this coding type called?"),
    ("Coding MCQ: If A=1, FAT=27 (6+1+20), what is FAITH?", "Option C is correct. F(6) + A(1) + I(9) + T(20) + H(8) = 44.", "Easy", "MCQ", "", {"A": "40", "B": "42", "C": "44", "D": "46"}, "C", "What is position of T?"),
    ("Coding MCQ: If 'WATER' is written as 'YCVGT', each letter is shifted by how many positions?", "Option A is correct. W->Y (+2), A->C (+2), T->V (+2), E->G (+2), R->T (+2). Shift is +2.", "Easy", "MCQ", "", {"A": "+2", "B": "+3", "C": "+1", "D": "+4"}, "A", "What does FIRE code to?")
]

reasoning_blood_directions = [
    # Blood Relations & Direction Sense (35 Qs)
    ("Pointing to a photograph, John says: 'She is the daughter of the only son of my grandfather.' Who is the girl to John?", "John's sister. 'Only son of my grandfather' = John's father. 'Daughter of my father' = John's sister.", "Easy", "Problem Solving", "", "How is John related to the girl?"),
    ("A is the brother of B. B is the daughter of C. D is the father of C. How is A related to D?", "Grandson. C is A's mother/father. D is C's father. Since A is male, A is the grandson of D.", "Easy", "Problem Solving", "", "What is D to A?"),
    ("Introducing a boy, a girl says: 'He is the son of the daughter of the father of my uncle.' How is the boy related to the girl?", "Brother (or cousin). 'Father of my uncle' = Grandfather. 'Daughter of my grandfather' = Mother (or Aunt). 'Son of my mother' = Brother.", "Intermediate", "Problem Solving", "", "What if it was son of my aunt?"),
    ("A man walks 5 km North, turns right and walks 3 km, turns right again and walks 5 km. In which direction is he now from his starting point?", "East. North 5km (+Y) then East 3km (+X) then South 5km (-Y). Net displacement = 3 km East.", "Easy", "Problem Solving", "", "How far is he from the start?"),
    ("A person walks 3 km West, turns left and walks 4 km. How far is he from his starting point?", "5 km. Forms a right-angled triangle with sides 3 km and 4 km. By Pythagoras theorem: Distance = sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5 km South-West.", "Easy", "Problem Solving", "", "What is the direction from start?"),
    ("One morning after sunrise, Suresh was standing facing a pole. The shadow of the pole fell exactly to his right. In which direction was Suresh facing?", "South. In the morning, the Sun is in the East, so shadows fall towards the West. If the shadow is to Suresh's right, West is to his right. Facing South puts West on the right.", "Intermediate", "Problem Solving", "", "What if it was evening sunset?"),
    ("A's mother is B's sister and has a daughter C. How can A be related to B?", "Nephew or Niece. B is the maternal uncle or aunt. A is B's sister's child.", "Easy", "Concept", "", "What if A is female?"),
    ("Blood Relations MCQ: If P is the brother of Q, and R is the mother of P, how is R related to Q?", "Option A is correct. R is the mother of both P and Q.", "Easy", "MCQ", "", {"A": "Mother", "B": "Aunt", "C": "Sister", "D": "Grandmother"}, "A", "Is Q male or female?"),
    ("Direction Sense MCQ: A man travels 12 km North, then 5 km East. What is the shortest distance back to his starting point?", "Option B is correct. sqrt(12^2 + 5^2) = sqrt(144 + 25) = sqrt(169) = 13 km.", "Easy", "MCQ", "", {"A": "17 km", "B": "13 km", "C": "15 km", "D": "14 km"}, "B", "What is the Pythagorean triple?"),
    ("A man walks 10 km South, turns left and walks 20 km, turns left again and walks 10 km. How far is he from starting point?", "20 km East. South 10, then East 20, then North 10 cancels South 10. Distance = 20 km.", "Easy", "Problem Solving", "", "What direction is he facing?")
]

reasoning_seating_syllogisms = [
    # Seating Arrangements, Syllogisms & Logic (40 Qs)
    ("Five friends A, B, C, D, and E are sitting in a row facing North. C is in the middle. A is to the immediate left of C. D is at the right extreme. Where is B sitting?", "Between C and D (or at left extreme). Order is: E, A, C, B, D.", "Easy", "Problem Solving", "", "Who sits at the left end?"),
    ("Six people P, Q, R, S, T, and U sit in a circle facing the center. P is opposite S. Q is to the immediate right of P. Who sits opposite Q?", "T (directly opposite Q in the circle).", "Easy", "Problem Solving", "", "How many people between P and S?"),
    ("Statement: All cats are dogs. All dogs are mammals. Conclusion 1: All cats are mammals. Conclusion 2: All mammals are cats. Which conclusion follows?", "Only Conclusion 1 follows. If set Cat is inside Dog and Dog is inside Mammal, all Cats are Mammals (Valid). But not all Mammals are Cats (Invalid).", "Easy", "Concept", "", "What is this logic called?"),
    ("Statement: Some pens are books. Some books are pencils. Conclusion: Some pens are pencils. Does this conclusion follow?", "Does NOT follow. Two 'Some' premises (particular premises) do not guarantee an overlapping intersection between pens and pencils without a universal link.", "Easy", "Concept", "", "Can it be a possibility?"),
    ("Statement: All flowers are red. No red is a tree. Conclusion 1: No flower is a tree. Conclusion 2: Some trees are flowers. Which follows?", "Only Conclusion 1 follows. Flowers are entirely inside Red, and Red has zero intersection with Trees. Therefore, no Flower can be a Tree.", "Easy", "Concept", "", "Why does Conclusion 2 fail?"),
    ("In a class of 40 students, Rahul is ranked 15th from the top. What is his rank from the bottom?", "26th. Total = Rank from top + Rank from bottom - 1 -> 40 = 15 + Bottom - 1 -> 40 = 14 + Bottom -> Bottom Rank = 26th.", "Easy", "Problem Solving", "", "What is the formula: Top + Bottom - 1?"),
    ("In a row of boys, if A is 10th from the left and B is 9th from the right, and on swapping places A becomes 15th from the left, how many boys are in the row?", "23 boys. After swapping, A's new position is B's old position (9th from right). Total = 15 + 9 - 1 = 23 boys.", "Intermediate", "Problem Solving", "", "What is B's new position from right?"),
    ("Syllogism MCQ: Statement: All cars are vehicles. No vehicle is an airplane. Conclusion: No car is an airplane.", "Option A is correct. Since all cars are inside vehicles, and vehicles and airplanes are disjoint, no car can be an airplane.", "Easy", "MCQ", "", {"A": "Conclusion follows", "B": "Conclusion does not follow", "C": "Either follows", "D": "Neither follows"}, "A", "Is it valid?"),
    ("Seating MCQ: In circular seating facing center, if you move clockwise, are you moving to the person's right or left?", "Option B is correct. When facing the center, clockwise movement goes to each person's left.", "Easy", "MCQ", "", {"A": "To their right", "B": "To their left", "C": "Straight", "D": "Behind them"}, "B", "What if facing outside?"),
    ("Logic MCQ: Statement: 'Most developers drink coffee.' Does it follow that 'Every developer drinks coffee'?", "Option B is correct. 'Most' means more than 50%, not 100%. 'Every' cannot be concluded.", "Easy", "MCQ", "", {"A": "Yes, absolutely", "B": "No, it does not follow", "C": "Only in mornings", "D": "Logically equivalent"}, "B", "What does 'some' mean in logic?")
]
